package online.wanan.xingchen.console;
import online.wanan.xingchen.security.XingChenProperties;import org.springframework.beans.factory.annotation.Value;import org.springframework.core.env.Environment;import org.springframework.http.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.Authentication;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.web.bind.annotation.*;import java.time.Instant;import java.util.*;
@RestController @RequestMapping("/api") public class AdminOperationsController {
 private final JdbcTemplate jdbc;private final UsageConsoleService usage;private final AccessControlService access;private final ConfigService config;private final Environment env;private final XingChenProperties props;private final PasswordEncoder encoder;private final SafeOperationalLogStore logs;private final ConsoleSessionGenerationRegistry sessions;
 private final EffectiveConsoleConfiguration effective;
 public AdminOperationsController(JdbcTemplate jdbc,UsageConsoleService usage,AccessControlService access,ConfigService config,Environment env,XingChenProperties props,PasswordEncoder encoder,SafeOperationalLogStore logs,ConsoleSessionGenerationRegistry sessions,EffectiveConsoleConfiguration effective){this.jdbc=jdbc;this.usage=usage;this.access=access;this.config=config;this.env=env;this.props=props;this.encoder=encoder;this.logs=logs;this.sessions=sessions;this.effective=effective;}
 private ResponseEntity<?> noStore(Object body){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).header("Pragma","no-cache").body(body);}
 @GetMapping("/usage/summary") public ResponseEntity<?> summary(@RequestParam(defaultValue="7d")String window,@RequestParam(required=false)String from,@RequestParam(required=false)String to,@RequestParam(required=false)String provider,@RequestParam(required=false)String model,@RequestParam(required=false)String conversation,@RequestParam(required=false)String person){return noStore(usage.summary(window,from,to,provider,model,conversation,person));}
 @GetMapping("/usage/series") public ResponseEntity<?> series(@RequestParam(defaultValue="7d")String window,@RequestParam(required=false)String from,@RequestParam(required=false)String to,@RequestParam(required=false)String provider,@RequestParam(required=false)String model,@RequestParam(required=false)String conversation,@RequestParam(required=false)String person){return noStore(usage.series(window,from,to,provider,model,conversation,person));}
 @GetMapping("/usage/breakdown") public ResponseEntity<?> breakdown(@RequestParam(defaultValue="7d")String window,@RequestParam(required=false)String from,@RequestParam(required=false)String to){return noStore(usage.breakdown(window,from,to));}
 @GetMapping("/usage/records") public ResponseEntity<?> records(@RequestParam(defaultValue="7d")String window,@RequestParam(required=false)String from,@RequestParam(required=false)String to,@RequestParam(required=false)String provider,@RequestParam(required=false)String model,@RequestParam(required=false)String conversation,@RequestParam(required=false)String person,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size){return noStore(usage.records(window,from,to,provider,model,conversation,person,page,size));}
 @GetMapping("/pricing") public ResponseEntity<?> pricing(){return noStore(Map.of("revision",revision(),"unit","currency per 1,000,000 tokens","rows",jdbc.queryForList("SELECT provider,model,input,cache_hit cacheHit,cache_miss cacheMiss,output,reasoning,currency,revision,updated_at updatedAt FROM console_pricing ORDER BY provider,model")));}
 @org.springframework.transaction.annotation.Transactional @PatchMapping("/pricing") public ResponseEntity<?> savePricing(@RequestBody PricingPatch p,Authentication auth){if(p==null||p.rows()==null||p.rows().isEmpty()||p.rows().size()>300)throw new IllegalArgumentException("At least one pricing row is required");if(p.revision()!=revision())throw new java.util.ConcurrentModificationException();Set<String> keys=new HashSet<>();for(var r:p.rows())if(r.provider()==null||r.provider().isBlank()||r.provider().length()>80||r.model()==null||r.model().isBlank()||r.model().length()>160||r.currency()==null||!r.currency().matches("[A-Z]{3}")||!valid(r.input())||!valid(r.cacheHit())||!valid(r.cacheMiss())||!valid(r.output())||!valid(r.reasoning())||!keys.add(r.provider()+"\u0000"+r.model()))throw new IllegalArgumentException("Invalid pricing row");if(jdbc.update("UPDATE console_pricing_meta SET revision=revision+1 WHERE singleton=1 AND revision=?",p.revision())!=1)throw new java.util.ConcurrentModificationException();var oldRows=jdbc.queryForList("SELECT * FROM console_pricing");String now=Instant.now().toString();long next=p.revision()+1;jdbc.update("DELETE FROM console_pricing");for(var r:p.rows()){Map<String,Object> old=oldRows.stream().filter(x->Objects.equals(x.get("provider"),r.provider())&&Objects.equals(x.get("model"),r.model())).findFirst().orElse(Map.of());jdbc.update("INSERT INTO console_pricing(provider,model,input,cache_hit,cache_miss,output,reasoning,currency,revision,updated_at,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)",r.provider(),r.model(),r.input(),r.cacheHit(),r.cacheMiss(),r.output(),r.reasoning(),r.currency(),next,now,auth.getName());jdbc.update("INSERT INTO console_pricing_audit(occurred_at,actor,provider,model,old_input,new_input,old_cache_hit,new_cache_hit,old_cache_miss,new_cache_miss,old_output,new_output,old_reasoning,new_reasoning,currency,revision) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",now,auth.getName(),r.provider(),r.model(),old.get("input"),r.input(),old.get("cache_hit"),r.cacheHit(),old.get("cache_miss"),r.cacheMiss(),old.get("output"),r.output(),old.get("reasoning"),r.reasoning(),r.currency(),next);}jdbc.update("INSERT INTO console_configuration_audit(occurred_at,actor,category,config_key,action) VALUES(?,?,?,?,?)",now,auth.getName(),"Pricing","rates","UPDATE_NUMERIC");return noStore(Map.of("revision",revision()));}
 private boolean valid(java.math.BigDecimal v){return UsageCostAccounting.validRate(v);} private long revision(){return jdbc.queryForObject("SELECT revision FROM console_pricing_meta WHERE singleton=1",Long.class);}
 public record PriceRow(String provider,String model,java.math.BigDecimal input,java.math.BigDecimal cacheHit,java.math.BigDecimal cacheMiss,java.math.BigDecimal output,java.math.BigDecimal reasoning,String currency){} public record PricingPatch(long revision,List<PriceRow> rows){}
 @GetMapping("/access/policy") public ResponseEntity<?> policy(){return noStore(access.policy());}
 @PatchMapping("/access/rules") public ResponseEntity<?> rules(@RequestBody AccessPatch p,Authentication auth){if(p==null)throw new IllegalArgumentException("Invalid access policy");return noStore(access.replace(p.rules(),p.revision(),auth.getName()));}
 public record AccessPatch(long revision,List<AccessControlService.Rule> rules){}
 @GetMapping("/access/preview") public ResponseEntity<?> preview(@RequestParam String platform,@RequestParam String actorId,@RequestParam String scope,@RequestParam String conversationId){if(!Set.of("QQ","DISCORD","TELEGRAM","OTHER").contains(platform.toUpperCase(Locale.ROOT))||!Set.of("PRIVATE","GROUP").contains(scope)||!actorId.matches("[A-Za-z0-9_-]{1,128}")||!conversationId.matches("[A-Za-z0-9_-]{1,128}"))throw new IllegalArgumentException("Invalid stable identity");var d=access.evaluate(platform,actorId,scope,conversationId,actorId.equals(props.owner().platformUserId()));return noStore(Map.of("decision",d.allowed()?"ALLOW":"DENY","reason",d.reason()));}
 @GetMapping("/security/posture") public ResponseEntity<?> posture(){boolean credential=jdbc.queryForObject("SELECT COUNT(*) FROM console_admin_credentials",Integer.class)>0;String mode=Arrays.stream(env.getActiveProfiles()).anyMatch(p->p.contains("fake")||p.contains("test"))?"FAKE_PROFILE_ACTIVE":"PRODUCTION_PROFILE";Map<String,Object> p=new LinkedHashMap<>();p.put("authenticationEnabled",true);p.put("passwordConfigured",credential);p.put("sessionTimeout",env.getProperty("server.servlet.session.timeout","30m"));p.put("csrfEnabled",true);p.put("passwordEncoder","BCrypt cost 12");p.put("cookieHttpOnly",true);p.put("cookieSameSite","Strict");p.put("cookieSecure",effective.cookieSecure());p.put("bindAddress",props.console().bind());p.put("trustedProxyConfigured",!props.console().trustedProxies().isEmpty());p.put("publicBaseUrlConfigured",!effective.publicBaseUrl().isBlank());p.put("secretStore",config.secretStatus());p.put("gatewayEndpointPolicy","numeric loopback only");p.put("providerEndpointPolicy","validated outbound URL policy");p.put("profileMode",mode);p.put("externalIntegrationsEnabled",!mode.equals("FAKE_PROFILE_ACTIVE")&&Boolean.parseBoolean(env.getProperty("xingchen.social.enabled","false")));p.put("hardSecurity","CSRF, BCrypt, redaction and capability/path guards enforced; no disable control");return noStore(p);}
 @PostMapping("/security/password") public ResponseEntity<?> changePassword(@RequestBody PasswordChange p,Authentication auth,jakarta.servlet.http.HttpServletRequest request){if(p==null||p.currentPassword()==null||p.newPassword()==null||!p.newPassword().equals(p.confirmation())||p.newPassword().length()<14||p.newPassword().getBytes(java.nio.charset.StandardCharsets.UTF_8).length>72||p.newPassword().chars().distinct().count()<4)throw new IllegalArgumentException("New password must be confirmed, at least 14 characters, at most 72 UTF-8 bytes, and have varied characters");var row=jdbc.query("SELECT password_hash FROM console_admin_credentials WHERE username=?",rs->rs.next()?rs.getString(1):null,auth.getName());if(row==null||!encoder.matches(p.currentPassword(),row))throw new SecurityException("Current password is incorrect");String now=Instant.now().toString();jdbc.update("UPDATE console_admin_credentials SET password_hash=?,auth_generation=auth_generation+1,updated_at=? WHERE username=?",encoder.encode(p.newPassword()),now,auth.getName());jdbc.update("INSERT INTO console_configuration_audit(occurred_at,actor,category,config_key,action) VALUES(?,?,?,?,?)",now,auth.getName(),"Security","credential","PASSWORD_CHANGED");logs.record("INFO","SECURITY","PASSWORD_CHANGED");sessions.invalidateUser(auth.getName());var session=request.getSession(false);if(session!=null)session.invalidate();org.springframework.security.core.context.SecurityContextHolder.clearContext();return noStore(Map.of("changed",true,"reauthenticationRequired",true));}
 public record PasswordChange(String currentPassword,String newPassword,String confirmation){}
 @GetMapping("/logs/operational") public ResponseEntity<?> operational(@RequestParam(required=false)String level,@RequestParam(required=false)String component,@RequestParam(required=false)String from,@RequestParam(required=false)String to,@RequestParam(required=false)String correlationId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size){return noStore(Map.of("retention","bounded in-memory recent events","limit",logs.retention(),"records",logs.list(level,component,from,to,correlationId,page,size)));}
 @GetMapping("/logs/audit") public ResponseEntity<?> audit(@RequestParam(required=false)String category,@RequestParam(required=false)String actor,@RequestParam(required=false)String operation,@RequestParam(required=false)String from,@RequestParam(required=false)String to,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size){if(page<0||size<1||size>100)throw new IllegalArgumentException("Invalid page bounds");String start=utc(from),end=utc(to);String union="SELECT occurred_at,actor,category,config_key target,action operation FROM console_configuration_audit UNION ALL SELECT occurred_at,actor,'CONVERSATION',conversation_id,operation FROM conversation_console_audit UNION ALL SELECT occurred_at,actor,'RELATIONSHIP',person_id,operation FROM relationship_console_audit UNION ALL SELECT occurred_at,actor,'MEMORY',memory_id,operation FROM memory_console_audit UNION ALL SELECT occurred_at,actor,'PROMPT',layer,operation FROM prompt_console_audit UNION ALL SELECT occurred_at,actor,'SOCIAL_SETTINGS',setting_key,'UPDATE' FROM social_settings_audit UNION ALL SELECT occurred_at,actor,'MODEL_PROVIDER',provider_id,setting_key FROM model_provider_audit UNION ALL SELECT occurred_at,actor,'SLANG',term_id,action FROM slang_console_audit UNION ALL SELECT occurred_at,actor,'ACCESS',stable_id,'RULE_'||COALESCE(old_effect,'NONE')||'_TO_'||new_effect FROM console_access_audit UNION ALL SELECT occurred_at,actor,'PRICING',provider||'/'||model,'RATES_REVISION_'||revision FROM console_pricing_audit";String sql="SELECT occurred_at timestamp,actor,category,target,operation FROM ("+union+") WHERE (? IS NULL OR category=?) AND (? IS NULL OR actor=?) AND (? IS NULL OR operation=?) AND (? IS NULL OR occurred_at>=?) AND (? IS NULL OR occurred_at<=?) ORDER BY occurred_at DESC LIMIT ? OFFSET ?";return noStore(jdbc.queryForList(sql,blank(category),blank(category),blank(actor),blank(actor),blank(operation),blank(operation),start,start,end,end,size,page*size));}
 private String utc(String value){if(value==null||value.isBlank())return null;try{return java.time.Instant.parse(value).toString();}catch(Exception ex){throw new IllegalArgumentException("Audit time filter must be an ISO-8601 UTC instant");}}
 private String blank(String s){return s==null||s.isBlank()?null:s;}
}
