package online.wanan.xingchen.console;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import online.wanan.xingchen.core.conversation.ConversationControlPort;
import online.wanan.xingchen.core.agent.ClosedAgentAccessPolicy;
import online.wanan.xingchen.core.model.ConversationType;
import online.wanan.xingchen.security.XingChenProperties;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.*;

/** Bounded administrative read model and mutation facade; controllers never assemble SQL/runtime state. */
@Service
public final class ConversationConsoleService {
    private static final int MAX_PAGE_SIZE=100,MAX_PAGE=10000;
    private static final String ACTIVE="EXISTS(SELECT 1 FROM durable_turn_executions dt WHERE dt.conversation_id=c.id AND dt.status IN ('RUNNING','RECOVERING'))";
    private final JdbcTemplate jdbc;private final NamedParameterJdbcTemplate named;private final ConversationControlPort runtime;private final ObjectMapper mapper;private final XingChenProperties properties;private final ClosedAgentAccessPolicy closedPolicy;

    public ConversationConsoleService(JdbcTemplate jdbc,NamedParameterJdbcTemplate named,ConversationControlPort runtime,ObjectMapper mapper,XingChenProperties properties,ClosedAgentAccessPolicy closedPolicy){this.jdbc=jdbc;this.named=named;this.runtime=runtime;this.mapper=mapper;this.properties=properties;this.closedPolicy=closedPolicy;}

    public Map<String,Object> list(String query,String type,String mode,String state,Boolean hasUnknown,Boolean interrupted,int page,int size){
        if(page<0||page>MAX_PAGE||size<1||size>MAX_PAGE_SIZE)throw new IllegalArgumentException("分页参数超出允许范围");
        StringBuilder where=new StringBuilder(" WHERE 1=1");MapSqlParameterSource args=new MapSqlParameterSource();
        if(query!=null&&!query.isBlank()){String q=query.strip();if(q.length()>100)throw new IllegalArgumentException("搜索内容过长");where.append(" AND (lower(c.platform_conversation_id) LIKE lower(:q) OR EXISTS(SELECT 1 FROM memberships sm JOIN persons sp ON sp.id=sm.person_id LEFT JOIN person_aliases sa ON sa.person_id=sp.id WHERE sm.conversation_id=c.id AND (lower(COALESCE(NULLIF(sm.card,''),NULLIF(sm.current_display_name,''),'')) LIKE lower(:q) OR lower(COALESCE(sa.alias,'')) LIKE lower(:q))))");args.addValue("q","%"+q+"%");}
        if(type!=null&&!type.isBlank()){String normalized=type.toUpperCase(Locale.ROOT);if(!Set.of("PRIVATE","GROUP").contains(normalized))throw new IllegalArgumentException("会话类型无效");where.append(" AND c.type=:type");args.addValue("type",normalized);}
        if(mode!=null&&!mode.isBlank()){String normalized=mode.toUpperCase(Locale.ROOT);if(!Set.of("SOCIAL","CLOSED_AGENT").contains(normalized))throw new IllegalArgumentException("会话模式无效");where.append(" AND COALESCE(s.mode,'SOCIAL')=:mode");args.addValue("mode",normalized);}
        String stateExpr="CASE WHEN "+ACTIVE+" THEN 'ACTIVE' WHEN s.wake_state='WAITING' THEN 'WAITING' WHEN s.wake_state='SLEEPING' OR s.wake_state='IDLE' THEN 'SLEEPING' ELSE 'ACTIVE' END";
        if(state!=null&&!state.isBlank()){String normalized=state.toUpperCase(Locale.ROOT);if(!Set.of("ACTIVE","WAITING","SLEEPING").contains(normalized))throw new IllegalArgumentException("运行状态无效");where.append(" AND ").append(stateExpr).append("=:state");args.addValue("state",normalized);}
        if(hasUnknown!=null){where.append(hasUnknown?" AND ":" AND NOT ").append("EXISTS(SELECT 1 FROM onebot_outbound_executions u WHERE u.conversation_id=c.id AND u.status='UNKNOWN')");}
        if(interrupted!=null){where.append(interrupted?" AND ":" AND NOT ").append("EXISTS(SELECT 1 FROM durable_turn_executions i WHERE i.conversation_id=c.id AND i.status='INTERRUPTED')");}
        String base=" FROM conversations c LEFT JOIN simulation_conversation_state s ON s.conversation_id=c.id"+where;
        long total=named.queryForObject("SELECT COUNT(*)"+base,args,Long.class);
        String sql="SELECT c.id,c.platform,c.type,c.platform_conversation_id,c.created_at,COALESCE(s.mode,'SOCIAL') AS mode,COALESCE(s.wake_state,'AWAKE') AS wake_state,COALESCE(s.generation,0) AS generation,s.last_read_cursor,s.last_incoming_at,s.waiting_since,s.origin_turn_id,"+
                "CASE WHEN c.type='PRIVATE' THEN COALESCE((SELECT COALESCE(NULLIF(m.card,''),NULLIF(m.current_display_name,'')) FROM memberships m WHERE m.conversation_id=c.id ORDER BY m.last_seen_at DESC LIMIT 1),c.platform_conversation_id) ELSE c.platform_conversation_id END AS display_name,"+
                "(SELECT COUNT(*) FROM memberships m WHERE m.conversation_id=c.id) AS member_count,(SELECT MAX(m.created_at) FROM messages m WHERE m.conversation_id=c.id) AS last_activity,"+
                "(SELECT COUNT(*) FROM onebot_outbound_executions u WHERE u.conversation_id=c.id AND u.status='UNKNOWN') AS unknown_count,"+
                "(SELECT COUNT(*) FROM durable_turn_executions i WHERE i.conversation_id=c.id AND i.status='INTERRUPTED') AS interrupted_count,"+
                "(SELECT COUNT(*) FROM durable_turn_executions a WHERE a.conversation_id=c.id AND a.status IN ('RUNNING','RECOVERING')) AS active_turn_count,"+
                "CASE WHEN s.last_read_cursor IS NULL THEN (SELECT COUNT(*) FROM messages um WHERE um.conversation_id=c.id AND um.is_self=0) WHEN trim(s.last_read_cursor)<>'' AND s.last_read_cursor NOT GLOB '*[^0-9]*' THEN (SELECT COUNT(*) FROM messages um WHERE um.conversation_id=c.id AND um.is_self=0 AND um.platform_message_id NOT GLOB '*[^0-9]*' AND CAST(um.platform_message_id AS INTEGER)>CAST(s.last_read_cursor AS INTEGER)) ELSE NULL END AS unread_count,"+stateExpr+" AS runtime_state"+base+" ORDER BY COALESCE(last_activity,c.created_at) DESC,c.id LIMIT :limit OFFSET :offset";
        args.addValue("limit",size).addValue("offset",(long)page*size);
        List<Map<String,Object>> items=named.queryForList(sql,args);return Map.of("items",items,"total",total,"page",page,"size",size,"maxSize",MAX_PAGE_SIZE);
    }

    public Map<String,Object> detail(UUID id){Map<String,Object> summary=findSummary(id);String lane=lane(summary);Map<String,Object> result=new LinkedHashMap<>(summary);
        result.put("canWake",ownerPrivate(id,summary));Map<String,Object> simulation=new LinkedHashMap<>();for(String key:List.of("mode","wake_state","generation","last_read_cursor","last_incoming_at","waiting_since","origin_turn_id"))simulation.put(key,summary.getOrDefault(key,null));
        simulation.put("waitReason",safeWaitReason(id));simulation.put("sleepUntil",single("SELECT sleep_until FROM simulation_conversation_state WHERE conversation_id=?",id.toString()));simulation.put("queueDepth",runtime.queuedFor(lane));simulation.put("active",runtime.laneActive(lane));
        simulation.put("activeTurn",turn(id,false));simulation.put("interruptedTurn",turn(id,true));simulation.put("unknownOutbound",unknownOutbound(id));result.put("runtime",simulation);result.put("context",context(id));result.put("dsh",dsh(id));result.put("pending",pending(id));result.put("members",members(id,0,20));result.put("recentMessages",messages(id,0,20));return result;}

    public Map<String,Object> members(UUID id,int page,int size){requireConversation(id);checkPage(page,size);long total=jdbc.queryForObject("SELECT COUNT(*) FROM memberships WHERE conversation_id=?",Long.class,id.toString());List<Map<String,Object>> rows=jdbc.query("SELECT p.id AS personId,p.platform,p.platform_user_id AS platformUserId,COALESCE(NULLIF(m.card,''),NULLIF(m.current_display_name,''),p.platform_user_id) AS displayName,m.platform_role AS platformRole,p.is_self AS self,p.is_owner AS owner,m.last_seen_at AS lastSeen FROM memberships m JOIN persons p ON p.id=m.person_id WHERE m.conversation_id=? ORDER BY p.is_owner DESC,p.is_self DESC,displayName LIMIT ? OFFSET ?",(rs,n)->{String role=rs.getInt("self")!=0?"SELF":rs.getInt("owner")!=0?"OWNER":rs.getString("platformRole");Map<String,Object> row=new LinkedHashMap<>();row.put("personId",rs.getString("personId"));row.put("platform",rs.getString("platform"));row.put("platformUserId",rs.getString("platformUserId"));row.put("displayName",rs.getString("displayName"));row.put("role",role);row.put("self",rs.getInt("self")!=0);row.put("owner",rs.getInt("owner")!=0);row.put("lastSeen",rs.getString("lastSeen"));return row;},id.toString(),size,(long)page*size);return Map.of("items",rows,"total",total,"page",page,"size",size);}

    public Map<String,Object> messages(UUID id,int page,int size){requireConversation(id);checkPage(page,size);long total=jdbc.queryForObject("SELECT COUNT(*) FROM messages WHERE conversation_id=?",Long.class,id.toString());List<Map<String,Object>> rows=jdbc.query("SELECT m.platform_message_id,m.actor_person_id,p.platform_user_id,COALESCE(NULLIF(mm.card,''),NULLIF(mm.current_display_name,''),p.platform_user_id) AS sender,m.text,m.message_type,m.reply_to_message_id,m.created_at,m.raw_metadata_json,m.is_self FROM messages m JOIN persons p ON p.id=m.actor_person_id LEFT JOIN memberships mm ON mm.person_id=p.id AND mm.conversation_id=m.conversation_id WHERE m.conversation_id=? ORDER BY m.created_at DESC,m.platform_message_id DESC LIMIT ? OFFSET ?",(rs,n)->safeMessage(rs),id.toString(),size,(long)page*size);return Map.of("items",rows,"total",total,"page",page,"size",size);}

    public ConversationControlPort.SimulationSnapshot mode(UUID id,String mode,long expected,String actor){Map<String,Object> meta=findSummary(id);String old=Objects.toString(meta.get("mode"),"SOCIAL");boolean owner=ownerPrivate(id,meta);String normalized=mode==null?"":mode.toUpperCase(Locale.ROOT);return audited(id,actor,"MODE_CHANGED",old,normalized,()->{if(normalized.equals("CLOSED_AGENT")&&!closedPolicy.allows(ConversationType.valueOf(meta.get("type").toString()),owner,normalized,owner))throw new SecurityException("closed-agent mode requires the configured owner in a private conversation");return runtime.changeMode(lane(meta),id,normalized,expected,owner);});}
    public ConversationControlPort.SimulationSnapshot wake(UUID id,long expected,String actor){Map<String,Object> meta=findSummary(id);boolean owner=ownerPrivate(id,meta);return audited(id,actor,"MANUAL_WAKE",Objects.toString(meta.get("wake_state"),"AWAKE"),"AWAKE",()->{if(!owner)throw new SecurityException("manual wake requires the configured owner private conversation");if("WAITING".equals(meta.get("wake_state")))throw new IllegalStateException("WAITING conversations must be reset to retire the pending turn safely");return runtime.wake(lane(meta),id,expected,owner);});}
    public ConversationControlPort.SimulationSnapshot reset(UUID id,long expected,String actor){Map<String,Object> meta=findSummary(id);String old=Objects.toString(meta.get("wake_state"),"AWAKE")+"/g"+meta.get("generation");return audited(id,actor,"RESET",old,"IDLE",()->runtime.reset(lane(meta),id,expected));}

    private ConversationControlPort.SimulationSnapshot audited(UUID id,String actor,String operation,String old,String next,java.util.function.Supplier<ConversationControlPort.SimulationSnapshot> work){try{var result=work.get();jdbc.update("INSERT INTO conversation_console_audit(occurred_at,actor,conversation_id,operation,old_summary,new_summary,result) VALUES(?,?,?,?,?,?,?)",Instant.now().toString(),actor,id.toString(),operation,safeSummary(old),safeSummary(next),"SUCCESS");return result;}catch(RuntimeException failure){jdbc.update("INSERT INTO conversation_console_audit(occurred_at,actor,conversation_id,operation,old_summary,new_summary,result) VALUES(?,?,?,?,?,?,?)",Instant.now().toString(),actor,id.toString(),operation,safeSummary(old),safeSummary(next),failure instanceof java.util.ConcurrentModificationException?"CONFLICT":"REJECTED");throw failure;}}
    private boolean ownerPrivate(UUID id,Map<String,Object> meta){if(!"PRIVATE".equals(meta.get("type")))return false;var owner=properties.owner();if(owner==null||owner.platformUserId()==null||owner.platformUserId().isBlank())return false;String platform=owner.platform()==null?"QQ":owner.platform().toUpperCase(Locale.ROOT);return jdbc.queryForObject("SELECT COUNT(*) FROM memberships m JOIN persons p ON p.id=m.person_id WHERE m.conversation_id=? AND p.platform=? AND p.platform_user_id=? AND p.is_owner=1",Integer.class,id.toString(),platform,owner.platformUserId())>0;}

    private Map<String,Object> findSummary(UUID id){String stateExpr="CASE WHEN "+ACTIVE+" THEN 'ACTIVE' WHEN s.wake_state='WAITING' THEN 'WAITING' WHEN s.wake_state='SLEEPING' OR s.wake_state='IDLE' THEN 'SLEEPING' ELSE 'ACTIVE' END";String sql="SELECT c.id,c.platform,c.type,c.platform_conversation_id,c.created_at,COALESCE(s.mode,'SOCIAL') AS mode,COALESCE(s.wake_state,'AWAKE') AS wake_state,COALESCE(s.generation,0) AS generation,s.last_read_cursor,s.last_incoming_at,s.waiting_since,s.origin_turn_id,CASE WHEN c.type='PRIVATE' THEN COALESCE((SELECT COALESCE(NULLIF(m.card,''),NULLIF(m.current_display_name,'')) FROM memberships m WHERE m.conversation_id=c.id ORDER BY m.last_seen_at DESC LIMIT 1),c.platform_conversation_id) ELSE c.platform_conversation_id END AS display_name,(SELECT COUNT(*) FROM memberships m WHERE m.conversation_id=c.id) AS member_count,(SELECT MAX(m.created_at) FROM messages m WHERE m.conversation_id=c.id) AS last_activity,(SELECT COUNT(*) FROM onebot_outbound_executions u WHERE u.conversation_id=c.id AND u.status='UNKNOWN') AS unknown_count,(SELECT COUNT(*) FROM durable_turn_executions i WHERE i.conversation_id=c.id AND i.status='INTERRUPTED') AS interrupted_count,"+stateExpr+" AS runtime_state FROM conversations c LEFT JOIN simulation_conversation_state s ON s.conversation_id=c.id WHERE c.id=?";return jdbc.query(sql,(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();for(String key:List.of("id","platform","type","platform_conversation_id","created_at","mode","wake_state","generation","last_read_cursor","last_incoming_at","waiting_since","origin_turn_id","display_name","member_count","last_activity","unknown_count","interrupted_count","runtime_state"))m.put(key,rs.getObject(key));return m;},id.toString()).stream().findFirst().orElseThrow(()->new ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"conversation not found"));}
    private void requireConversation(UUID id){if(jdbc.queryForObject("SELECT COUNT(*) FROM conversations WHERE id=?",Integer.class,id.toString())==0)throw new ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"conversation not found");}
    private void checkPage(int page,int size){if(page<0||page>MAX_PAGE||size<1||size>MAX_PAGE_SIZE)throw new IllegalArgumentException("分页参数超出允许范围");}
    private String lane(Map<String,Object> meta){return meta.get("platform")+":"+meta.get("type")+":"+meta.get("platform_conversation_id");}
    private Object single(String sql,Object...args){return jdbc.query(sql,rs->rs.next()?rs.getObject(1):null,args);}
    private String safeWaitReason(UUID id){Object value=single("SELECT wait_reason FROM simulation_conversation_state WHERE conversation_id=?",id.toString());if(value==null)return "";String reason=value.toString().replaceAll("[^A-Za-z0-9 _.-]","");return reason.length()>80?reason.substring(0,80):reason;}
    private Object turn(UUID id,boolean interrupted){String statuses=interrupted?"'INTERRUPTED'":"'RUNNING','RECOVERING'";List<Map<String,Object>> rows=jdbc.query("SELECT turn_id,generation,model_turn_state,status,claimed_at,updated_at FROM durable_turn_executions WHERE conversation_id=? AND status IN ("+statuses+") ORDER BY updated_at DESC LIMIT 1",(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();String tid=rs.getString("turn_id");m.put("turnId",tid.length()>8?tid.substring(0,8):tid);m.put("generation",rs.getLong("generation"));m.put("executionState",rs.getString("model_turn_state"));m.put("status",rs.getString("status"));m.put("startedAt",rs.getString("claimed_at"));m.put("updatedAt",rs.getString("updated_at"));m.put("reason",interrupted?"Turn requires operator review; automatic replay is blocked.":"");return m;},id.toString());return rows.isEmpty()?null:rows.getFirst();}
    private List<Map<String,Object>> unknownOutbound(UUID id){return jdbc.query("SELECT logical_message_id,turn_id,created_at,status FROM onebot_outbound_executions WHERE conversation_id=? AND status='UNKNOWN' ORDER BY updated_at DESC LIMIT 20",(rs,n)->Map.of("logicalMessageId",shortId(rs.getString(1)),"turnId",shortId(rs.getString(2)),"timestamp",rs.getString(3),"status",rs.getString(4)),id.toString());}
    private Map<String,Object> context(UUID id){Map<String,Object> result=new LinkedHashMap<>();var rows=jdbc.query("SELECT * FROM context_diagnostics WHERE conversation_id=?",(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();m.put("currentEstimate",rs.getInt("total_tokens"));m.put("personaTokens",rs.getInt("persona_tokens"));m.put("simulationTokens",rs.getInt("simulation_tokens"));m.put("memoryTokens",rs.getInt("memory_tokens"));m.put("recentTokens",rs.getInt("recent_tokens"));m.put("summaryTokens",rs.getInt("summary_tokens"));m.put("includedMemoryCount",rs.getInt("included_memory_count"));m.put("excludedMemoryCount",rs.getInt("excluded_memory_count"));m.put("lifecycleState",rs.getString("lifecycle_state"));m.put("updatedAt",rs.getString("updated_at"));return m;},id.toString());if(!rows.isEmpty())result.putAll(rows.getFirst());else{result.put("currentEstimate",0);result.put("lifecycleState","UNKNOWN");}
        result.put("thresholds",Map.of("soft",properties.context().softLimitTokens(),"rollover",properties.context().rolloverTokens(),"hard",properties.context().hardLimitTokens()));result.put("recentMessageCount",jdbc.queryForObject("SELECT COUNT(*) FROM messages WHERE conversation_id=?",Integer.class,id.toString()));result.put("unreadCount",unreadCount(id));
        List<Map<String,Object>> session=jdbc.query("SELECT generation,status,estimated_context_tokens,last_rollover_at,updated_at FROM session_state WHERE conversation_id=?",(rs,n)->Map.of("generation",rs.getLong(1),"status",rs.getString(2),"estimatedTokens",rs.getInt(3),"lastRolloverAt",Objects.toString(rs.getString(4),""),"updatedAt",rs.getString(5)),id.toString());result.put("session",session.isEmpty()?Map.of():session.getFirst());
        List<Map<String,Object>> handoff=jdbc.query("SELECT generation,created_at FROM session_handoffs WHERE conversation_id=? ORDER BY generation DESC LIMIT 1",(rs,n)->Map.of("generation",rs.getLong(1),"createdAt",rs.getString(2)),id.toString());result.put("handoff",handoff.isEmpty()?Map.of("status","NONE"):Map.of("status","AVAILABLE","latest",handoff.getFirst()));return result;}
    private Map<String,Object> dsh(UUID id){List<Map<String,Object>> rows=jdbc.query("SELECT session_id,status,generation,updated_at FROM dsh_session_mappings WHERE conversation_id=? AND status='CURRENT' ORDER BY generation DESC LIMIT 1",(rs,n)->Map.of("mappingExists",true,"sessionId",shortId(rs.getString(1)),"status",rs.getString(2),"generation",rs.getLong(3),"lastActivity",rs.getString(4)),id.toString());return rows.isEmpty()?Map.of("mappingExists",false,"sessionId","","status","NONE"):rows.getFirst();}
    private Map<String,Object> pending(UUID id){Map<String,Object> result=new LinkedHashMap<>();result.put("questions",safeCount("SELECT COUNT(*) FROM pending_questions WHERE conversation_id=? AND status='PENDING'",id.toString()));result.put("approvals",safeCount("SELECT COUNT(*) FROM pending_approvals WHERE conversation_id=? AND status='PENDING'",id.toString()));return result;}
    private int safeCount(String sql,Object...args){try{return jdbc.queryForObject(sql,Integer.class,args);}catch(org.springframework.dao.DataAccessException unavailable){return 0;}}
    private Object unreadCount(UUID id){String cursor=Objects.toString(single("SELECT last_read_cursor FROM simulation_conversation_state WHERE conversation_id=?",id.toString()),"");if(cursor.isBlank())return jdbc.queryForObject("SELECT COUNT(*) FROM messages WHERE conversation_id=? AND is_self=0",Integer.class,id.toString());if(!cursor.matches("[0-9]+"))return null;return jdbc.queryForObject("SELECT COUNT(*) FROM messages WHERE conversation_id=? AND is_self=0 AND platform_message_id NOT GLOB '*[^0-9]*' AND CAST(platform_message_id AS INTEGER)>CAST(? AS INTEGER)",Integer.class,id.toString(),cursor);}
    private Map<String,Object> safeMessage(java.sql.ResultSet rs)throws java.sql.SQLException{String text=rs.getString("text");String sanitized=text==null?"":text.replaceAll("[\\p{Cntrl}&&[^\\r\\n\\t]]"," ").replaceAll("\\s+"," ").strip();if(sanitized.length()>400)sanitized=sanitized.substring(0,400)+"…";String metadata=rs.getString("raw_metadata_json");Set<String> kinds=safeContentKinds(metadata);String type=rs.getString("message_type");if(!kinds.isEmpty())type=String.join(",",kinds);else if(sanitized.isBlank()&&"message".equals(type))type="non-text";Map<String,Object> row=new LinkedHashMap<>();row.put("messageId",shortId(rs.getString("platform_message_id")));row.put("sender",rs.getString("sender"));row.put("senderId",rs.getString("platform_user_id"));row.put("time",rs.getString("created_at"));row.put("type",safeType(type));row.put("preview",sanitized);row.put("replyTo",shortId(Objects.toString(rs.getString("reply_to_message_id"),"")));row.put("self",rs.getInt("is_self")!=0);row.put("contentKinds",kinds);return row;}
    private Set<String> safeContentKinds(String metadata){if(metadata==null||metadata.isBlank())return Set.of();try{JsonNode segments=mapper.readTree(metadata).path("segments");Set<String> types=new TreeSet<>();if(segments.isArray())for(JsonNode segment:segments){String type=segment.path("type").asText("");if(Set.of("image","file","record","video","forward","at","reply","poke","text").contains(type))types.add(type);}return Set.copyOf(types);}catch(Exception ignored){return Set.of();}}
    private String safeType(String value){String type=value==null?"message":value.replaceAll("[^A-Za-z0-9_,:-]","");return type.length()>80?type.substring(0,80):type;}
    private String shortId(String value){if(value==null||value.isBlank())return "";return value.length()>12?value.substring(0,8)+"…":value;}
    private String safeSummary(String value){if(value==null)return "";String safe=value.replaceAll("[^A-Za-z0-9_./ -]","");return safe.substring(0,Math.min(120,safe.length()));}
}
