package online.wanan.xingchen.console;

import online.wanan.xingchen.core.identity.*;
import online.wanan.xingchen.core.memory.*;
import online.wanan.xingchen.core.model.*;
import online.wanan.xingchen.core.relationship.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.*;

/** Bounded administrative read/write facade. Memory bodies are never copied into audit records. */
@Service
public class PeopleMemoryConsoleService {
    private static final int MAX_SIZE=100, MAX_PAGE=10000;
    private final JdbcTemplate jdbc; private final NamedParameterJdbcTemplate named;
    private final IdentityPersistence identities; private final RelationshipTermRegistry terms;
    private final MemoryRepository memories; private final MemoryRetriever retriever;
    private final AddressResolver addressResolver; private final MemoryPolicy memoryPolicy;

    public PeopleMemoryConsoleService(JdbcTemplate jdbc, NamedParameterJdbcTemplate named, IdentityPersistence identities,
            RelationshipTermRegistry terms, MemoryRepository memories, MemoryRetriever retriever, AddressResolver addressResolver,MemoryPolicy memoryPolicy) {
        this.jdbc=jdbc; this.named=named; this.identities=identities; this.terms=terms; this.memories=memories; this.retriever=retriever; this.addressResolver=addressResolver;this.memoryPolicy=memoryPolicy;
    }

    public Map<String,Object> people(String q,int page,int size) {
        page(page,size); String query=q==null?"":q.strip(); if(query.length()>100)throw new IllegalArgumentException("搜索内容过长");
        String where=" WHERE (:q='' OR lower(p.platform_user_id) LIKE lower(:like) OR EXISTS(SELECT 1 FROM person_aliases a WHERE a.person_id=p.id AND lower(a.alias) LIKE lower(:like)) OR EXISTS(SELECT 1 FROM memberships m WHERE m.person_id=p.id AND (lower(COALESCE(m.card,'')) LIKE lower(:like) OR lower(COALESCE(m.current_display_name,'')) LIKE lower(:like))))";
        var args=new MapSqlParameterSource().addValue("q",query).addValue("like","%"+query+"%").addValue("limit",size).addValue("offset",page*size);
        long total=named.queryForObject("SELECT COUNT(*) FROM persons p"+where,args,Long.class);
        var rows=named.query("SELECT p.id,p.platform,p.platform_user_id,p.is_self,p.is_owner,p.created_at, (SELECT COALESCE(NULLIF(m.card,''),NULLIF(m.current_display_name,'')) FROM memberships m WHERE m.person_id=p.id ORDER BY m.last_seen_at DESC LIMIT 1) display_name,(SELECT COUNT(*) FROM person_aliases a WHERE a.person_id=p.id) alias_count,(SELECT COUNT(*) FROM memberships m WHERE m.person_id=p.id) membership_count,(SELECT COUNT(*) FROM relationship_terms r WHERE r.target_person_id=p.id AND r.active=1) relationship_count,(SELECT COUNT(*) FROM memories mm WHERE mm.subject_person_id=p.id AND mm.status='ACTIVE') memory_count,(SELECT MAX(m.last_seen_at) FROM memberships m WHERE m.person_id=p.id) last_seen FROM persons p"+where+" ORDER BY last_seen DESC,p.id LIMIT :limit OFFSET :offset",args,(r,n)->map(r));
        return Map.of("items",rows,"page",page,"size",size,"total",total,"identityEditable",false);
    }
    public Map<String,Object> person(UUID id) {
        var p=jdbc.query("SELECT * FROM persons WHERE id=?",(r,n)->Map.<String,Object>of("id",r.getString("id"),"platform",r.getString("platform"),"platformUserId",r.getString("platform_user_id"),"self",r.getInt("is_self")!=0,"owner",r.getInt("is_owner")!=0,"createdAt",r.getString("created_at")),id.toString()).stream().findFirst().orElseThrow(()->new NoSuchElementException("person not found"));
        var aliases=jdbc.query("SELECT a.id,a.alias,a.source_conversation_id,a.first_seen_at,a.last_seen_at,c.type,c.platform_conversation_id FROM person_aliases a LEFT JOIN conversations c ON c.id=a.source_conversation_id WHERE a.person_id=? ORDER BY a.last_seen_at DESC",(r,n)->Map.of("id",r.getString("id"),"alias",r.getString("alias"),"sourceConversationId",Objects.toString(r.getString("source_conversation_id"),""),"conversationType",Objects.toString(r.getString("type"),""),"platformConversationId",Objects.toString(r.getString("platform_conversation_id"),""),"firstSeenAt",r.getString("first_seen_at"),"lastSeenAt",r.getString("last_seen_at")),id.toString());
        var membership=jdbc.query("SELECT m.*,c.type,c.platform,c.platform_conversation_id FROM memberships m JOIN conversations c ON c.id=m.conversation_id WHERE m.person_id=? ORDER BY m.last_seen_at DESC",(r,n)->Map.of("id",r.getString("id"),"conversationId",r.getString("conversation_id"),"conversationType",r.getString("type"),"platform",r.getString("platform"),"platformConversationId",r.getString("platform_conversation_id"),"displayName",Objects.toString(r.getString("current_display_name"),""),"card",Objects.toString(r.getString("card"),""),"role",r.getString("platform_role"),"firstSeenAt",r.getString("first_seen_at"),"lastSeenAt",r.getString("last_seen_at")),id.toString());
        var rel=relationshipRows(id,null); var summary=jdbc.query("SELECT type,scope_type,COUNT(*) count FROM memories WHERE subject_person_id=? AND status='ACTIVE' GROUP BY type,scope_type",(r,n)->Map.of("type",r.getString(1),"scope",r.getString(2),"count",r.getInt(3)),id.toString());
        return Map.of("person",p,"aliases",aliases,"memberships",membership,"relationships",rel,"memorySummary",summary);
    }
    public Map<String,Object> relationships(UUID personId,int page,int size) { page(page,size);var rows=relationshipRows(personId,null);int from=Math.min(page*size,rows.size()),to=Math.min(from+size,rows.size());return Map.of("items",rows.subList(from,to),"page",page,"size",size,"total",rows.size(),"scopes",Arrays.stream(ScopeType.values()).map(Enum::name).toList()); }
    private List<Map<String,Object>> relationshipRows(UUID personId,String ignored){return jdbc.query("SELECT r.*,sp.platform_user_id subject_id,tp.platform_user_id target_id,(SELECT c.id FROM conversations c WHERE c.platform_conversation_id=r.scope_id LIMIT 1) conversation_id FROM relationship_terms r JOIN persons sp ON sp.id=r.subject_person_id JOIN persons tp ON tp.id=r.target_person_id WHERE r.active=1 AND (? IS NULL OR r.subject_person_id=? OR r.target_person_id=?) ORDER BY r.updated_at DESC",(r,n)->Map.ofEntries(Map.entry("id",r.getString("id")),Map.entry("subjectPersonId",r.getString("subject_person_id")),Map.entry("subjectPlatformUserId",r.getString("subject_id")),Map.entry("targetPersonId",r.getString("target_person_id")),Map.entry("targetPlatformUserId",r.getString("target_id")),Map.entry("type",r.getString("type")),Map.entry("term",r.getString("value")),Map.entry("scope",r.getString("scope_type")),Map.entry("scopeId",Objects.toString(r.getString("scope_id"),"")),Map.entry("conversationId",Objects.toString(r.getString("conversation_id"),"")),Map.entry("explicit",r.getInt("explicit")!=0),Map.entry("source",relationshipSource(r)),Map.entry("priorityClass",relationshipPriorityClass(r)),Map.entry("createdAt",r.getString("created_at")),Map.entry("updatedAt",r.getString("updated_at")),Map.entry("active",r.getInt("active")!=0)),personId==null?null:personId.toString(),personId==null?null:personId.toString(),personId==null?null:personId.toString());}
    private static String relationshipSource(java.sql.ResultSet r)throws java.sql.SQLException{if(r.getInt("explicit")==0)return "INFERRED";if(r.getString("source_message_id")!=null)return "CONVERSATION_EXPLICIT";return "MANUAL_EXPLICIT";}
    private static String relationshipPriorityClass(java.sql.ResultSet r)throws java.sql.SQLException{boolean global="GLOBAL".equals(r.getString("scope_type"));if(r.getInt("explicit")==0)return global?"GLOBAL_INFERRED":"CONVERSATION_INFERRED";return global?"GLOBAL_EXPLICIT":"CONVERSATION_EXPLICIT";}
    @Transactional public Map<String,Object> saveRelationship(UUID id,RelationshipInput in,String actor) {
        UUID subject=uuid(in.subjectPersonId()), target=uuid(in.targetPersonId());
        if(!in.explicit())throw new IllegalArgumentException("只能编辑显式关系；推断关系只读");
        if(in.term()==null||in.term().isBlank()||in.term().length()>80)throw new IllegalArgumentException("称呼长度无效");
        ScopeType scope=parse(ScopeType.class,in.scope());String scopeId=blankNull(in.scopeId());
        if(scope==ScopeType.GLOBAL&&scopeId!=null)throw new IllegalArgumentException("GLOBAL 关系不能绑定局部范围");
        if(scope!=ScopeType.GLOBAL){String conversationRef=scopeId;scopeId=jdbc.query("SELECT platform_conversation_id FROM conversations WHERE id=?",(r,n)->r.getString(1),conversationRef).stream().findFirst().orElseThrow(()->new IllegalArgumentException("请选择有效会话范围"));}
        if(jdbc.queryForObject("SELECT COUNT(*) FROM persons WHERE id IN (?,?)",Integer.class,subject.toString(),target.toString())<2)throw new IllegalArgumentException("人物不存在");
        Instant now=Instant.now();String old=null;
        if(id!=null){var current=jdbc.query("SELECT value,updated_at,explicit,subject_person_id,target_person_id FROM relationship_terms WHERE id=? AND active=1",(r,n)->new String[]{r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5)},id.toString()).stream().findFirst().orElseThrow(()->new NoSuchElementException("relationship not found"));if(!"1".equals(current[2]))throw new SecurityException("推断关系不可编辑");if(!Objects.equals(current[1],in.expectedUpdatedAt()))throw new ConcurrentModificationException();if(!current[3].equals(subject.toString())||!current[4].equals(target.toString()))throw new IllegalArgumentException("关系双方身份不可更改");int duplicate=jdbc.queryForObject("SELECT COUNT(*) FROM relationship_terms WHERE id<>? AND subject_person_id=? AND target_person_id=? AND type='ADDRESS_AS' AND scope_type=? AND scope_id IS ? AND active=1",Integer.class,id.toString(),subject.toString(),target.toString(),scope.name(),scopeId);if(duplicate>0)throw new IllegalStateException("该范围已有称呼，请编辑现有记录");old=current[0];var updated=new RelationshipTerm(id,subject,target,RelationshipType.ADDRESS_AS,in.term().strip(),scope,scopeId,true,1.0,null,now,now);if(!terms.updateExplicit(updated,in.expectedUpdatedAt()))throw new ConcurrentModificationException();}
        else {int duplicate=jdbc.queryForObject("SELECT COUNT(*) FROM relationship_terms WHERE subject_person_id=? AND target_person_id=? AND type='ADDRESS_AS' AND scope_type=? AND scope_id IS ? AND active=1",Integer.class,subject.toString(),target.toString(),scope.name(),scopeId);if(duplicate>0)throw new IllegalStateException("该范围已有称呼，请编辑现有记录");id=UUID.randomUUID();terms.save(new RelationshipTerm(id,subject,target,RelationshipType.ADDRESS_AS,in.term().strip(),scope,scopeId,true,1.0,null,now,now));}
        jdbc.update("INSERT INTO relationship_console_audit(occurred_at,actor,person_id,scope_type,scope_id,operation,old_term,new_term,result) VALUES(?,?,?,?,?,?,?,?, 'SUCCESS')",now.toString(),actor,target.toString(),scope.name(),scopeId,in.operation()==null?"SAVE":in.operation(),old,in.term().strip());
        return Map.of("id",id.toString(),"updatedAt",now.toString());
    }
    @Transactional public void forgetRelationship(UUID id,String expected,String actor){var row=jdbc.query("SELECT target_person_id,scope_type,scope_id,value,explicit,updated_at FROM relationship_terms WHERE id=? AND active=1",(r,n)->new Object[]{r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getInt(5),r.getString(6)},id.toString()).stream().findFirst().orElseThrow(()->new NoSuchElementException("relationship not found"));if((int)row[4]!=1)throw new SecurityException("推断关系不可停用");if(!Objects.equals(row[5],expected)||!terms.deactivateExplicit(id,expected))throw new ConcurrentModificationException();Instant now=Instant.now();jdbc.update("INSERT INTO relationship_console_audit(occurred_at,actor,person_id,scope_type,scope_id,operation,old_term,new_term,result) VALUES(?,?,?,?,?,'FORGET',?,NULL,'SUCCESS')",now.toString(),actor,row[0],row[1],row[2],row[3]);}

    public Map<String,Object> memoryList(String q,String person,String conversation,String project,String type,String scope,String status,String from,String to,int page,int size){page(page,size);String query=blankNull(q);if(query!=null&&query.length()>100)throw new IllegalArgumentException("搜索内容过长");String normalizedStatus=status==null?"ACTIVE":status.toUpperCase(Locale.ROOT);if(!Set.of("ACTIVE","SOFT_DELETED").contains(normalizedStatus))throw new IllegalArgumentException("状态筛选值无效");Instant createdFrom=parseTimestamp(from,"from"),createdTo=parseTimestamp(to,"to");if(createdFrom!=null&&createdTo!=null&&createdFrom.isAfter(createdTo))throw new IllegalArgumentException("from 不能晚于 to；时间范围采用左闭右开 [from,to)");List<Object> args=new ArrayList<>();StringBuilder where=new StringBuilder(" WHERE 1=1");filter(where,args,"m.subject_person_id",person);filter(where,args,"m.conversation_id",conversation);filter(where,args,"m.project_key",project);filter(where,args,"m.type",enumValue(MemoryType.class,type));filter(where,args,"m.scope_type",enumValue(MemoryScope.class,scope));filter(where,args,"m.status",normalizedStatus);if(createdFrom!=null){where.append(" AND julianday(m.created_at)>=julianday(?)");args.add(createdFrom.toString());}if(createdTo!=null){where.append(" AND julianday(m.created_at)<julianday(?)");args.add(createdTo.toString());}
        if(query!=null){where.append(" AND m.id IN (SELECT f.memory_id FROM memories_fts f WHERE memories_fts MATCH ?)");args.add(query);}
        try {long count=jdbc.queryForObject("SELECT COUNT(*) FROM memories m"+where,args.toArray(),Long.class);var pageArgs=new ArrayList<>(args);pageArgs.add(size);pageArgs.add(page*size);
        var rows=jdbc.query("SELECT m.*,p.platform_user_id,COALESCE((SELECT actor FROM memory_admin_provenance ap WHERE ap.memory_id=m.id),(SELECT ms.platform||':'||ms.message_id FROM memory_sources ms WHERE ms.memory_id=m.id LIMIT 1),'UNKNOWN') provenance FROM memories m LEFT JOIN persons p ON p.id=m.subject_person_id"+where+" ORDER BY m.updated_at DESC LIMIT ? OFFSET ?",pageArgs.toArray(),(r,n)->memoryMap(r,false));return Map.of("items",rows,"page",page,"size",size,"total",count,"types",Arrays.stream(MemoryType.values()).map(Enum::name).toList(),"scopes",Arrays.stream(MemoryScope.values()).map(Enum::name).toList());} catch(org.springframework.dao.DataAccessException failure){if(query!=null)throw new IllegalArgumentException("全文搜索语法无效");throw failure;}}
    public Map<String,Object> memory(UUID id){var m=jdbc.query("SELECT m.*,p.platform_user_id,COALESCE((SELECT actor FROM memory_admin_provenance ap WHERE ap.memory_id=m.id),(SELECT ms.platform||':'||ms.message_id FROM memory_sources ms WHERE ms.memory_id=m.id LIMIT 1),'UNKNOWN') provenance FROM memories m LEFT JOIN persons p ON p.id=m.subject_person_id WHERE m.id=?",(r,n)->memoryMap(r,true),id.toString()).stream().findFirst().orElseThrow(()->new NoSuchElementException("memory not found"));var sources=jdbc.query("SELECT platform,conversation_id,message_id,actor_person_id,timestamp FROM memory_sources WHERE memory_id=?",(r,n)->Map.of("platform",r.getString(1),"conversationId",Objects.toString(r.getString(2),""),"messageId",r.getString(3),"actorPersonId",r.getString(4),"timestamp",r.getString(5)),id.toString());return Map.of("memory",m,"sources",sources);}
    @Transactional public Map<String,Object> saveMemory(UUID id,MemoryInput in,String actor){MemoryType type=parse(MemoryType.class,in.type());MemoryScope scope=parse(MemoryScope.class,in.scope());String content=in.content()==null?"":in.content().strip();if(content.isBlank()||content.length()>20000)throw new IllegalArgumentException("记忆正文长度无效");UUID person=uuid(in.personId()),conversation=uuid(in.conversationId());String project=blankNull(in.projectKey());validateScope(scope,person,conversation,project);if(person!=null&&jdbc.queryForObject("SELECT COUNT(*) FROM persons WHERE id=?",Integer.class,person.toString())!=1)throw new IllegalArgumentException("人物不存在");if(conversation!=null&&jdbc.queryForObject("SELECT COUNT(*) FROM conversations WHERE id=?",Integer.class,conversation.toString())!=1)throw new IllegalArgumentException("会话不存在");if(scope==MemoryScope.OWNER_GLOBAL&&jdbc.queryForObject("SELECT is_owner FROM persons WHERE id=?",Integer.class,person.toString())!=1)throw new IllegalArgumentException("OWNER_GLOBAL 必须绑定 owner 人物");Instant now=Instant.now();String oldScope=null;String created;
        if(id==null){id=UUID.randomUUID();var candidate=new Memory(id,type,person,conversation,project,content,scope,scopeId(scope,person,conversation,project),1.0,0.8,true,now,now,null,null,MemoryStatus.ACTIVE);memoryPolicy.validateAdministrative(candidate,null,false);created=now.toString();jdbc.update("INSERT INTO memories(id,type,subject_person_id,conversation_id,project_key,content,scope_type,scope_id,confidence,importance,explicit,created_at,updated_at,status) VALUES(?,?,?,?,?,?,?,?,1.0,0.8,1,?,?, 'ACTIVE')",id.toString(),type.name(),str(person),str(conversation),project,content,scope.name(),scopeId(scope,person,conversation,project),created,created);jdbc.update("INSERT INTO memory_admin_provenance(memory_id,actor,created_at) VALUES(?,?,?)",id.toString(),actor,created);}
        else {var current=jdbc.query("SELECT type,scope_type,updated_at,status FROM memories WHERE id=? AND EXISTS(SELECT 1 FROM memory_admin_provenance ap WHERE ap.memory_id=memories.id)",(r,n)->new String[]{r.getString(1),r.getString(2),r.getString(3),r.getString(4)},id.toString()).stream().findFirst().orElseThrow(()->new SecurityException("仅可编辑管理员创建的记忆"));if(!Objects.equals(current[2],in.expectedUpdatedAt()))throw new ConcurrentModificationException();if(!"ACTIVE".equals(current[3]))throw new IllegalStateException("已停用的记忆不可编辑");oldScope=current[1];Memory candidate=new Memory(id,type,person,conversation,project,content,scope,scopeId(scope,person,conversation,project),1.0,0.8,true,now,now,null,null,MemoryStatus.ACTIVE);memoryPolicy.validateAdministrative(candidate,memories.get(id).orElseThrow(),in.confirmScopeExpansion());int changed=jdbc.update("UPDATE memories SET type=?,content=?,scope_type=?,scope_id=?,subject_person_id=?,conversation_id=?,project_key=?,updated_at=? WHERE id=? AND updated_at=? AND status='ACTIVE'",type.name(),content,scope.name(),scopeId(scope,person,conversation,project),str(person),str(conversation),project,now.toString(),id.toString(),in.expectedUpdatedAt());if(changed!=1)throw new ConcurrentModificationException();created=now.toString();}
        jdbc.update("INSERT INTO memory_console_audit(occurred_at,actor,memory_id,operation,type,old_scope,new_scope,result) VALUES(?,?,?,?,?,?,?,'SUCCESS')",now.toString(),actor,id.toString(),in.operation()==null?"SAVE":in.operation(),type.name(),oldScope,scope.name());return Map.of("id",id.toString(),"updatedAt",created,"provenance","ADMIN_MANUAL");}
    @Transactional public void forgetMemory(UUID id,String expected,String actor){var row=jdbc.query("SELECT type,scope_type,updated_at FROM memories WHERE id=? AND status='ACTIVE'",(r,n)->new String[]{r.getString(1),r.getString(2),r.getString(3)},id.toString()).stream().findFirst().orElseThrow(()->new NoSuchElementException("memory not found"));if(!Objects.equals(row[2],expected))throw new ConcurrentModificationException();Instant now=Instant.now();if(jdbc.update("UPDATE memories SET status='SOFT_DELETED',updated_at=? WHERE id=? AND updated_at=? AND status='ACTIVE'",now.toString(),id.toString(),expected)!=1)throw new ConcurrentModificationException();jdbc.update("INSERT INTO memory_console_audit(occurred_at,actor,memory_id,operation,type,old_scope,new_scope,result) VALUES(?,?,?,'FORGET',?,?,?,'SUCCESS')",now.toString(),actor,id.toString(),row[0],row[1],row[1]);}
    public Map<String,Object> preview(String personId,String conversationId,String projectKey){UUID person=uuid(personId),conversation=uuid(conversationId);if(person==null||conversation==null)throw new IllegalArgumentException("请选择人物和会话");var personRow=identities.findPerson(person).orElseThrow(()->new IllegalArgumentException("人物不存在"));var conv=jdbc.query("SELECT platform,type,platform_conversation_id FROM conversations WHERE id=?",(r,n)->new ConversationIdentity(Platform.valueOf(r.getString(1)),ConversationType.valueOf(r.getString(2)),r.getString(3)),conversation.toString()).stream().findFirst().orElseThrow(()->new IllegalArgumentException("会话不存在"));boolean member=identities.findMembership(person,conversation).isPresent();var request=new RequestContext(person,conversation,personRow.owner(),projectKey);var result=retriever.retrieve(request,"",conversation,person,12000);return Map.of("items",result.memories().stream().map(m->Map.of("id",m.id().toString(),"type",m.type().name(),"scope",m.scopeType().name(),"matched",true,"reason",previewReason(m,person,conversation,projectKey))).toList(),"excludedCount",result.excludedCount(),"contextMember",member,"modelInvoked",false);}

    public Map<String,Object> relationshipPreview(String subjectId,String targetId,String conversationId){
        UUID subject=uuid(subjectId),target=uuid(targetId),conversation=uuid(conversationId);
        if(subject==null||target==null||conversation==null)throw new IllegalArgumentException("请选择关系双方和会话");
        String platformConversation=jdbc.query("SELECT platform_conversation_id FROM conversations WHERE id=?",(r,n)->r.getString(1),conversation.toString()).stream().findFirst().orElseThrow(()->new IllegalArgumentException("会话不存在"));
        var candidates=terms.all().stream().filter(t->t.subjectPersonId().equals(subject)&&t.targetPersonId().equals(target)&&t.type()==RelationshipType.ADDRESS_AS).toList();
        var resolved=addressResolver.resolveAddress(subject,target,platformConversation,"",candidates);
        var ordered=candidates.stream().filter(t->t.scopeType()==ScopeType.GLOBAL||Objects.equals(t.scopeId(),platformConversation)).sorted(Comparator.comparingInt((RelationshipTerm t)->AddressResolver.priority(t,platformConversation)).thenComparing(RelationshipTerm::updatedAt,Comparator.nullsLast(Comparator.reverseOrder()))).map(t->Map.<String,Object>of("id",t.id().toString(),"term",t.value(),"scope",t.scopeType().name(),"explicit",t.explicit(),"source",t.explicit()?(t.sourceMessageId()==null?"MANUAL_EXPLICIT":"CONVERSATION_EXPLICIT"):"INFERRED","priorityClass",t.explicit()?(t.scopeType()==ScopeType.GLOBAL?"GLOBAL_EXPLICIT":"CONVERSATION_EXPLICIT"):(t.scopeType()==ScopeType.GLOBAL?"GLOBAL_INFERRED":"CONVERSATION_INFERRED"),"priority",AddressResolver.priority(t,platformConversation),"effective",t.value().equals(resolved.address())&&Objects.equals(t.scopeType(),resolved.scope())&&t.explicit()==resolved.explicit())).toList();
        String reason=resolved.scope()==null?"DISPLAY_NAME_FALLBACK":resolved.explicit()?(resolved.scope()==ScopeType.GLOBAL?"GLOBAL_EXPLICIT":"CONVERSATION_EXPLICIT"):resolved.scope()==ScopeType.GLOBAL?"GLOBAL_INFERRED":"CONVERSATION_INFERRED";
        return Map.of("address",resolved.address(),"scope",resolved.scope()==null?"":resolved.scope().name(),"explicit",resolved.explicit(),"reason",reason,"candidates",ordered,"conversationId",conversation.toString());
    }

    private static String previewReason(Memory m,UUID person,UUID conversation,String project){return switch(m.scopeType()){case PERSON_GLOBAL->"PERSON_GLOBAL same person";case PRIVATE->Objects.equals(m.subjectPersonId(),person)?"PRIVATE same person":"PRIVATE different actor";case CONVERSATION->Objects.equals(m.conversationId(),conversation)?"CONVERSATION same conversation":"CONVERSATION different conversation";case PROJECT->Objects.equals(m.projectKey(),project)?"PROJECT same project":"PROJECT different project";case OWNER_GLOBAL->"OWNER_GLOBAL owner policy";case GLOBAL->"GLOBAL policy";};}
    private static void validateScope(MemoryScope s,UUID p,UUID c,String project){if(s==MemoryScope.PERSON_GLOBAL&&p==null)throw new IllegalArgumentException("PERSON_GLOBAL 必须绑定人物");if((s==MemoryScope.PRIVATE||s==MemoryScope.OWNER_GLOBAL)&&p==null)throw new IllegalArgumentException("此记忆范围必须绑定人物");if(s==MemoryScope.CONVERSATION&&c==null)throw new IllegalArgumentException("CONVERSATION 必须绑定会话");if(s==MemoryScope.PROJECT&&(project==null||project.length()>120))throw new IllegalArgumentException("PROJECT 必须绑定项目");}
    private static String scopeId(MemoryScope s,UUID p,UUID c,String project){return switch(s){case PERSON_GLOBAL,PRIVATE,OWNER_GLOBAL->str(p);case CONVERSATION->str(c);case PROJECT->project;case GLOBAL->null;};}
    private static boolean expands(String old,MemoryScope next){return !"GLOBAL".equals(old)&&next==MemoryScope.GLOBAL;}
    private static void filter(StringBuilder w,List<Object>a,String column,String value){if(value!=null&&!value.isBlank()){w.append(" AND ").append(column).append("=?");a.add(value);}}
    private static void page(int p,int s){if(p<0||p>MAX_PAGE||s<1||s>MAX_SIZE)throw new IllegalArgumentException("分页参数超出允许范围");}
    private static Map<String,Object> map(java.sql.ResultSet r)throws java.sql.SQLException{return Map.ofEntries(Map.entry("id",r.getString("id")),Map.entry("platform",r.getString("platform")),Map.entry("platformUserId",r.getString("platform_user_id")),Map.entry("self",r.getInt("is_self")!=0),Map.entry("owner",r.getInt("is_owner")!=0),Map.entry("createdAt",r.getString("created_at")),Map.entry("displayName",Objects.toString(r.getString("display_name"),"")),Map.entry("aliasCount",r.getInt("alias_count")),Map.entry("membershipCount",r.getInt("membership_count")),Map.entry("relationshipCount",r.getInt("relationship_count")),Map.entry("memoryCount",r.getInt("memory_count")),Map.entry("lastSeen",Objects.toString(r.getString("last_seen"),"")));}
    private static Map<String,Object> memoryMap(java.sql.ResultSet r,boolean detail)throws java.sql.SQLException{Map<String,Object> m=new LinkedHashMap<>();m.put("id",r.getString("id"));m.put("type",r.getString("type"));m.put("scope",r.getString("scope_type"));m.put("personId",Objects.toString(r.getString("subject_person_id"),""));m.put("personPlatformUserId",Objects.toString(r.getString("platform_user_id"),""));m.put("conversationId",Objects.toString(r.getString("conversation_id"),""));m.put("projectKey",Objects.toString(r.getString("project_key"),""));m.put("content",detail?r.getString("content"):r.getString("content").substring(0,Math.min(180,r.getString("content").length())));m.put("createdAt",r.getString("created_at"));m.put("updatedAt",r.getString("updated_at"));m.put("status",r.getString("status"));m.put("provenance",r.getString("provenance"));return m;}
    @SuppressWarnings({"rawtypes","unchecked"}) private static String enumValue(Class c,String v){if(v==null||v.isBlank())return null;try{return Enum.valueOf(c,v.toUpperCase(Locale.ROOT)).name();}catch(Exception e){throw new IllegalArgumentException("筛选值无效");}}
    private static <E extends Enum<E>> E parse(Class<E> c,String v){try{return Enum.valueOf(c,v.toUpperCase(Locale.ROOT));}catch(Exception e){throw new IllegalArgumentException("筛选值无效");}}
    private static UUID uuid(String v){try{return v==null||v.isBlank()?null:UUID.fromString(v);}catch(Exception e){throw new IllegalArgumentException("标识格式无效");}}
    private static String str(UUID v){return v==null?null:v.toString();}private static String blankNull(String v){return v==null||v.isBlank()?null:v.strip();}
    private static Instant parseTimestamp(String value,String name){if(value==null||value.isBlank())return null;try{return Instant.parse(value);}catch(Exception e){throw new IllegalArgumentException(name+" 必须是带时区的 ISO-8601 时间戳");}}
    public record RelationshipInput(String subjectPersonId,String targetPersonId,String term,String scope,String scopeId,boolean explicit,String expectedUpdatedAt,String operation){}
    public record MemoryInput(String content,String type,String scope,String personId,String conversationId,String projectKey,String expectedUpdatedAt,boolean confirmScopeExpansion,String operation){}
}
