package online.wanan.xingchen.console;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import online.wanan.xingchen.core.agent.SocialSettingsSnapshot;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.*;

/** Validated persistent social-policy facade; runtime and Console share this source of truth. */
@Service
public class SocialSettingsService {
    private static final Map<String,Object> DEFAULTS=defaults();
    private static final Set<String> KEYS=DEFAULTS.keySet();
    private final JdbcTemplate jdbc; private final ObjectMapper json;
    public SocialSettingsService(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}

    public Map<String,Object> global(){var row=jdbc.query("SELECT revision,values_json FROM social_settings_global WHERE singleton_id=1",rs->rs.next()?new Object[]{rs.getLong(1),parse(rs.getString(2))}:null);long revision=row==null?0:(long)row[0];Map<String,Object> values=row==null?DEFAULTS:merge(DEFAULTS,cast(row[1]));return Map.of("scope","GLOBAL","revision",revision,"values",values,"applyMode","HOT_APPLY");}

    @Transactional public Map<String,Object> updateGlobal(long expectedRevision,Map<String,Object> changes,String actor){Map<String,Object> before=global();long revision=((Number)before.get("revision")).longValue();if(revision!=expectedRevision)throw new ConcurrentModificationException("social settings changed");Map<String,Object> next=merge(cast(before.get("values")),validate(changes));persistGlobal(next,revision+1,revision,actor);audit("GLOBAL",null,cast(before.get("values")),next,actor);return global();}

    public Map<String,Object> conversation(UUID id){requireConversation(id);Map<String,Object> global=global();OverrideRow row=override(id);Map<String,Object> values=row==null?Map.of():row.values;Map<String,Object> effective=merge(cast(global.get("values")),values);return Map.of("scope","CONVERSATION","conversationId",id.toString(),"globalRevision",global.get("revision"),"overrideRevision",row==null?0:row.revision,"global",global.get("values"),"overrides",values,"effective",effective,"applyMode","HOT_APPLY");}

    @Transactional public Map<String,Object> updateConversation(UUID id,long expectedRevision,Map<String,Object> changes,String actor){requireConversation(id);OverrideRow old=override(id);long revision=old==null?0:old.revision;if(revision!=expectedRevision)throw new ConcurrentModificationException("conversation settings changed");Map<String,Object> oldValues=old==null?Map.of():old.values;if(changes==null||changes.isEmpty()||!KEYS.containsAll(changes.keySet()))throw new IllegalArgumentException("conversation settings are invalid");Map<String,Object> nonNull=new LinkedHashMap<>();Set<String> cleared=new HashSet<>();changes.forEach((k,v)->{if(v==null)cleared.add(k);else nonNull.put(k,v);});Map<String,Object> patch=nonNull.isEmpty()?Map.of():validate(nonNull);Map<String,Object> next=new LinkedHashMap<>(oldValues);cleared.forEach(next::remove);next.putAll(patch);next=Map.copyOf(next);String now=Instant.now().toString();String payload=encode(next);
        if(old==null){jdbc.update("INSERT INTO social_settings_override(conversation_id,revision,values_json,updated_at,updated_by) VALUES(?,1,?,?,?)",id.toString(),payload,now,actor);}
        else if(jdbc.update("UPDATE social_settings_override SET revision=revision+1,values_json=?,updated_at=?,updated_by=? WHERE conversation_id=? AND revision=?",payload,now,actor,id.toString(),revision)!=1)throw new ConcurrentModificationException("conversation settings changed");
        audit("CONVERSATION",id.toString(),oldValues,next,actor);return conversation(id);}

    @Transactional public Map<String,Object> clearConversation(UUID id,long expectedRevision,String actor){requireConversation(id);OverrideRow old=override(id);long revision=old==null?0:old.revision;if(revision!=expectedRevision)throw new ConcurrentModificationException("conversation settings changed");if(old!=null){Map<String,Object> cleared=Map.of();if(jdbc.update("UPDATE social_settings_override SET revision=revision+1,values_json=?,updated_at=?,updated_by=? WHERE conversation_id=? AND revision=?",encode(cleared),Instant.now().toString(),actor,id.toString(),revision)!=1)throw new ConcurrentModificationException("conversation settings changed");audit("CONVERSATION",id.toString(),old.values,cleared,actor);}return conversation(id);}

    /** Captured before wake evaluation and reused for participation and outbound limits through the same turn. */
    public SocialSettingsSnapshot capture(UUID id,Map<String,Object> legacyWake){Map<String,Object> view=conversation(id);Map<String,Object> e=cast(view.get("effective"));List<String> speakers=new ArrayList<>(strings(e.get("configuredSpeakerIds")));Object legacy=legacyWake==null?null:legacyWake.get("speakers");if(legacy instanceof Collection<?> c)for(Object v:c)if(v instanceof String s&&!s.isBlank())speakers.add("QQ:"+s.strip());
        return new SocialSettingsSnapshot(((Number)view.get("globalRevision")).longValue(),((Number)view.get("overrideRevision")).longValue(),bool(e,"mentionWake"),bool(e,"replyToBotWake"),bool(e,"pokeWake"),bool(e,"botNameWake"),strings(e.get("botNameAliases")),bool(e,"questionWake"),bool(e,"configuredSpeakerWake"),List.copyOf(new LinkedHashSet<>(speakers)),true,decimal(e,"ordinaryMessageProbability"),integer(e,"maxReplyMessages"),integer(e,"maxPerMinute"),integer(e,"gapMillis"));}

    private void persistGlobal(Map<String,Object> values,long next,long previous,String actor){String now=Instant.now().toString(),payload=encode(values);if(previous==0){var exists=jdbc.queryForObject("SELECT COUNT(*) FROM social_settings_global WHERE singleton_id=1",Integer.class);if(exists==0){jdbc.update("INSERT INTO social_settings_global(singleton_id,revision,values_json,updated_at,updated_by) VALUES(1,?,?,?,?)",next,payload,now,actor);return;}}
        if(jdbc.update("UPDATE social_settings_global SET revision=?,values_json=?,updated_at=?,updated_by=? WHERE singleton_id=1 AND revision=?",next,payload,now,actor,previous)!=1)throw new ConcurrentModificationException("social settings changed");}
    private OverrideRow override(UUID id){return jdbc.query("SELECT revision,values_json FROM social_settings_override WHERE conversation_id=?",rs->rs.next()?new OverrideRow(rs.getLong(1),cast(parse(rs.getString(2)))):null,id.toString());}
    private void requireConversation(UUID id){if(id==null||jdbc.queryForObject("SELECT COUNT(*) FROM conversations WHERE id=?",Integer.class,id.toString())==0)throw new NoSuchElementException("conversation not found");}
    private Map<String,Object> validate(Map<String,Object> changes){if(changes==null||changes.isEmpty()||!KEYS.containsAll(changes.keySet()))throw new IllegalArgumentException("social settings are invalid");Map<String,Object> result=new LinkedHashMap<>();for(var e:changes.entrySet()){String k=e.getKey();Object v=e.getValue();switch(k){case "mentionWake","replyToBotWake","pokeWake","botNameWake","questionWake","configuredSpeakerWake"->{if(!(v instanceof Boolean))throw new IllegalArgumentException(k+" must be boolean");result.put(k,v);}case "botNameAliases"->{List<String> items=boundedStrings(v,12,64,"botNameAliases");result.put(k,items.stream().map(s->s.toLowerCase(Locale.ROOT)).distinct().toList());}case "configuredSpeakerIds"->{List<String> items=boundedStrings(v,32,128,"configuredSpeakerIds");for(String item:items)if(!item.matches("(?i)QQ:[A-Za-z0-9_-]{1,80}"))throw new IllegalArgumentException("configured speakers must use stable QQ platform user IDs, not names");result.put(k,items.stream().map(s->"QQ:"+s.substring(s.indexOf(':')+1)).distinct().toList());}case "ordinaryMessageProbability"->{double n=asDouble(v,k);if(n<0||n>1)throw new IllegalArgumentException(k+" must be between 0 and 1");result.put(k,n);}case "maxReplyMessages"->{int n=asInt(v,k);if(n<1||n>8)throw new IllegalArgumentException(k+" must be 1..8 messages");result.put(k,n);}case "maxPerMinute"->{int n=asInt(v,k);if(n<1||n>60)throw new IllegalArgumentException(k+" must be 1..60 messages per minute");result.put(k,n);}case "gapMillis"->{int n=asInt(v,k);if(n<0||n>30_000)throw new IllegalArgumentException(k+" must be 0..30000 milliseconds");result.put(k,n);}default->throw new IllegalArgumentException("unsupported social setting");}}return Map.copyOf(result);}
    private List<String> boundedStrings(Object value,int maxCount,int maxLength,String key){if(!(value instanceof Collection<?> c)||c.size()>maxCount)throw new IllegalArgumentException(key+" exceeds its item limit");List<String> out=new ArrayList<>();for(Object item:c){if(!(item instanceof String s)||s.length()>maxLength)throw new IllegalArgumentException(key+" contains an invalid item");String n=s.strip();if(n.isEmpty())continue;out.add(n);}return List.copyOf(out);}
    private void audit(String scope,String conversation,Map<String,Object> oldValues,Map<String,Object> newValues,String actor){Set<String> keys=new TreeSet<>();keys.addAll(oldValues.keySet());keys.addAll(newValues.keySet());for(String key:keys)if(!Objects.equals(oldValues.get(key),newValues.get(key)))jdbc.update("INSERT INTO social_settings_audit(occurred_at,actor,scope,conversation_id,setting_key,old_value_json,new_value_json) VALUES(?,?,?,?,?,?,?)",Instant.now().toString(),actor,scope,conversation,key,oldValues.containsKey(key)?encode(oldValues.get(key)):null,newValues.containsKey(key)?encode(newValues.get(key)):null);}
    private boolean bool(Map<String,Object> m,String k){return Boolean.TRUE.equals(m.get(k));}private double decimal(Map<String,Object> m,String k){return ((Number)m.get(k)).doubleValue();}private int integer(Map<String,Object> m,String k){return ((Number)m.get(k)).intValue();}
    private List<String> strings(Object o){return o instanceof Collection<?> c?c.stream().filter(String.class::isInstance).map(String.class::cast).toList():List.of();}
    private static int asInt(Object v,String k){if(!(v instanceof Number n)||n.doubleValue()!=n.intValue())throw new IllegalArgumentException(k+" must be an integer");return n.intValue();}private static double asDouble(Object v,String k){if(!(v instanceof Number n)||!Double.isFinite(n.doubleValue()))throw new IllegalArgumentException(k+" must be a finite number");return n.doubleValue();}
    private String encode(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException("social settings could not be encoded");}}private Object parse(String s){try{return json.readValue(s,Object.class);}catch(Exception e){throw new IllegalStateException("stored social settings are invalid");}}
    @SuppressWarnings("unchecked") private static Map<String,Object> cast(Object o){return (Map<String,Object>)o;}
    private static Map<String,Object> merge(Map<String,Object> base,Map<String,Object> overlay){Map<String,Object> result=new LinkedHashMap<>(base);result.putAll(overlay);return Map.copyOf(result);}
    private static Map<String,Object> defaults(){Map<String,Object> m=new LinkedHashMap<>();m.put("mentionWake",true);m.put("replyToBotWake",true);m.put("pokeWake",true);m.put("botNameWake",true);m.put("botNameAliases",List.of());m.put("questionWake",true);m.put("configuredSpeakerWake",true);m.put("configuredSpeakerIds",List.of());m.put("ordinaryMessageProbability",0.0);m.put("maxReplyMessages",8);m.put("maxPerMinute",30);m.put("gapMillis",0);return Map.copyOf(m);}
    private record OverrideRow(long revision,Map<String,Object> values){}
}
