package online.wanan.xingchen.adapter.dsh;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.*;
import java.nio.file.Path;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;

class DshRc2AdapterContractTest {
    private FakeDshRc2Server server;private DshRc2Adapter adapter;private Path workspace;
    @BeforeEach void start() throws Exception {server=new FakeDshRc2Server("launch-secret");workspace=Path.of("build").toAbsolutePath();adapter=new DshRc2Adapter(config("launch-secret",Duration.ofSeconds(2)),new ObjectMapper());}
    @AfterEach void stop(){if(adapter!=null)adapter.close();if(server!=null)server.close();}
    private DshRc2Configuration config(String token,Duration timeout){return new DshRc2Configuration(server.baseUri(),workspace,token,"deepseek-official",timeout);}

    @Test void dsh001_launchTokenExchangeObtainsCookieForUnaryRpc(){assertThat(adapter.findOrCreateWorkspace(workspace.toString())).isEqualTo("workspace-fixture");assertThat(server.requests()).singleElement().satisfies(r->{assertThat(r.endpoint()).isEqualTo("workspace/create");assertThat(r.cookie()).isEqualTo("DSHSession=fake-cookie");});}
    @Test void dsh002_authFailureIsClassifiedAndSecretRedacted(){adapter.close();adapter=new DshRc2Adapter(config("wrong-launch-secret",Duration.ofSeconds(1)),new ObjectMapper());assertThatThrownBy(()->adapter.findOrCreateWorkspace(workspace.toString())).isInstanceOf(DshRc2Exception.class).hasMessage("DSH authentication exchange failed").hasMessageNotContaining("wrong-launch-secret").hasMessageNotContaining("fake-cookie").satisfies(e->assertThat(((DshRc2Exception)e).code()).isEqualTo("auth/rejected"));}
    @Test void dsh003_workspaceUsesExistingDirectoryAndExactRequestShape(){adapter.findOrCreateWorkspace(workspace.toString());var req=server.requests("workspace/create").getFirst().envelope();assertThat(req.path("type").asText()).isEqualTo("client-request");assertThat(req.path("method").asText()).isEqualTo("workspace/create");assertThat(req.path("payload").path("args").path("request").path("path").asText()).isEqualTo(workspace.toString());assertThatThrownBy(()->adapter.findOrCreateWorkspace(workspace.resolve("missing").toString())).isInstanceOf(IllegalArgumentException.class);}
    @Test void dsh004_sessionCreateSelectsPresetAtCreationAndModelSeparately(){assertThat(adapter.createSession("workspace-1","SOCIAL","qq-chat","deepseek-chat")).isEqualTo("session-fixture");var create=server.requests("session/create").getFirst().envelope().path("payload").path("args").path("request");assertThat(create.path("workspaceId").asText()).isEqualTo("workspace-1");assertThat(create.path("agentPreset").asText()).isEqualTo("qq-chat");assertThat(server.requests("session/selectModel")).hasSize(1);assertThat(server.requests("session/selectModel").getFirst().envelope().path("payload").path("args").path("request").path("provider").asText()).isEqualTo("deepseek-official");}
    @Test void dsh005_promptUsesRequiredRequestIdAndTextPart(){adapter.prompt("s-1","hello");var req=server.requests("session/prompt").getFirst().envelope().path("payload").path("args").path("request");assertThat(req.path("requestId").asText()).isNotBlank();assertThat(req.path("sessionId").asText()).isEqualTo("s-1");assertThat(req.path("mode").asText()).isEqualTo("queue");assertThat(req.path("content").get(0).path("text").asText()).isEqualTo("hello");}
    @Test void dsh006_followDecodesSnapshotThenDurableEventForBoundSession() throws Exception {var events=new CopyOnWriteArrayList<DshFollowEvent>();var latch=new CountDownLatch(2);var errors=new CopyOnWriteArrayList<Throwable>();var sub=adapter.follow("session-fixture",e->{events.add(e);latch.countDown();},errors::add);try{assertThat(latch.await(3,TimeUnit.SECONDS)).isTrue();assertThat(events).extracting(DshFollowEvent::kind).containsExactly(DshFollowEvent.Kind.SNAPSHOT,DshFollowEvent.Kind.DURABLE_EVENT);assertThat(events).allSatisfy(e->assertThat(e.sessionId()).isEqualTo("session-fixture"));assertThat(events.get(1).eventType()).isEqualTo("assistant/message");assertThat(errors).isEmpty();}finally{sub.close();}}
    @Test void dsh007_stopReadsBaselineRemovesQueuedWorkThenCancels(){server.queue("session-fixture","q1","q2");adapter.stop("session-fixture");assertThat(server.requests("session/control")).isEmpty();assertThat(server.requests("session/updateQueue")).hasSize(2);assertThat(server.requests("session/cancel")).hasSize(1);}
    @Test void dsh008_archiveUsesWorkspaceArchiveSessionEndpoint(){adapter.archive("s-archive");assertThat(server.requests("workspace/archiveSession")).singleElement().satisfies(r->assertThat(r.envelope().path("payload").path("args").path("request").path("sessionId").asText()).isEqualTo("s-archive"));}
    @Test void dsh009_selectModelUsesSessionSelectModelContract(){adapter.selectModel("s-model","model-x");assertThat(server.requests("session/selectModel")).singleElement().satisfies(r->{assertThat(r.endpoint()).isEqualTo("session/selectModel");assertThat(r.envelope().path("payload").path("args").path("request").path("model").asText()).isEqualTo("model-x");});}
    @Test void dsh010_timeoutIsBoundedAndSanitized(){server.timeoutNext("workspace/create",700);adapter.close();adapter=new DshRc2Adapter(config("launch-secret",Duration.ofMillis(100)),new ObjectMapper());assertThatThrownBy(()->adapter.findOrCreateWorkspace(workspace.toString())).isInstanceOf(DshRc2Exception.class).hasMessage("DSH request timed out").satisfies(e->assertThat(((DshRc2Exception)e).code()).isEqualTo("transport/timeout"));}
    @Test void dsh011_disconnectIsReportedWithoutLeakingCookie() throws Exception{server.muxMode=FakeDshRc2Server.MuxMode.DISCONNECT;var latch=new CountDownLatch(1);var errors=new CopyOnWriteArrayList<Throwable>();var sub=adapter.follow("session-fixture",e->{},e->{errors.add(e);latch.countDown();});try{assertThat(latch.await(3,TimeUnit.SECONDS)).isTrue();assertThat(errors.getFirst()).hasMessageNotContaining("fake-cookie");}finally{sub.close();}}
    @Test void dsh012_malformedMuxFrameFailsClosed() throws Exception{server.muxMode=FakeDshRc2Server.MuxMode.MALFORMED;var latch=new CountDownLatch(1);var errors=new CopyOnWriteArrayList<Throwable>();var sub=adapter.follow("session-fixture",e->{},e->{errors.add(e);latch.countDown();});try{assertThat(latch.await(3,TimeUnit.SECONDS)).isTrue();assertThat(errors.getFirst()).isInstanceOf(DshRc2Exception.class).hasMessage("DSH remote.mux frame is malformed");}finally{sub.close();}}
    @Test void dsh013_foreignSessionSnapshotIsRejected() throws Exception{server.muxMode=FakeDshRc2Server.MuxMode.FOREIGN_SESSION;var latch=new CountDownLatch(1);var errors=new CopyOnWriteArrayList<Throwable>();var sub=adapter.follow("session-fixture",e->{},e->{errors.add(e);latch.countDown();});try{assertThat(latch.await(3,TimeUnit.SECONDS)).isTrue();assertThat(errors.getFirst()).isInstanceOf(DshRc2Exception.class).satisfies(e->assertThat(((DshRc2Exception)e).code()).isEqualTo("protocol/foreign-session"));}finally{sub.close();}}
    @Test void dsh014_concurrentFollowSessionsRemainBoundToTheirOwnStreamIds() throws Exception {var received=new CopyOnWriteArrayList<String>();var latch=new CountDownLatch(2);var a=adapter.follow("session-a",e->{if(e.kind()==DshFollowEvent.Kind.SNAPSHOT){received.add(e.sessionId());latch.countDown();}},e->{});var b=adapter.follow("session-b",e->{if(e.kind()==DshFollowEvent.Kind.SNAPSHOT){received.add(e.sessionId());latch.countDown();}},e->{});try{assertThat(latch.await(3,TimeUnit.SECONDS)).isTrue();assertThat(received).containsExactlyInAnyOrder("session-a","session-b");}finally{a.close();b.close();}}
    @Test void dsh015_remoteErrorAndMalformedResponseDoNotLeakCredentials(){server.malformedNext("workspace/create");assertThatThrownBy(()->adapter.findOrCreateWorkspace(workspace.toString())).isInstanceOf(DshRc2Exception.class).hasMessage("DSH returned a malformed RPC response").hasMessageNotContaining("launch-secret").hasMessageNotContaining("fake-cookie");}
    @Test void dsh016_expiredCookieIsReauthenticatedOnce(){server.expireNextCookie=true;assertThat(adapter.findOrCreateWorkspace(workspace.toString())).isEqualTo("workspace-fixture");assertThat(server.requests("workspace/create")).hasSize(2);}
    @Test void dsh017_rpcCorrelationMismatchIsRejected(){server.badRpcId=true;assertThatThrownBy(()->adapter.findOrCreateWorkspace(workspace.toString())).isInstanceOf(DshRc2Exception.class).hasMessage("DSH returned a malformed RPC response");}
    @Test void dsh018_remoteFailureCodeIsPreservedButMessageIsSanitized(){server.remoteErrorEndpoint="workspace/create";assertThatThrownBy(()->adapter.findOrCreateWorkspace(workspace.toString())).isInstanceOf(DshRc2Exception.class).hasMessage("DSH remote operation failed").satisfies(e->assertThat(((DshRc2Exception)e).code()).isEqualTo("workspace/not-found"));}
    @Test void dsh019_foreignStreamIdIsRejected(){server.muxMode=FakeDshRc2Server.MuxMode.FOREIGN_STREAM;var latch=new CountDownLatch(1);var errors=new CopyOnWriteArrayList<Throwable>();var sub=adapter.follow("session-fixture",e->{},e->{errors.add(e);latch.countDown();});try{assertThat(latch.await(3,TimeUnit.SECONDS)).isTrue();assertThat(errors.getFirst()).isInstanceOf(DshRc2Exception.class).satisfies(e->assertThat(((DshRc2Exception)e).code()).isEqualTo("protocol/foreign-stream"));}catch(InterruptedException e){Thread.currentThread().interrupt();fail(e);}finally{sub.close();}}
    @Test void dsh020_promptCancellationCancelsInFlightHttpRequest() throws Exception{server.timeoutNext("session/prompt",1000);var token=new online.wanan.xingchen.core.agent.CancellationToken();var executor=Executors.newSingleThreadExecutor();try{var pending=executor.submit(()->adapter.prompt("s-cancel","hello",token));long deadline=System.nanoTime()+TimeUnit.SECONDS.toNanos(2);while(server.requests("session/prompt").isEmpty()&&System.nanoTime()<deadline)Thread.sleep(10);assertThat(server.requests("session/prompt")).hasSize(1);token.cancel();assertThatThrownBy(pending::get).isInstanceOf(ExecutionException.class).hasCauseInstanceOf(CancellationException.class);}finally{executor.shutdownNow();}}
    @Test void dsh021_presetSelectionIsOnlyAvailableOnSessionCreate(){assertThatThrownBy(()->adapter.selectPreset("s1","qq-chat")).isInstanceOf(UnsupportedOperationException.class).hasMessageContaining("only during session/create");}
    @Test void dsh022_followCompletionIsObservableAndDistinctFromDisconnect() throws Exception {
        server.muxMode=FakeDshRc2Server.MuxMode.END;
        var events=new CopyOnWriteArrayList<DshFollowEvent>();
        var errors=new CopyOnWriteArrayList<Throwable>();
        var sub=adapter.follow("session-fixture",events::add,errors::add);
        try {
            sub.completion().toCompletableFuture().get(3,TimeUnit.SECONDS);
            assertThat(sub.isOpen()).isFalse();
            assertThat(events).extracting(DshFollowEvent::kind)
                    .containsExactly(DshFollowEvent.Kind.SNAPSHOT,DshFollowEvent.Kind.DURABLE_EVENT);
            assertThat(errors).isEmpty();
        } finally { sub.close(); }
    }
    @Test void dshevt001_openEventsStreamWaitsForReadyBeforeDeliveringApproval() throws Exception{var mapper=new ObjectMapper();var req=mapper.createObjectNode().put("toolName","bash").put("callId","call-7").put("reason","write file");server.waterfall("evt-7","session-fixture","approval/request",req);var received=new ArrayBlockingQueue<DshInteractionEvent>(2);var sub=adapter.interactionEvents(received::offer,e->fail(e));try{var event=received.poll(3,TimeUnit.SECONDS);assertThat(sub.currentClientId()).isEqualTo("event-client-1");assertThat(event).isInstanceOfSatisfying(DshApprovalRequest.class,a->{assertThat(a.agentId()).isEqualTo("session-fixture");assertThat(a.eventId()).isEqualTo("evt-7");assertThat(a.clientId()).isEqualTo("event-client-1");assertThat(a.clientGeneration()).isEqualTo(1);assertThat(a.toolName()).isEqualTo("bash");assertThat(a.callId()).isEqualTo("call-7");assertThat(a.reason()).isEqualTo("write file");});}finally{sub.close();}}
    @Test void dshevt002_questionWaterfallMapsStableQuestionIdsAndAnswerUsesExactResultRpc() throws Exception{var mapper=new ObjectMapper();var request=mapper.createObjectNode();request.putArray("questions").addObject().put("id","q-1").put("question","Continue?").putArray("options").addObject().put("label","Yes");server.waterfall("evt-q","session-fixture","user-questions/request",request);var received=new ArrayBlockingQueue<DshInteractionEvent>(1);var sub=adapter.interactionEvents(received::offer,e->fail(e));try{var event=received.poll(3,TimeUnit.SECONDS);assertThat(event).isInstanceOfSatisfying(DshUserQuestionRequest.class,q->{assertThat(q.questions()).containsExactly(new DshInteractionEvent.Question("q-1","Continue?",List.of("Yes")));});var value=mapper.createObjectNode();value.putArray("answers").addObject().put("id","q-1").putArray("selected").add("Yes");var outcome=mapper.createObjectNode().put("kind","result");outcome.set("value",value);adapter.respondToInteraction(event.clientId(),event.eventId(),outcome);var sent=server.requests("$events/result").getFirst().envelope();assertThat(sent.path("method").asText()).isEqualTo("$events/result");assertThat(sent.path("payload").path("args").path("clientId").asText()).isEqualTo("event-client-1");assertThat(sent.path("payload").path("args").path("eventId").asText()).isEqualTo("evt-q");assertThat(sent.path("payload").path("args").path("outcome").path("kind").asText()).isEqualTo("result");assertThat(sent.path("payload").path("args").has("request")).isFalse();}finally{sub.close();}}
    @Test void dshevt003_staleClientGenerationCannotPostAnEventResult(){var outcome=new ObjectMapper().createObjectNode().put("kind","next");assertThatThrownBy(()->adapter.respondToInteraction("old-client","evt-old",outcome)).isInstanceOf(DshRc2Exception.class).satisfies(e->assertThat(((DshRc2Exception)e).code()).isEqualTo("interaction/stale-client"));assertThat(server.requests("$events/result")).isEmpty();}
}
