package online.wanan.xingchen.core.agent;

public enum AgentCapability { QQ_READ, QQ_SEND, QQ_REPLY, QQ_WAIT, QQ_POKE, MEMORY_READ, MEMORY_WRITE, MEMORY_ADDRESS, STICKER_READ, STICKER_SEND, STICKER_WRITE, SLANG_READ, SLANG_WRITE, SHELL, SSH, DOCKER, ARBITRARY_FILESYSTEM, PROCESS_CONTROL }
