package online.wanan.xingchen.core.agent;

import online.wanan.xingchen.adapter.onebot.*;
import online.wanan.xingchen.core.identity.*;
import online.wanan.xingchen.core.memory.*;
import online.wanan.xingchen.core.model.*;
import online.wanan.xingchen.core.relationship.*;
import online.wanan.xingchen.core.slang.*;
import online.wanan.xingchen.core.sticker.*;
import java.time.*;
import java.util.*;

/** Concrete social tool router. Every destination and persistent write is checked against the active request. */
public final class SocialToolExecutor implements ToolExecutor {
    private final OneBotGateway gateway;private final AgentToolCatalog catalog;private final MemoryRepository memories;private final MemoryRetriever retriever;private final MemoryPolicy memoryPolicy;private final IdentityRegistry identities;private final RelationshipTermRegistry terms;private final String botPlatformId;private final StickerService stickers;private final SlangService slang;private final Clock clock;private final SimulationStateService simulation;private final online.wanan.xingchen.core.conversation.OutboundExecutionService outbound;
    public SocialToolExecutor(OneBotGateway gateway,AgentToolCatalog catalog,MemoryRepository memories,MemoryRetriever retriever,MemoryPolicy memoryPolicy,IdentityRegistry identities,RelationshipTermRegistry terms,String botPlatformId,StickerService stickers,SlangService slang,Clock clock){this(gateway,catalog,memories,retriever,memoryPolicy,identities,terms,botPlatformId,stickers,slang,clock,null);}
    public SocialToolExecutor(OneBotGateway gateway,AgentToolCatalog catalog,MemoryRepository memories,MemoryRetriever retriever,MemoryPolicy memoryPolicy,IdentityRegistry identities,RelationshipTermRegistry terms,String botPlatformId,StickerService stickers,SlangService slang,Clock clock,SimulationStateService simulation){this(gateway,catalog,memories,retriever,memoryPolicy,identities,terms,botPlatformId,stickers,slang,clock,simulation,null);}
    public SocialToolExecutor(OneBotGateway gateway,AgentToolCatalog catalog,MemoryRepository memories,MemoryRetriever retriever,MemoryPolicy memoryPolicy,IdentityRegistry identities,RelationshipTermRegistry terms,String botPlatformId,StickerService stickers,SlangService slang,Clock clock,SimulationStateService simulation,online.wanan.xingchen.core.conversation.OutboundExecutionService outbound){this.gateway=gateway;this.catalog=catalog;this.memories=memories;this.retriever=retriever;this.memoryPolicy=memoryPolicy;this.identities=identities;this.terms=terms;this.botPlatformId=botPlatformId;this.stickers=stickers;this.slang=slang;this.clock=clock;this.simulation=simulation;this.outbound=outbound;}
    @Override public ToolResult execute(ToolCall call,AgentRequest request,Set<AgentCapability> capabilities){
        if(call==null||!catalog.allows(call.name(),capabilities))return fail("capability denied");
        try{return switch(call.name()){
            case "qq.readRecent"->messages(request,arg(call,"conversation"),intArg(call,"limit",20),false);
            case "qq.readUnread"->messages(request,arg(call,"conversation"),intArg(call,"limit",20),true);
            case "qq.markRead"->markRead(request,call);
            case "qq.wait"->waitMessages(request,call);
            case "qq.send"->send(request,call);
            case "qq.sendMultiple"->sendMultiple(request,call);
            case "qq.setWakeConfig"->setWakeConfig(request,call);
            case "qq.reply"->reply(request,call);
            case "qq.getMember"->getMember(request,call);
            case "qq.getMembers"->getMembers(request,call);
            case "qq.poke"->poke(request,call);
            case "memory.search"->searchMemory(request,call);
            case "memory.remember"->remember(request,call);
            case "memory.update"->updateMemory(request,call);
            case "memory.setAddress"->setAddress(request,call);
            case "memory.getPerson"->getPerson(call);
            case "sticker.list"->stickerList(call);
            case "sticker.search"->stickerSearch(call);
            case "sticker.send"->stickerSend(request,call);
            case "sticker.collect"->stickerCollect(call);
            case "sticker.note"->stickerNote(call);
            case "slang.search"->slangSearch(call);
            case "slang.submit"->slangSubmit(call);
            default->fail("tool is not implemented");
        };}catch(java.util.concurrent.CancellationException e){return fail("operation cancelled");}catch(Exception e){return fail("tool operation failed safely");}
    }
    private ToolResult messages(AgentRequest r,String conversation,int limit,boolean unread){if(!sameConversation(r,conversation))return fail("conversation scope denied");var events=unread?gateway.getUnreadMessages(conversation,clamp(limit,1,50)):gateway.getRecentMessages(conversation,clamp(limit,1,50));if(unread&&simulation!=null){String cursor=simulation.get(r.actor().conversation().id()).lastReadCursor();if(cursor!=null){int index=-1;for(int i=0;i<events.size();i++)if(events.get(i).message().platformMessageId().equals(cursor))index=i;if(index<0)return fail("persisted read cursor is outside the adapter unread window; refusing replay");events=events.subList(index+1,events.size());}}return ok("messages",Map.of("messages",events.stream().map(SocialToolExecutor::safeEvent).toList()));}
    private ToolResult markRead(AgentRequest r,ToolCall c){String conversation=arg(c,"conversation"),cursor=arg(c,"cursor");if(!sameConversation(r,conversation))return fail("conversation scope denied");if(simulation==null)return fail("persistent simulation state unavailable");boolean visible=gateway.getRecentMessages(conversation,100).stream().anyMatch(e->e.message().platformMessageId().equals(cursor));if(!visible)return fail("cursor is not an observed recent message");try{var state=simulation.markRead(r.actor().conversation().id(),cursor);return ok("read cursor saved",Map.of("cursor",state.lastReadCursor(),"generation",state.generation()));}catch(IllegalArgumentException e){return fail("cursor ordering could not be verified");}}
    private ToolResult waitMessages(AgentRequest r,ToolCall c){String conversation=arg(c,"conversation");if(!sameConversation(r,conversation))return fail("conversation scope denied");int seconds=clamp(intArg(c,"timeoutSeconds",10),1,30);return ok("messages",Map.of("messages",gateway.waitForMessages(conversation,Duration.ofSeconds(seconds)).stream().map(SocialToolExecutor::safeEvent).toList()));}
    private ToolResult sendMultiple(AgentRequest r,ToolCall c){Object raw=c.arguments().get("messages");if(!(raw instanceof List<?> values)||values.isEmpty()||values.size()>5)return fail("batch must contain 1-5 messages");List<String> receipts=new ArrayList<>();int ordinal=0;for(Object value:values){if(!(value instanceof String text)||text.isBlank()||text.length()>2000)return fail("invalid batch message");ToolCall child=new ToolCall("qq.send",Map.of("target",arg(c,"target"),"kind",arg(c,"kind"),"text",text),Objects.toString(c.callId(),"batch")+":"+ordinal++);ToolResult result=send(r,child);receipts.add(result.message());if(!result.success()||"UNKNOWN".equals(result.data().get("deliveryStatus")))return new ToolResult(result.success(),"batch stopped at uncertain or failed delivery",Map.of("completed",receipts.size(),"receipts",receipts,"stopped",true));}return ok("batch accepted",Map.of("completed",receipts.size(),"receipts",receipts));}
    private ToolResult setWakeConfig(AgentRequest r,ToolCall c){String conversation=arg(c,"conversation");if(!sameConversation(r,conversation))return fail("conversation scope denied");if(!r.actor().flags().owner())return fail("owner authorization required");if(simulation==null)return fail("persistent simulation state unavailable");Map<String,Object> config=new LinkedHashMap<>();for(String key:List.of("mention","name","question","poke"))if(c.arguments().containsKey(key))config.put(key,c.arguments().get(key));Object speakers=c.arguments().get("speakers");if(speakers!=null)config.put("speakers",speakers);try{var state=simulation.configure(r.actor().conversation().id(),config,true);return ok("wake configuration saved",Map.of("generation",state.generation()));}catch(IllegalArgumentException e){return fail("invalid wake configuration");}}
    private ToolResult send(AgentRequest r,ToolCall c){String target=arg(c,"target"),kind=arg(c,"kind"),text=arg(c,"text");if(text.isBlank()||text.length()>2000)return fail("invalid text");if(r.actor().conversation().identity().type()==ConversationType.PRIVATE){if(!kind.equals("private")||!target.equals(r.actor().person().platformUserId()))return fail("private destination must be current speaker");return sendWithLedger(r,c,target,()->gateway.sendPrivateMessage(target,text));}if(!kind.equals("group")||!target.equals(r.actor().conversation().identity().platformConversationId()))return fail("group destination must be current conversation");return sendWithLedger(r,c,target,()->gateway.sendGroupMessage(target,text));}
    private ToolResult reply(AgentRequest r,ToolCall c){String id=arg(c,"messageId");if(id.isBlank())return fail("message id required");Optional<PlatformEvent> source=gateway.getMessage(id);if(source.isPresent()&&!sameConversation(r,source.get().conversation().platformConversationId()))return fail("reply source belongs to another conversation");if(source.isEmpty()&&!id.equals(r.eventId()))return fail("reply source is not in the current event context");return sendWithLedger(r,c,r.actor().conversation().identity().platformConversationId(),()->gateway.replyMessage(id,arg(c,"text")));}
    private ToolResult getMember(AgentRequest r,ToolCall c){String group=arg(c,"groupId");if(!isCurrentGroup(r,group))return fail("group scope denied");return gateway.getGroupMember(group,arg(c,"userId")).<ToolResult>map(m->ok("member",Map.of("member",m))).orElseGet(()->fail("member not found"));}
    private ToolResult getMembers(AgentRequest r,ToolCall c){String group=arg(c,"groupId");if(!isCurrentGroup(r,group))return fail("group scope denied");return ok("members",Map.of("members",gateway.getGroupMembers(group).stream().limit(clamp(intArg(c,"limit",100),1,100)).toList()));}
    private ToolResult poke(AgentRequest r,ToolCall c){String group=arg(c,"groupId"),user=arg(c,"userId");if(!isCurrentGroup(r,group))return fail("group scope denied");if(gateway.getGroupMember(group,user).isEmpty()&&!user.equals(r.actor().person().platformUserId()))return fail("poke target is not a known group member");return sendWithLedger(r,c,group,()->gateway.sendPoke(group,user));}
    private ToolResult searchMemory(AgentRequest r,ToolCall c){int limit=clamp(intArg(c,"limit",10),1,50);RequestContext rc=request(r);var result=retriever.retrieve(rc,arg(c,"query"),r.actor().conversation().id(),r.actor().person().id(),Math.min(4000,limit*300));return ok("memory matches",Map.of("memories",result.memories().stream().map(m->Map.of("id",m.id().toString(),"type",m.type().name(),"scope",m.scopeType().name(),"content",m.content())).toList()));}
    private ToolResult remember(AgentRequest r,ToolCall c){MemoryCandidate candidate=new MemoryCandidate(r.actor().person().id(),MemoryType.valueOf(arg(c,"type").toUpperCase(Locale.ROOT)),arg(c,"content"),MemoryScope.valueOf(arg(c,"scope").toUpperCase(Locale.ROOT)),r.actor().conversation().id(),arg(c,"projectKey"),.8,doubleArg(c,"importance",.5),true,r.eventId());MemoryPolicy.Evaluation e=memoryPolicy.evaluate(candidate,r.actor());if(e.memory()==null)return fail(e.reason());Memory saved=memories.save(e.memory(),List.of(new MemorySource(e.memory().id(),r.actor().person().platform().name(),r.actor().conversation().id(),Objects.toString(r.eventId(),"unknown"),r.actor().person().id(),clock.instant())));return ok("memory "+e.outcome().name().toLowerCase(Locale.ROOT),Map.of("memoryId",saved.id().toString(),"scope",saved.scopeType().name(),"subjectPersonId",saved.subjectPersonId().toString()));}
    private ToolResult updateMemory(AgentRequest r,ToolCall c){UUID id=UUID.fromString(arg(c,"memoryId"));Memory old=memories.get(id).orElse(null);if(old==null||!MemoryVisibility.canRead(old,request(r)))return fail("memory unavailable in request scope");String content=arg(c,"content");if(content.isBlank()||content.length()>2000)return fail("invalid memory content");Memory updated=new Memory(old.id(),old.type(),old.subjectPersonId(),old.conversationId(),old.projectKey(),content,old.scopeType(),old.scopeId(),old.confidence(),old.importance(),old.explicit(),old.createdAt(),clock.instant(),old.lastAccessedAt(),old.expiresAt(),old.status());memories.update(updated);return ok("memory updated",Map.of("memoryId",id.toString()));}
    private ToolResult setAddress(AgentRequest r,ToolCall c){UUID targetId=UUID.fromString(arg(c,"targetPersonId"));Person target=identities.findById(targetId).orElse(null);Person bot=identities.find(Platform.QQ,botPlatformId).orElse(null);if(target==null||bot==null)return fail("target identity is not established");boolean sameGroup=identities.memberships(targetId).stream().anyMatch(m->m.conversationId().equals(r.actor().conversation().id()));if(!sameGroup&&!r.actor().flags().owner())return fail("target must be a known member of this conversation");String address=arg(c,"address");if(address.isBlank()||address.length()>40||address.chars().anyMatch(Character::isISOControl))return fail("invalid address");String raw=arg(c,"scope").toUpperCase(Locale.ROOT);ScopeType scope=ScopeType.valueOf(raw);if(scope==ScopeType.GLOBAL&&!r.actor().flags().owner())return fail("global address requires owner");if(scope==ScopeType.PRIVATE&&r.actor().conversation().identity().type()!=ConversationType.PRIVATE)return fail("private address scope requires a private conversation");String scopeId=scope==ScopeType.GLOBAL?null:r.actor().conversation().identity().platformConversationId();Instant now=clock.instant();RelationshipTerm term=new RelationshipTerm(UUID.randomUUID(),bot.id(),targetId,RelationshipType.ADDRESS_AS,address,scope,scopeId,true,1.0,r.eventId(),now,now);terms.save(term);return ok("address updated",Map.of("targetPersonId",targetId.toString(),"address",address,"scope",scope.name()));}
    private ToolResult getPerson(ToolCall c){Platform p=Platform.valueOf(arg(c,"platform").toUpperCase(Locale.ROOT));Person person=identities.find(p,arg(c,"platformUserId")).orElse(null);if(person==null)return fail("person identity not found");return ok("person",Map.of("personId",person.id().toString(),"platform",person.platform().name(),"platformUserId",person.platformUserId(),"owner",person.owner(),"self",person.self()));}
    private ToolResult stickerList(ToolCall c){if(stickers==null)return fail("sticker service unavailable");return ok("stickers",Map.of("items",stickers.list(clamp(intArg(c,"limit",20),1,100))));}
    private ToolResult stickerSearch(ToolCall c){if(stickers==null)return fail("sticker service unavailable");return ok("stickers",Map.of("items",stickers.search(arg(c,"query"),clamp(intArg(c,"limit",20),1,100))));}
    private ToolResult stickerSend(AgentRequest r,ToolCall c){if(stickers==null)return fail("sticker service unavailable");String target=arg(c,"target"),kind=arg(c,"kind");if(r.actor().conversation().identity().type()==ConversationType.PRIVATE){if(!kind.equals("private")||!target.equals(r.actor().person().platformUserId()))return fail("private sticker target denied");}else if(!kind.equals("group")||!isCurrentGroup(r,target))return fail("group sticker target denied");UUID stickerId=UUID.fromString(arg(c,"stickerId"));return sendWithLedger(r,c,target,()->stickers.send(stickerId,target,kind));}
    private ToolResult stickerCollect(ToolCall c){if(stickers==null)return fail("sticker service unavailable");try{var tags=c.arguments().get("tags") instanceof List<?> list?list.stream().map(Object::toString).toList():List.<String>of();return ok("sticker collected",Map.of("sticker",stickers.collect(arg(c,"assetId"),tags,"agent-local-inbox")));}catch(java.io.IOException e){return fail("sticker asset unavailable");}}
    private ToolResult stickerNote(ToolCall c){if(stickers==null)return fail("sticker service unavailable");return stickers.note(UUID.fromString(arg(c,"stickerId")),arg(c,"note")).<ToolResult>map(s->ok("sticker noted",Map.of("id",s.id().toString()))).orElseGet(()->fail("sticker not found"));}
    private ToolResult slangSearch(ToolCall c){if(slang==null)return fail("slang service unavailable");return ok("slang entries",Map.of("items",slang.search(arg(c,"query"),clamp(intArg(c,"limit",20),1,100))));}
    private ToolResult slangSubmit(ToolCall c){if(slang==null)return fail("slang service unavailable");var entry=slang.submit(arg(c,"term"),arg(c,"meaning"),arg(c,"usage"),arg(c,"example"),arg(c,"risk"),List.of(Objects.toString(c.arguments().get("source"),"agent")),List.of(Objects.toString(c.arguments().get("evidence"),"")));return ok("slang candidate submitted",Map.of("id",entry.id().toString(),"status",entry.status().name()));}
    private static Map<String,Object> safeEvent(PlatformEvent e){return Map.of("eventId",e.message().platformMessageId(),"actorId",e.actor().platformUserId(),"displayName",e.actor().displayName(),"conversationId",e.conversation().platformConversationId(),"text",e.text(),"replyTo",Objects.toString(e.message().replyToMessageId(),""));}
    private ToolResult sendWithLedger(AgentRequest request,ToolCall call,String target,java.util.function.Supplier<SendReceipt> operation){
        if(outbound==null)return receipt(operation.get());
        String conversation=request.actor().conversation().id().toString();String turn=Objects.toString(request.turnId(),Objects.toString(request.eventId(),""));
        String callIdentity=call.callId()==null||call.callId().isBlank()?call.name()+":"+digest(call.arguments()):call.callId();
        long generation=simulation==null?0:simulation.get(request.actor().conversation().id()).generation();
        String key=conversation+":"+turn+":"+callIdentity;
        var record=outbound.dispatch(key,request.actor().conversation().id(),turn,generation,callIdentity,target,operation::get);
        DeliveryStatus status=switch(record.status()){case SUCCESS->DeliveryStatus.ACCEPTED;case FAILED->DeliveryStatus.REJECTED;case UNKNOWN,PENDING->DeliveryStatus.UNKNOWN;};
        return receipt(new SendReceipt(status==DeliveryStatus.ACCEPTED,"tool-outbound",Objects.toString(record.providerMessageId(),target),Objects.toString(record.failureReason(),""),status));
    }
    private static String digest(Map<String,Object> values){try{var md=java.security.MessageDigest.getInstance("SHA-256");byte[] hash=md.digest(new TreeMap<>(values).toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));return java.util.HexFormat.of().formatHex(hash,0,12);}catch(java.security.NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
    private static RequestContext request(AgentRequest r){return new RequestContext(r.actor().person().id(),r.actor().conversation().id(),r.actor().flags().owner(),null);}
    private static boolean sameConversation(AgentRequest r,String id){return Objects.equals(id,r.actor().conversation().identity().platformConversationId());}
    private static boolean isCurrentGroup(AgentRequest r,String id){return r.actor().conversation().identity().type()==ConversationType.GROUP&&sameConversation(r,id);}
    private static ToolResult receipt(SendReceipt r){String message=switch(r.status()){case ACCEPTED->"operation accepted";case REJECTED->"operation rejected";case UNKNOWN->"delivery outcome unknown; do not retry automatically";};return new ToolResult(r.accepted(),message,Map.of("operation",r.operation(),"target",r.target(),"deliveryStatus",r.status().name()));}
    private static ToolResult ok(String message,Map<String,Object> data){return new ToolResult(true,message,data);}private static ToolResult fail(String message){return new ToolResult(false,message,Map.of());}
    private static String arg(ToolCall c,String key){return Objects.toString(c.arguments().get(key),"");}
    private static int intArg(ToolCall c,String key,int fallback){try{return Integer.parseInt(arg(c,key));}catch(NumberFormatException e){return fallback;}}
    private static int clamp(int n,int low,int high){return Math.max(low,Math.min(high,n));}
    private static double doubleArg(ToolCall c,String key,double fallback){try{return Double.parseDouble(arg(c,key));}catch(NumberFormatException e){return fallback;}}
}
