package online.wanan.xingchen.storage;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import online.wanan.xingchen.core.sticker.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.time.Instant;
import java.util.*;

@Repository public class SqliteStickerRepository implements StickerRepository {
    private final JdbcTemplate jdbc;private final ObjectMapper mapper;
    public SqliteStickerRepository(JdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;}
    @Override public StickerMetadata save(StickerMetadata s){jdbc.update("INSERT INTO stickers(id,path,sha256,tags_json,note,usage_count,source,created_at,last_used_at,file_name,mime_type,file_size,width,height,animated,enabled,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",s.id().toString(),s.path(),s.sha256(),json(s.tags()),s.note(),s.usageCount(),s.source(),s.createdAt().toString(),str(s.lastUsedAt()),s.fileName(),s.mimeType(),s.fileSize(),s.width(),s.height(),s.animated()==null?null:(s.animated()?1:0),s.enabled()?1:0,s.updatedAt().toString());return s;}
    @Override public Optional<StickerMetadata> get(UUID id){return jdbc.query("SELECT * FROM stickers WHERE id=?",(r,n)->map(r),id.toString()).stream().findFirst();}
    @Override public Optional<StickerMetadata> findByHash(String hash){return jdbc.query("SELECT * FROM stickers WHERE sha256=?",(r,n)->map(r),hash).stream().findFirst();}
    @Override public List<StickerMetadata> list(int limit){return jdbc.query("SELECT * FROM stickers WHERE enabled=1 ORDER BY usage_count DESC,created_at DESC LIMIT ?",(r,n)->map(r),bounded(limit));}
    @Override public List<StickerMetadata> search(String q,int limit){String term="%"+Objects.requireNonNullElse(q,"").replace("%","\\%").replace("_","\\_")+"%";return jdbc.query("SELECT * FROM stickers WHERE enabled=1 AND (file_name LIKE ? ESCAPE '\\' OR note LIKE ? ESCAPE '\\' OR tags_json LIKE ? ESCAPE '\\') ORDER BY usage_count DESC LIMIT ?",(r,n)->map(r),term,term,term,bounded(limit));}
    @Override public StickerPage page(String q,Boolean enabled,String format,Boolean animated,int offset,int limit){String term="%"+Objects.requireNonNullElse(q,"").replace("%","\\%").replace("_","\\_")+"%";String normalized=format==null?"":format.trim().toLowerCase(Locale.ROOT);String ext=normalized.isBlank()?null:"%."+normalized.replace("%","\\%").replace("_","\\_");String mime=normalized.isBlank()?null:switch(normalized){case "jpg","jpeg"->"image/jpeg";case "png"->"image/png";case "gif"->"image/gif";case "webp"->"image/webp";default->"image/unsupported";};String f=ext==null?null:ext;String m=mime;
        String where=" WHERE (? IS NULL OR enabled=?) AND (?='' OR file_name LIKE ? ESCAPE '\\' OR note LIKE ? ESCAPE '\\' OR tags_json LIKE ? ESCAPE '\\') AND (? IS NULL OR lower(mime_type)=? OR lower(file_name) LIKE ? ESCAPE '\\') AND (? IS NULL OR animated=?)";
        Object[] args={enabled==null?null:(enabled?1:0),enabled==null?null:(enabled?1:0),Objects.requireNonNullElse(q,""),term,term,term,f,m,ext,animated==null?null:(animated?1:0),animated==null?null:(animated?1:0)};
        Long total=jdbc.queryForObject("SELECT COUNT(*) FROM stickers"+where,Long.class,args);int pageLimit=Math.max(1,Math.min(100,limit)),pageOffset=Math.max(0,Math.min(100_000,offset));List<StickerMetadata> items=jdbc.query("SELECT * FROM stickers"+where+" ORDER BY updated_at DESC,created_at DESC LIMIT ? OFFSET ?",(r,n)->map(r),append(args,pageLimit,pageOffset));return new StickerPage(items,total==null?0:total,pageOffset,pageLimit);}
    @Override public Optional<StickerMetadata> updateNote(UUID id,String note){if(jdbc.update("UPDATE stickers SET note=?,updated_at=? WHERE id=?",note,Instant.now().toString(),id.toString())==0)return Optional.empty();return get(id);}
    @Override public Optional<StickerMetadata> updateAdmin(UUID id,List<String> tags,String note,boolean enabled){if(jdbc.update("UPDATE stickers SET tags_json=?,note=?,enabled=?,updated_at=? WHERE id=?",json(tags),note,enabled?1:0,Instant.now().toString(),id.toString())==0)return Optional.empty();return get(id);}
    @Override public Optional<StickerMetadata> updateAdmin(UUID id,List<String> tags,String note,boolean enabled,String expectedUpdatedAt){if(jdbc.update("UPDATE stickers SET tags_json=?,note=?,enabled=?,updated_at=? WHERE id=? AND updated_at=?",json(tags),note,enabled?1:0,Instant.now().toString(),id.toString(),expectedUpdatedAt)==0)return Optional.empty();return get(id);}
    @Override public Optional<StickerMetadata> recordUse(UUID id,Instant at){if(jdbc.update("UPDATE stickers SET usage_count=usage_count+1,last_used_at=? WHERE id=?",at.toString(),id.toString())==0)return Optional.empty();return get(id);}
    private StickerMetadata map(java.sql.ResultSet r)throws java.sql.SQLException{try{Instant created=Instant.parse(r.getString("created_at"));String updatedText=r.getString("updated_at");return new StickerMetadata(UUID.fromString(r.getString("id")),r.getString("path"),r.getString("sha256"),mapper.readValue(r.getString("tags_json"),new TypeReference<>(){}),r.getString("note"),r.getLong("usage_count"),r.getString("source"),created,r.getString("last_used_at")==null?null:Instant.parse(r.getString("last_used_at")),r.getString("file_name"),r.getString("mime_type"),r.getLong("file_size"),nullableInt(r.getObject("width")),nullableInt(r.getObject("height")),r.getObject("animated")==null?null:r.getInt("animated")!=0,r.getInt("enabled")!=0,updatedText==null||updatedText.isBlank()?created:Instant.parse(updatedText));}catch(Exception e){throw new java.sql.SQLException("invalid sticker metadata",e);}}
    private static Integer nullableInt(Object value){return value==null?null:((Number)value).intValue();}
    private String json(Object o){try{return mapper.writeValueAsString(o);}catch(Exception e){throw new IllegalStateException(e);}}private static String str(Instant x){return x==null?null:x.toString();}private static int bounded(int n){return Math.max(1,Math.min(500,n));}private static Object[] append(Object[] values,Object...tail){Object[] out=Arrays.copyOf(values,values.length+tail.length);System.arraycopy(tail,0,out,values.length,tail.length);return out;}
}
