package online.wanan.xingchen.storage;

import com.fasterxml.jackson.databind.ObjectMapper;
import online.wanan.xingchen.core.agent.SimulationConversationState;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.*;

@Repository
public class SqliteSimulationStateRepository {
    private final JdbcTemplate jdbc; private final ObjectMapper mapper;
    public SqliteSimulationStateRepository(JdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;}
    public SimulationConversationState load(UUID id){return jdbc.query("SELECT * FROM simulation_conversation_state WHERE conversation_id=?",(rs,n)->new SimulationConversationState(id,rs.getString("mode"),SimulationConversationState.WakeState.valueOf(rs.getString("wake_state")),rs.getString("last_read_cursor"),instant(rs.getString("last_action_at")),instant(rs.getString("last_incoming_at")),instant(rs.getString("sleep_until")),readMap(rs.getString("wake_config_json")),rs.getInt("consecutive_no_action"),rs.getLong("generation"),instant(rs.getString("updated_at")),rs.getString("origin_turn_id"),instant(rs.getString("waiting_since")),rs.getString("wait_reason")),id.toString()).stream().findFirst().orElse(null);}
    @Transactional public void save(SimulationConversationState s){jdbc.update("INSERT INTO simulation_conversation_state(conversation_id,mode,wake_state,last_read_cursor,last_action_at,last_incoming_at,sleep_until,wake_config_json,consecutive_no_action,generation,updated_at,origin_turn_id,waiting_since,wait_reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(conversation_id) DO UPDATE SET mode=excluded.mode,wake_state=excluded.wake_state,last_read_cursor=excluded.last_read_cursor,last_action_at=excluded.last_action_at,last_incoming_at=excluded.last_incoming_at,sleep_until=excluded.sleep_until,wake_config_json=excluded.wake_config_json,consecutive_no_action=excluded.consecutive_no_action,generation=excluded.generation,updated_at=excluded.updated_at,origin_turn_id=excluded.origin_turn_id,waiting_since=excluded.waiting_since,wait_reason=excluded.wait_reason",s.conversationId().toString(),s.mode(),s.wakeState().name(),s.lastReadCursor(),str(s.lastActionAt()),str(s.lastIncomingAt()),str(s.sleepUntil()),writeMap(s.wakeConfig()),s.consecutiveNoAction(),s.generation(),str(s.updatedAt()),s.originTurnId(),str(s.waitingSince()),s.waitReason());}
    @Transactional public boolean claimWait(UUID id,long expectedGeneration,String reason,Instant now){return jdbc.update("UPDATE simulation_conversation_state SET wake_state='AWAKE',generation=generation+1,origin_turn_id=NULL,waiting_since=NULL,wait_reason=?,updated_at=? WHERE conversation_id=? AND wake_state='WAITING' AND generation=?",reason,str(now),id.toString(),expectedGeneration)==1;}
    @Transactional public boolean changeMode(UUID id,long expectedGeneration,String mode,Instant now){int changed=jdbc.update("UPDATE simulation_conversation_state SET mode=?,generation=generation+1,updated_at=? WHERE conversation_id=? AND generation=?",mode,str(now),id.toString(),expectedGeneration);if(changed==1)return true;if(expectedGeneration!=0)return false;return jdbc.update("INSERT OR IGNORE INTO simulation_conversation_state(conversation_id,mode,wake_state,generation,updated_at) VALUES(?,?,'AWAKE',1,?)",id.toString(),mode,str(now))==1;}
    @Transactional public boolean wake(UUID id,long expectedGeneration,Instant now){int changed=jdbc.update("UPDATE simulation_conversation_state SET wake_state='AWAKE',sleep_until=NULL,consecutive_no_action=0,origin_turn_id=NULL,waiting_since=NULL,wait_reason=NULL,generation=generation+1,updated_at=? WHERE conversation_id=? AND generation=? AND wake_state<>'WAITING'",str(now),id.toString(),expectedGeneration);if(changed==1)return true;if(expectedGeneration!=0)return false;return jdbc.update("INSERT OR IGNORE INTO simulation_conversation_state(conversation_id,mode,wake_state,generation,updated_at) VALUES(?,'SOCIAL','AWAKE',1,?)",id.toString(),str(now))==1;}
    @Transactional public long invalidateGeneration(UUID id,long expectedGeneration,Instant now){int changed=jdbc.update("UPDATE simulation_conversation_state SET generation=generation+1,updated_at=? WHERE conversation_id=? AND generation=?",str(now),id.toString(),expectedGeneration);if(changed==1)return expectedGeneration+1;if(expectedGeneration!=0)return -1;return jdbc.update("INSERT OR IGNORE INTO simulation_conversation_state(conversation_id,mode,wake_state,generation,updated_at) VALUES(?,'SOCIAL','IDLE',1,?)",id.toString(),str(now))==1?1:-1;}
    @Transactional public long invalidateGeneration(SimulationConversationState initial,Instant now){int changed=jdbc.update("UPDATE simulation_conversation_state SET generation=generation+1,updated_at=? WHERE conversation_id=?",str(now),initial.conversationId().toString());if(changed==0){var first=new SimulationConversationState(initial.conversationId(),initial.mode(),initial.wakeState(),initial.lastReadCursor(),initial.lastActionAt(),initial.lastIncomingAt(),initial.sleepUntil(),initial.wakeConfig(),initial.consecutiveNoAction(),1,now,initial.originTurnId(),initial.waitingSince(),initial.waitReason());save(first);return 1;}return load(initial.conversationId()).generation();}
    @Transactional public boolean cleanupReset(UUID id,long expectedGeneration,Instant now){return jdbc.update("UPDATE simulation_conversation_state SET wake_state='IDLE',last_read_cursor=NULL,sleep_until=NULL,consecutive_no_action=0,updated_at=?,origin_turn_id=NULL,waiting_since=NULL,wait_reason=NULL WHERE conversation_id=? AND generation=?",str(now),id.toString(),expectedGeneration)==1;}
    private String writeMap(Map<String,Object> map){try{return mapper.writeValueAsString(map);}catch(Exception e){throw new IllegalStateException("wake configuration could not be encoded",e);}}
    private Map<String,Object> readMap(String json){try{return mapper.readValue(json,mapper.getTypeFactory().constructMapType(Map.class,String.class,Object.class));}catch(Exception e){throw new IllegalStateException("persisted wake configuration is invalid",e);}}
    private static String str(Instant value){return value==null?null:value.toString();}
    private static Instant instant(String value){return value==null?null:Instant.parse(value);}
}
