import { useEffect, useRef, useState } from 'react'
import { api, apiErrorText } from './api'
import type { Language } from './i18n'

type Props = { language: Language }
const word = (l: Language, zh: string, en: string) => l === 'zh-CN' ? zh : en
const labels: Record<string, [string, string]> = {
 development:['开发构建','Development build'],unavailable:['不可用','Unavailable'],unknown:['未知','Unknown'],POLICY_UNAVAILABLE:['策略不可用，拒绝','Policy unavailable, deny'],
 'CSRF, BCrypt, redaction and capability/path guards enforced; no disable control':['强制 CSRF、BCrypt、脱敏和能力/路径防护；不能关闭','CSRF, BCrypt, redaction and capability/path guards enforced; no disable control'],
 message:['事件','Event'],LOGIN_SUCCEEDED:['登录成功','Login succeeded'],LOGIN_FAILED:['登录失败','Login failed'],LOGIN_RATE_LIMITED:['登录尝试受限','Login rate limited'],PASSWORD_CHANGED:['密码已更新','Password changed'],ACCESS_RULES_CHANGED:['访问规则已更新','Access rules changed'],
 name:['项目','Item'],value:['状态 / 值','Status / value'],timestamp:['时间','Time'],level:['等级','Level'],component:['组件','Component'],code:['事件代码','Event code'],correlationId:['关联 ID','Correlation ID'],actor:['操作者','Actor'],category:['类别','Category'],target:['目标','Target'],operation:['操作','Operation'],
 version:['版本','Version'],gitCommit:['提交','Commit'],uptimeMillis:['运行时间（毫秒）','Uptime (ms)'],javaVersion:['Java 版本','Java version'],database:['数据库','Database'],schemaVersion:['数据结构版本','Schema version'],databaseBytes:['数据库大小（字节）','Database size (bytes)'],activeConversations:['活动会话','Active conversations'],waitingConversations:['等待会话','Waiting conversations'],outboundUnknown:['发送结果未知','Unknown outbound results'],interruptedTurns:['中断回合','Interrupted turns'],queueDepth:['队列深度','Queue depth'],oneBotEnabled:['OneBot 已启用','OneBot enabled'],dshEnabled:['DSH 已启用','DSH enabled'],modelEnabled:['模型已启用','Model enabled'],externalIntegrationsEnabled:['外部集成已启用','External integrations enabled'],oneBotConnected:['OneBot 已连接','OneBot connected'],modelStatus:['模型状态','Model status'],heapUsed:['已用堆内存','Heap used'],heapMax:['最大堆内存','Heap maximum'],threadCount:['线程数','Thread count'],configApplyTracking:['配置应用跟踪','Configuration apply tracking'],pendingReconnect:['待重新连接','Pending reconnect'],pendingRestart:['待重启','Pending restart'],assetRootConfigured:['资源目录已配置','Asset root configured'],
 authenticationEnabled:['身份认证已启用','Authentication enabled'],passwordConfigured:['密码已配置','Password configured'],sessionTimeout:['会话超时','Session timeout'],csrfEnabled:['CSRF 防护已启用','CSRF enabled'],passwordEncoder:['密码编码','Password encoder'],cookieHttpOnly:['Cookie 仅 HTTP 可用','HTTP-only cookie'],cookieSameSite:['Cookie 同站策略','Cookie same-site policy'],cookieSecure:['Cookie 仅 HTTPS','Secure cookie'],bindAddress:['绑定地址','Bind address'],trustedProxyConfigured:['可信代理已配置','Trusted proxy configured'],publicBaseUrlConfigured:['公开地址已配置','Public base URL configured'],secretStore:['凭据存储状态','Secret store status'],gatewayEndpointPolicy:['网关地址策略','Gateway endpoint policy'],providerEndpointPolicy:['模型地址策略','Provider endpoint policy'],profileMode:['运行模式','Profile mode'],hardSecurity:['硬性安全策略','Hard security policy'],
 ALLOW:['允许 (ALLOW)','Allow (ALLOW)'],DENY:['拒绝 (DENY)','Deny (DENY)'],PRIVATE:['私聊 (PRIVATE)','Private (PRIVATE)'],GROUP:['群组 (GROUP)','Group (GROUP)'],EXPLICIT_ALLOW:['显式允许 (EXPLICIT_ALLOW)','Explicit allow (EXPLICIT_ALLOW)'],EXPLICIT_DENY:['显式拒绝 (EXPLICIT_DENY)','Explicit deny (EXPLICIT_DENY)'],DEFAULT_DENY:['默认拒绝 (DEFAULT_DENY)','Default deny (DEFAULT_DENY)'],OWNER:['所有者 (OWNER)','Owner (OWNER)'],GROUP_ALLOW:['群组允许 (GROUP_ALLOW)','Group allow (GROUP_ALLOW)'],POLICY_ERROR:['策略错误，拒绝 (POLICY_ERROR)','Policy error, deny (POLICY_ERROR)'],NOT_TRACKED:['未跟踪 (NOT_TRACKED)','Not tracked (NOT_TRACKED)'],UNKNOWN_NOT_TRACKED:['未知，未跟踪 (UNKNOWN_NOT_TRACKED)','Unknown, not tracked (UNKNOWN_NOT_TRACKED)'],UNKNOWN:['未知 (UNKNOWN)','Unknown (UNKNOWN)'],UP:['正常 (UP)','Up (UP)'],DOWN:['异常 (DOWN)','Down (DOWN)'],DISABLED:['已关闭 (DISABLED)','Disabled (DISABLED)'],AVAILABLE:['可用 (AVAILABLE)','Available (AVAILABLE)'],UNAVAILABLE:['不可用 (UNAVAILABLE)','Unavailable (UNAVAILABLE)'],FAKE_PROFILE_ACTIVE:['隔离模拟环境','Fake profile active'],PRODUCTION_PROFILE:['生产配置模式','Production profile'],
 'numeric loopback only':['仅数字形式的本机回环地址','Numeric loopback only'],'validated outbound URL policy':['经过验证的出站地址策略','Validated outbound URL policy'],
}
const label = (l: Language, value: string) => labels[value] ? word(l, ...labels[value]) : value
function cell(l:Language, value:unknown):string {
 if(value === null || value === undefined) return word(l,'不可用','Unavailable')
 if(typeof value === 'boolean') return word(l,value?'是':'否',value?'Yes':'No')
 if(typeof value === 'object') return Object.entries(value).map(([k,v])=>label(l,k)+': '+cell(l,v)).join(' · ')
 return label(l,String(value))
}
function DataTable({rows,language:l}:{rows:any[];language:Language}) {
 if(!rows.length) return <p>{word(l,'暂无记录','No records')}</p>
 const keys=Object.keys(rows[0])
 return <div className="responsive-table"><table><thead><tr>{keys.map(k=><th key={k}>{label(l,k)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{keys.map(k=><td key={k}>{cell(l,r[k])}</td>)}</tr>)}</tbody></table></div>
}
function Retry({language:l,onRetry}:{language:Language;onRetry:()=>void}) {return <button className="button secondary" onClick={onRetry}>{word(l,'重试','Retry')}</button>}
export function AccessPage({language:l}:Props) {
 const [data,setData]=useState<any>(),[rules,setRules]=useState<any[]>([]),[preview,setPreview]=useState<any>(),[notice,setNotice]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[previewError,setPreviewError]=useState(''),[checking,setChecking]=useState(false),[actor,setActor]=useState(''),[conv,setConv]=useState(''),[platform,setPlatform]=useState('QQ'),[scope,setScope]=useState('PRIVATE')
 const previewSequence=useRef(0)
 const clearPreview=()=>{previewSequence.current++;setPreview(undefined);setPreviewError('');setChecking(false)}
 const load=async()=>{setLoading(true);setError('');try{const x=await api<any>('/api/access/policy');setData(x);setRules(x.rules)}catch(e){setData(undefined);setError(apiErrorText(e,l))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const save=async()=>{if(!data||!window.confirm(word(l,'确认应用这些访问规则？修改可能阻止用户访问。','Apply these access rules? This may block users.')))return;const serverRules=Array.isArray(data.rules)?data.rules:[];if(serverRules.length>0&&rules.length===0&&!window.confirm(word(l,'这将删除全部访问规则；普通用户和群将回到默认拒绝（Default Deny）。仍要继续吗？','This will delete every access rule; ordinary users and groups will fall back to Default Deny. Continue?')))return;setBusy(true);setNotice('');setError('');try{await api('/api/access/rules',{method:'PATCH',body:JSON.stringify({revision:data.revision,rules})});clearPreview();await load();setNotice(word(l,'访问规则已更新','Access rules updated'))}catch(e){setError(apiErrorText(e,l))}finally{setBusy(false)}}
 const check=async()=>{const sequence=++previewSequence.current;setPreview(undefined);setPreviewError('');setChecking(true);try{const result=await api('/api/access/preview?'+new URLSearchParams({platform,actorId:actor,scope,conversationId:conv}));if(sequence===previewSequence.current)setPreview(result)}catch(e){if(sequence===previewSequence.current)setPreviewError(apiErrorText(e,l))}finally{if(sequence===previewSequence.current)setChecking(false)}}
 return <div className="page"><div className="page-heading"><h1>{word(l,'访问控制','Access control')}</h1></div>{loading&&<p role="status">{word(l,'正在加载','Loading')}</p>}{error&&<p id="access-error" role="alert">{error} <Retry language={l} onRetry={()=>void load()}/></p>}
 <section className="settings-section"><h2>{word(l,'所有者（恢复配置）','Owner (recovery configuration)')}</h2><p>{data?.owner.platform} · {data?.owner.stableId||word(l,'未配置','Not configured')} · {word(l,'不能在此页面修改','Read-only here')}</p><p>{word(l,'默认拒绝；普通规则拒绝优先于允许，所有者保留恢复权限；身份键使用稳定平台 ID，不使用昵称。策略读取失败时默认拒绝。','Default deny; ordinary deny rules override allow, while the owner retains recovery access. Rules use stable platform IDs, never nicknames. Policy errors fail closed.')}</p></section>
 <section className="settings-section"><h2>{word(l,'私聊与群聊访问权限','Private and group access')}</h2><p>{word(l,'先检查访问权限，再判断是否需要回复。未命中允许规则时默认拒绝（Default Deny）。','Access is checked before wake rules. If no allow rule matches, access is denied by default (Default Deny).')}</p><p>{word(l,'私聊白名单决定哪些 QQ 用户可以联系机器人；群聊白名单决定机器人可以在哪些 QQ 群工作。','Private allowlist controls which QQ users may contact the bot; group allowlist controls which QQ groups the bot may operate in.')}</p><p>{word(l,`当前规则：${rules.length}`,`Current rules: ${rules.length}`)}</p>{rules.map((r:any,i:number)=><div className="rule-row" key={`${r.scope}:${r.platform}:${r.stableId}`}><span><strong>{r.scope==='GROUP'?word(l,'群聊白名单','Group allowlist'):word(l,'私聊白名单','Private allowlist')}</strong><br/>{r.scope==='GROUP'?word(l,'QQ 群号','QQ group number'):word(l,'QQ 用户号','QQ user number')}：{r.stableId}<br/>{label(l,r.effect)}{r.updatedBy&&<small> · {word(l,'来源','Source')}：{r.updatedBy}</small>}{r.updatedAt&&<small> · {word(l,'更新时间','Updated')}: {r.updatedAt}</small>}</span><select aria-label={word(l,'规则效果 ','Rule effect ')+i} aria-describedby={error?'access-error':undefined} aria-invalid={!!error} value={r.effect} onChange={e=>setRules(rules.map((x,n)=>n===i?{...x,effect:e.target.value}:x))}>{['ALLOW','DENY'].map(v=><option key={v} value={v}>{label(l,v)}</option>)}</select><button className="button secondary" onClick={()=>{if(window.confirm(word(l,'删除后，对象将不再受这条规则影响；若没有其他允许规则，将按默认拒绝处理。确定删除？','Delete this rule? The object will no longer match it and may fall back to Default Deny.')))setRules(rules.filter((_,n)=>n!==i))}}>{word(l,'删除规则','Delete rule')}</button></div>)}<RuleAdd language={l} onAdd={r=>setRules([...rules,r])}/><button className="button primary" disabled={!data||busy} onClick={()=>void save()}>{word(l,'保存访问权限','Save access rules')}</button>{notice&&<p role="status">{notice}</p>}</section>
 <section className="settings-section"><h2>{word(l,'有效策略预览','Effective policy preview')}</h2><label>{word(l,'平台','Platform')}<select value={platform} onChange={e=>{clearPreview();setPlatform(e.target.value)}}>{['QQ','DISCORD','TELEGRAM'].map(v=><option key={v}>{v}</option>)}</select></label><label>{word(l,'用户稳定 ID','Stable user ID')}<input value={actor} aria-invalid={!!previewError} aria-describedby={previewError?'access-preview-error':undefined} onChange={e=>{clearPreview();setActor(e.target.value)}}/></label><label>{word(l,'范围','Scope')}<select value={scope} onChange={e=>{clearPreview();setScope(e.target.value)}}>{['PRIVATE','GROUP'].map(v=><option key={v} value={v}>{label(l,v)}</option>)}</select></label><label>{word(l,'会话 / 群组 ID','Conversation / group ID')}<input value={conv} aria-invalid={!!previewError} aria-describedby={previewError?'access-preview-error':undefined} onChange={e=>{clearPreview();setConv(e.target.value)}}/></label><button className="button secondary" disabled={checking} onClick={()=>void check()}>{word(l,'检查（不调用模型）','Evaluate (no model call)')}</button>{checking&&<p role="status">{word(l,'正在检查','Checking')}</p>}{previewError&&<p id="access-preview-error" role="alert">{previewError}</p>}{preview&&<p role="status">{label(l,preview.decision)} · {label(l,preview.reason)}</p>}</section></div>
}
function RuleAdd({language:l,onAdd}:{language:Language;onAdd:(r:any)=>void}) {
 const [scope,setScope]=useState('PRIVATE'),[id,setId]=useState(''),[effect,setEffect]=useState('ALLOW')
 const group=scope==='GROUP'
 return <form className="rule-add" onSubmit={e=>{e.preventDefault();onAdd({scope,platform:'QQ',stableId:id.trim(),effect});setId('')}}><label>{word(l,'规则适用范围','Rule scope')}<select value={scope} onChange={e=>setScope(e.target.value)}>{['PRIVATE','GROUP'].map(v=><option key={v} value={v}>{label(l,v)}</option>)}</select></label><label>{group?word(l,'QQ 群号（群聊 ID）','QQ group number (group ID)'):word(l,'QQ 用户号（用户 ID）','QQ user number (user ID)')}<input required maxLength={128} pattern="[A-Za-z0-9_\-]{1,128}" placeholder={group?'例如：987654321':'例如：123456789'} value={id} onChange={e=>setId(e.target.value)}/><small>{group?word(l,'填写允许机器人工作的 QQ 群号，不是群成员 QQ 号。','Enter the QQ group number where the bot may work, not a member’s QQ number.'):word(l,'填写允许私聊机器人的 QQ 账号。','Enter the QQ account allowed to contact the bot privately.')}</small></label><label>{word(l,'规则结果','Rule effect')}<select value={effect} onChange={e=>setEffect(e.target.value)}>{['ALLOW','DENY'].map(v=><option key={v} value={v}>{label(l,v)}</option>)}</select></label><button className="button secondary">{word(l,'添加访问规则','Add access rule')}</button></form>
}
export function SecurityPage({language:l}:Props) {
 const [posture,setPosture]=useState<any>(),[loadError,setLoadError]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState('')
 const load=async()=>{setLoadError('');try{setPosture(await api('/api/security/posture'))}catch(e){setLoadError(apiErrorText(e,l))}}
 useEffect(()=>{void load()},[])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setNotice('');if(next!==confirm){setError(word(l,'两次新密码不一致。','New passwords do not match.'));return}setBusy(true);try{await api('/api/security/password',{method:'POST',body:JSON.stringify({currentPassword:current,newPassword:next,confirmation:confirm})});setNotice(word(l,'密码已更新，所有旧会话均需重新登录。','Password changed. All sessions must authenticate again.'));setCurrent('');setNext('');setConfirm('')}catch(x){setError(apiErrorText(x,l))}finally{setBusy(false)}}
 return <div className="page"><div className="page-heading"><h1>{word(l,'安全中心','Security center')}</h1></div>{loadError?<p role="alert">{loadError} <Retry language={l} onRetry={()=>void load()}/></p>:!posture?<p role="status">{word(l,'正在加载','Loading')}</p>:<section className="settings-section"><h2>{word(l,'安全姿态','Security posture')}</h2><DataTable language={l} rows={Object.entries(posture).map(([name,value])=>({name:label(l,name),value:name==='hardSecurity'?word(l,'硬性安全控制不可通过控制台关闭。','Hard security controls cannot be disabled from this console.'):value}))}/><p>{word(l,'硬性安全控制不可通过控制台关闭。','Hard security controls cannot be disabled from this console.')}</p></section>}
 <section className="settings-section"><h2>{word(l,'修改管理员密码','Change administrator password')}</h2><form onSubmit={submit}><label htmlFor="current-password">{word(l,'当前密码','Current password')}</label><input id="current-password" required type="password" autoComplete="current-password" aria-invalid={!!error} aria-describedby={error?'password-error':undefined} value={current} onChange={e=>setCurrent(e.target.value)}/><label htmlFor="new-password">{word(l,'新密码（至少 14 字符）','New password (at least 14 characters)')}</label><input id="new-password" required minLength={14} type="password" autoComplete="new-password" aria-invalid={!!error} aria-describedby={error?'password-error':undefined} value={next} onChange={e=>setNext(e.target.value)}/><label htmlFor="confirm-password">{word(l,'确认新密码','Confirm new password')}</label><input id="confirm-password" required minLength={14} type="password" autoComplete="new-password" aria-invalid={!!error} aria-describedby={error?'password-error':undefined} value={confirm} onChange={e=>setConfirm(e.target.value)}/><button className="button primary" disabled={busy}>{word(l,'更新并退出所有会话','Update and invalidate sessions')}</button></form>{error&&<p id="password-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</section></div>
}
export function LogsPage({language:l}:Props) {
 const [tab,setTab]=useState<'operational'|'audit'>('operational'),[page,setPage]=useState(0),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[level,setLevel]=useState(''),[component,setComponent]=useState(''),[correlation,setCorrelation]=useState(''),[actor,setActor]=useState(''),[category,setCategory]=useState(''),[operation,setOperation]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[filterError,setFilterError]=useState(''),[filters,setFilters]=useState<Record<string,string>>({})
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setRows([]);const q=new URLSearchParams({page:String(page),size:'50'});for(const [k,v] of Object.entries(filters))if(v)q.set(k,v);void api<any>('/api/logs/'+tab+'?'+q,{signal:controller.signal}).then(x=>{if(!controller.signal.aborted)setRows(tab==='operational'?x.records:x)}).catch(e=>{if(!controller.signal.aborted)setError(apiErrorText(e,l))}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[tab,page,filters,retry,l])
 const apply=()=>{setFilterError('');if((from&&!Number.isFinite(Date.parse(from)))||(to&&!Number.isFinite(Date.parse(to)))||(from&&to&&Date.parse(from)>=Date.parse(to))){setFilterError(word(l,'请选择有效的时间范围，结束时间必须晚于起始时间。','Choose a valid range with the end after the start.'));return}const iso=(v:string)=>v?new Date(v).toISOString():'';setPage(0);setFilters(tab==='operational'?{level,component,correlationId:correlation,from:iso(from),to:iso(to)}:{actor,category,operation,from:iso(from),to:iso(to)})}
 const changeTab=(next:'operational'|'audit')=>{setTab(next);setPage(0);setFilters({})}
 return <div className="page"><div className="page-heading"><h1>{word(l,'日志与审计','Logs & audit')}</h1></div><div className="button-row"><button className="button secondary" aria-pressed={tab==='operational'} onClick={()=>changeTab('operational')}>{word(l,'运行日志','Operational logs')}</button><button className="button secondary" aria-pressed={tab==='audit'} onClick={()=>changeTab('audit')}>{word(l,'审计记录','Audit trail')}</button></div><section className="settings-section"><p>{tab==='operational'?word(l,'仅展示有界、白名单化安全事件；不读取任意日志文件。','Bounded allow-listed safe events only; no arbitrary file access.'):word(l,'审计只读、不可从控制台修改或删除。','Audit is read-only and cannot be changed or deleted here.')}</p>
 {tab==='operational'?<div className="rule-add"><label>{word(l,'等级','Level')}<select value={level} onChange={e=>setLevel(e.target.value)}><option value="">{word(l,'全部','All')}</option>{['INFO','WARN','ERROR'].map(v=><option key={v}>{v}</option>)}</select></label><label>{word(l,'组件','Component')}<select value={component} onChange={e=>setComponent(e.target.value)}><option value="">{word(l,'全部','All')}</option>{['AUTH','SECURITY','CONFIG','RUNTIME'].map(v=><option key={v}>{v}</option>)}</select></label><label>{word(l,'关联 ID','Correlation ID')}<input value={correlation} onChange={e=>setCorrelation(e.target.value)}/></label></div>:<div className="rule-add"><label>{word(l,'操作者','Actor')}<input value={actor} onChange={e=>setActor(e.target.value)}/></label><label>{word(l,'类别','Category')}<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>{word(l,'操作','Operation')}<input value={operation} onChange={e=>setOperation(e.target.value)}/></label></div>}
 <div className="rule-add"><label>{word(l,'起始时间（本地）','From (local time)')}<input type="datetime-local" aria-invalid={!!filterError} aria-describedby={filterError?'log-filter-error':undefined} value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{word(l,'结束时间（本地）','To (local time)')}<input type="datetime-local" aria-invalid={!!filterError} aria-describedby={filterError?'log-filter-error':undefined} value={to} onChange={e=>setTo(e.target.value)}/></label><button className="button secondary" onClick={apply}>{word(l,'应用筛选','Apply filters')}</button></div>{filterError&&<p id="log-filter-error" role="alert">{filterError}</p>}
 {loading?<p role="status">{word(l,'正在加载','Loading')}</p>:error?<p role="alert">{error} <Retry language={l} onRetry={()=>setRetry(retry+1)}/></p>:<DataTable language={l} rows={rows}/>}<div className="button-row"><button className="button secondary" disabled={page===0||loading} onClick={()=>setPage(page-1)}>{word(l,'上一页','Previous')}</button><span>{word(l,'第 ','Page ')}{page+1}</span><button className="button secondary" disabled={rows.length<50||loading||!!error} onClick={()=>setPage(page+1)}>{word(l,'下一页','Next')}</button></div></section></div>
}
export function OperationsPage({language:l}:Props) {
 const [data,setData]=useState<any>(),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0)
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setData(undefined);void api('/api/operations/status',{signal:controller.signal}).then(x=>{if(!controller.signal.aborted)setData(x)}).catch(e=>{if(!controller.signal.aborted)setError(apiErrorText(e,l))}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[retry,l])
 return <div className="page"><div className="page-heading"><h1>{word(l,'运行维护','Operations')}</h1></div>{loading?<p role="status">{word(l,'正在加载','Loading')}</p>:error?<p role="alert">{error} <Retry language={l} onRetry={()=>setRetry(retry+1)}/></p>:<section className="settings-section"><p>{word(l,'仅显示 XingChen 应用自身诊断；不控制宿主机。','XingChen-only diagnostics; no host controls.')}</p><DataTable language={l} rows={Object.entries(data??{}).map(([name,value])=>({name:label(l,name),value}))}/><p>{word(l,'待重连/重启状态当前未被跟踪，故显示未知；本页不提供重启按钮。','Reconnect/restart pending state is not tracked, so shown as unknown. No restart control is exposed.')}</p></section>}</div>
}
export { UsageConsolePage as UsagePage } from './UsageConsolePage'
