import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { api, ApiError, apiErrorText } from './api'
import type { MessageKey, Language } from './i18n'

type T=(key:MessageKey)=>string
type Page<TItem>={items:TItem[];total:number;page:number;size:number}
type Conversation={id:string;platform:string;type:string;platform_conversation_id:string;display_name:string;mode:string;wake_state:string;generation:number;runtime_state:string;member_count:number;last_activity?:string|null;unread_count?:number|null;unknown_count:number;interrupted_count:number;active_turn_count:number;last_read_cursor?:string|null;origin_turn_id?:string|null;waiting_since?:string|null}
type Detail=Conversation&{runtime:{waitReason:string;sleepUntil?:string|null;queueDepth:number;active:boolean;activeTurn?:Record<string,unknown>|null;interruptedTurn?:Record<string,unknown>|null;unknownOutbound:Array<Record<string,unknown>>};context:Record<string,any>;dsh:Record<string,any>;pending:Record<string,number>;members:Page<Member>;recentMessages:Page<Message>;canWake:boolean}
type Member={personId:string;platform:string;platformUserId:string;displayName:string;role:string;self:boolean;owner:boolean;lastSeen:string}
type Message={messageId:string;sender:string;senderId:string;time:string;type:string;preview:string;replyTo:string;contentKinds:string[];self:boolean}

export function ConversationsPage({t,language='zh-CN'}:{t:T;language?:Language}){
  const {id}=useParams();const [searchParams,setSearchParams]=useSearchParams();const navigate=useNavigate();
  const [query,setQuery]=useState(searchParams.get('q')??'');const [type,setType]=useState(searchParams.get('type')??'');const [mode,setMode]=useState(searchParams.get('mode')??'');const [state,setState]=useState(searchParams.get('state')??'');const [unknown,setUnknown]=useState(searchParams.get('hasUnknown')==='true');const [interrupted,setInterrupted]=useState(searchParams.get('interrupted')==='true');
  const [page,setPage]=useState(Number(searchParams.get('page')??0));const [data,setData]=useState<Page<Conversation>|null>(null);const [detail,setDetail]=useState<Detail|null>(null);const [messagePage,setMessagePage]=useState<Page<Message>|null>(null);const [messageIndex,setMessageIndex]=useState(0);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [modeValue,setModeValue]=useState('SOCIAL');const [confirmReset,setConfirmReset]=useState(false);const resetTrigger=useRef<HTMLButtonElement>(null);const resetWasOpen=useRef(false);const dialog=useRef<HTMLElement>(null);const cancel=useRef<HTMLButtonElement>(null);const pages=useMemo(()=>Math.max(1,Math.ceil((data?.total??0)/20)),[data?.total]);
  const filterPath=()=>{const params=new URLSearchParams();if(query.trim())params.set('q',query.trim());if(type)params.set('type',type);if(mode)params.set('mode',mode);if(state)params.set('state',state);if(unknown)params.set('hasUnknown','true');if(interrupted)params.set('interrupted','true');if(page>0)params.set('page',String(page));return params.toString()}
  const loadList=async()=>{setLoading(true);setNotice('');try{const params=new URLSearchParams(filterPath());params.set('size','20');const result=await api<Page<Conversation>>(`/api/conversations?${params}`);setData(result)}catch(error){setNotice(error instanceof ApiError&&error.status===409?t('conversationConflict'):t('offline'))}finally{setLoading(false)}}
  const loadDetail=async(conversationId:string)=>{setLoading(true);setNotice('');try{const [value,messages]=await Promise.all([api<Detail>(`/api/conversations/${conversationId}`),api<Page<Message>>(`/api/conversations/${conversationId}/messages?page=${messageIndex}&size=20`)]);setDetail(value);setModeValue(value.mode);setMessagePage(messages)}catch(error){setDetail(null);setNotice(error instanceof ApiError&&error.status===409?t('conversationConflict'):t('offline'))}finally{setLoading(false)}}
  useEffect(()=>{void loadList()},[query,type,mode,state,unknown,interrupted,page])
  useEffect(()=>{if(id){setMessageIndex(0);void loadDetail(id)}else{setDetail(null);setMessagePage(null)}},[id])
  useEffect(()=>{if(id&&messageIndex>0)void loadDetail(id)},[messageIndex])
  useEffect(()=>{if(confirmReset){cancel.current?.focus();resetWasOpen.current=true}else if(resetWasOpen.current){resetTrigger.current?.focus();resetWasOpen.current=false}},[confirmReset])
  const applyFilters=(event:React.FormEvent)=>{event.preventDefault();setPage(0);setSearchParams(filterPath()?Object.fromEntries(new URLSearchParams(filterPath())):{})}
  const open=(item:Conversation)=>{setSearchParams(filterPath()?Object.fromEntries(new URLSearchParams(filterPath())):{});navigate(`/conversations/${item.id}${filterPath()?`?${filterPath()}`:''}`)}
  const refresh=()=>id?void loadDetail(id):void loadList()
  const mutate=async(action:'mode'|'wake'|'reset')=>{if(!detail)return;setBusy(true);setNotice('');try{const path=`/api/conversations/${detail.id}/${action}`;const options:RequestInit=action==='mode'?{method:'PATCH',body:JSON.stringify({mode:modeValue,expectedGeneration:detail.generation})}:{method:'POST',body:JSON.stringify({expectedGeneration:detail.generation})};await api(path,options);setConfirmReset(false);await loadDetail(detail.id);await loadList();setNotice(action==='reset'?t('resetDone'):action==='wake'?t('wakeDone'):t('modeDone'))}catch(error){if(error instanceof ApiError&&error.status===409){await loadDetail(detail.id);setNotice(t('conversationConflict'))}else setNotice(apiErrorText(error,language))}finally{setBusy(false)}}
  const trap=(event:React.KeyboardEvent<HTMLElement>)=>{if(event.key==='Escape'){event.preventDefault();setConfirmReset(false);return}if(event.key!=='Tab')return;const buttons=dialog.current?.querySelectorAll<HTMLButtonElement>('button:not([disabled])');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
  return <div className={`page conversations-page ${id?'detail-open':''}`}>
    <div className="page-heading"><div><p className="eyebrow">{t('social')}</p><h1>{t('conversations')}</h1></div><button className="button secondary" onClick={refresh}>{t('retry')}</button></div>
    <form className="conversation-filters" onSubmit={applyFilters} aria-label={t('conversationFilters')}>
      <label>{t('conversationSearch')}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('conversationSearchHint')} /></label>
      <label>{t('conversationType')}<select value={type} onChange={e=>{setType(e.target.value);setPage(0)}}><option value="">{t('all')}</option><option value="PRIVATE">{t('private')}</option><option value="GROUP">{t('group')}</option></select></label>
      <label>{t('conversationMode')}<select value={mode} onChange={e=>{setMode(e.target.value);setPage(0)}}><option value="">{t('all')}</option><option value="SOCIAL">{t('socialMode')}</option><option value="CLOSED_AGENT">{t('closedMode')}</option></select></label>
      <label>{t('runtimeState')}<select value={state} onChange={e=>{setState(e.target.value);setPage(0)}}><option value="">{t('all')}</option><option value="ACTIVE">{t('active')}</option><option value="WAITING">{t('waiting')}</option><option value="SLEEPING">{t('sleeping')}</option></select></label>
      <label className="check-filter"><input type="checkbox" checked={unknown} onChange={e=>{setUnknown(e.target.checked);setPage(0)}} />{t('hasUnknown')}</label>
      <label className="check-filter"><input type="checkbox" checked={interrupted} onChange={e=>{setInterrupted(e.target.checked);setPage(0)}} />{t('hasInterrupted')}</label>
    </form>
    {notice&&<p role="status" className="notice">{notice}</p>}
    <div className="conversation-workspace">
      <section className="conversation-list-panel" aria-label={t('conversationList')}>
        {loading&&!data?<FeedbackText t={t}/>:!data?.items.length?<p className="empty-state">{t('noData')}</p>:data.items.map(item=><button type="button" className={`conversation-item ${id===item.id?'selected':''}`} key={item.id} onClick={()=>open(item)} aria-current={id===item.id?'page':undefined}>
          <span className="conversation-item-head"><strong>{item.display_name}</strong><span className="state-badge">{stateLabel(t,item.runtime_state)}</span></span>
          <span className="conversation-meta">{item.type==='GROUP'?t('group'):t('private')} · {item.platform} · {item.platform_conversation_id}</span>
          <span className="conversation-meta">{item.mode} · {item.member_count} {t('members')} · {formatTime(item.last_activity)}</span>
          <span className="conversation-flags">{item.runtime_state==='WAITING'&&<span className="state-badge">{t('waiting')}</span>}{item.unknown_count>0&&<span className="state-badge warning">{t('unknown')}</span>}{item.interrupted_count>0&&<span className="state-badge danger">{t('interrupted')}</span>}{item.active_turn_count>0&&<span className="state-badge">{t('activeTurn')}</span>}<span>{t('generationLabel')} {item.generation} · {t('unreadLabel')} {item.unread_count??'—'}</span></span>
        </button>)}
        {data&&<div className="pagination"><span>{data.total} · {page+1}/{pages}</span><button className="button secondary" disabled={page===0||loading} onClick={()=>setPage(Math.max(0,page-1))}>{t('previous')}</button><button className="button secondary" disabled={page+1>=pages||loading} onClick={()=>setPage(page+1)}>{t('next')}</button></div>}
      </section>
      <section className="conversation-detail-panel" aria-live="polite">
        {!id?<div className="empty-state">{t('selectConversation')}</div>:loading&&!detail?<FeedbackText t={t}/>:!detail?<div role="alert" className="empty-state">{t('offline')}</div>:<>
          <div className="detail-heading"><div><p className="eyebrow">{detail.platform} · {detail.type}</p><h2>{detail.display_name}</h2><p className="conversation-meta">{t('platformConversationId')}: {detail.platform_conversation_id}</p></div><Link className="button secondary back-to-list" to={`/conversations${locationSearch(searchParams)}`}>{t('backToList')}</Link></div>
          <section className="detail-section"><div className="social-section-head"><h3>{t('runtimeDiagnostics')}</h3><Link className="button secondary" to={`/social-settings?conversation=${encodeURIComponent(detail.id)}`}>{t('socialSettings')}</Link></div><div className="detail-grid"><Info label={t('conversationMode')} value={detail.mode}/><Info label={t('runtimeState')} value={stateLabel(t,detail.runtime_state)}/><Info label={t('generationLabel')} value={String(detail.generation)}/><Info label={t('queue')} value={`${detail.runtime.queueDepth} · ${detail.runtime.active?t('busy'):t('idle')}`}/><Info label={t('cursor')} value={detail.last_read_cursor??'—'}/><Info label={t('unreadLabel')} value={detail.context.unreadCount==null?'—':String(detail.context.unreadCount)}/>{detail.waiting_since&&<Info label={t('waitingSince')} value={formatTime(detail.waiting_since)}/ >}{detail.origin_turn_id&&<Info label={t('originTurn')} value={short(detail.origin_turn_id)}/>}</div>{detail.runtime.waitReason&&<p className="quiet-note">{t('waitReason')}: {detail.runtime.waitReason}</p>}
            {detail.runtime.activeTurn&&<p className="quiet-note">{t('activeTurn')}: {String(detail.runtime.activeTurn.turnId)} · {String(detail.runtime.activeTurn.executionState)} · {String(detail.runtime.activeTurn.startedAt)}</p>}
            {detail.runtime.interruptedTurn&&<div className="notice-box danger"><strong>{t('recoveryRequired')}</strong><p>{t('interruptedDetails')}: {String(detail.runtime.interruptedTurn.turnId)} · {String(detail.runtime.interruptedTurn.executionState)} · {String(detail.runtime.interruptedTurn.updatedAt)}</p><p>{String(detail.runtime.interruptedTurn.reason)}</p></div>}
            {detail.runtime.unknownOutbound.length>0&&<div className="notice-box warning"><strong>{t('unknownNoRetry')}</strong>{detail.runtime.unknownOutbound.map((out,index)=><p key={index}>{String(out.logicalMessageId)} · {String(out.turnId)} · {formatTime(String(out.timestamp))} · {String(out.status)}</p>)}</div>}
          </section>
          <section className="detail-section"><h3>{t('contextDiagnostics')}</h3><div className="detail-grid"><Info label={t('currentEstimate')} value={`${detail.context.currentEstimate??0} tokens`}/><Info label={t('thresholds')} value={`soft ${detail.context.thresholds?.soft??'—'} · rollover ${detail.context.thresholds?.rollover??'—'} · hard ${detail.context.thresholds?.hard??'—'}`}/><Info label={t('contextLifecycle')} value={detail.context.lifecycleState??'UNKNOWN'}/><Info label={t('recentCount')} value={String(detail.context.recentMessageCount??0)}/><Info label={t('lastRollover')} value={formatTime(detail.context.session?.lastRolloverAt)}/><Info label={t('handoff')} value={detail.context.handoff?.status??'NONE'}/><Info label={t('dshMapping')} value={detail.dsh.mappingExists?`${detail.dsh.status} · ${detail.dsh.sessionId}`:t('none')}/><Info label={t('pendingInteractions')} value={`${t('questions')}: ${detail.pending.questions??0} · ${t('approvals')}: ${detail.pending.approvals??0}`}/></div></section>
          <section className="detail-section"><h3>{t('members')} · {detail.members.total}</h3><div className="member-list">{detail.members.items.map(member=><div className="member-row" key={member.personId}><Link to={`/people/${member.personId}`}><strong>{member.displayName}</strong></Link><span>{member.role}</span><small>{member.platformUserId} · {formatTime(member.lastSeen)}</small></div>)}</div><Link to={`/memory?conversation=${detail.id}`}>{t('memory')}</Link></section>
          <section className="detail-section"><h3>{t('recentMessages')}</h3><p className="quiet-note">{t('messagePrivacy')}</p><div className="message-list">{messagePage?.items.map(message=><article className="message-row" key={message.messageId}><header><strong>{message.sender}</strong><span>{message.type}</span><time>{formatTime(message.time)}</time></header><p>{message.preview||`[${message.contentKinds.join(', ')}]`}</p>{message.replyTo&&<small>{t('replyTo')}: {message.replyTo}</small>}</article>)}</div><div className="pagination"><span>{messagePage?.total??0}</span><button className="button secondary" disabled={messageIndex===0||loading} onClick={()=>setMessageIndex(Math.max(0,messageIndex-1))}>{t('previous')}</button><button className="button secondary" disabled={!messagePage||((messageIndex+1)*20>=messagePage.total)||loading} onClick={()=>setMessageIndex(messageIndex+1)}>{t('next')}</button></div></section>
          <section className="detail-section operations-section"><h3>{t('operations')}</h3><div className="mode-operation"><label htmlFor="conversation-mode">{t('conversationMode')}</label><select id="conversation-mode" value={modeValue} onChange={e=>setModeValue(e.target.value)}><option value="SOCIAL">{t('socialMode')}</option><option value="CLOSED_AGENT">{t('closedMode')}</option></select><button className="button secondary" disabled={busy||modeValue===detail.mode} onClick={()=>void mutate('mode')}>{t('saveMode')}</button></div><div className="operation-buttons"><button className="button secondary" disabled={busy||!detail.canWake||detail.wake_state==='WAITING'} onClick={()=>void mutate('wake')}>{t('manualWake')}</button><button ref={resetTrigger} className="button danger-button" disabled={busy} onClick={()=>setConfirmReset(true)}>{t('resetConversation')}</button></div><p className="quiet-note">{detail.wake_state==='WAITING'?t('waitingResetOnly'):t('ownerWakeOnly')}</p></section>
        </>}
      </section>
    </div>
    {confirmReset&&<div className="dialog-scrim"><section ref={dialog} className="dialog reset-dialog" role="alertdialog" aria-modal="true" aria-labelledby="reset-title" aria-describedby="reset-description" tabIndex={-1} onKeyDown={trap}><h2 id="reset-title">{t('resetConversation')}</h2><p id="reset-description">{t('resetWarning')}</p><ul><li>{t('resetEffectTransient')}</li><li>{t('resetEffectGeneration')}</li><li>{t('resetEffectDsh')}</li><li>{t('resetPreserveLongTerm')}</li></ul><div className="dialog-actions"><button ref={cancel} className="button secondary" disabled={busy} onClick={()=>setConfirmReset(false)}>{t('cancel')}</button><button className="button danger-button" disabled={busy} onClick={()=>void mutate('reset')}>{busy?t('working'):t('confirm')}</button></div></section></div>}
  </div>
}
function FeedbackText({t}:{t:T}){return <div className="empty-state" role="status">{t('loading')}</div>}
function Info({label,value}:{label:string;value:string}){return <div className="info-cell"><span>{label}</span><strong>{value||'—'}</strong></div>}
function stateLabel(t:T,state:string){const key=state==='WAITING'?'waiting':state==='ACTIVE'?'active':'sleeping';return t(key)}
function formatTime(value?:string|null){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.valueOf())?value:date.toLocaleString()}
function short(value:string){return value.length>12?`${value.slice(0,8)}…`:value}
function locationSearch(params:URLSearchParams){const value=params.toString();return value?`?${value}`:''}
