import { useCallback, useEffect, useState } from 'react'
import { ApiError, api, apiErrorText } from './api'
import type { Language } from './i18n'

type Provider={providerId:string;providerType:string;revision:number;enabled:boolean;configured:boolean;baseUrl:string;model:string;maxOutputTokens:number;timeoutMillis:number;supportedOptions:string[];reasoningEffortSupported:boolean;reasoningEfforts:string[];runtimeStatus:string;applyMode:string;lastTest:{status:string;summary:string;testedAt?:string}}
type State={providers:Provider[]}
export function ModelsPage({language}:{language:Language}){
  const zh=language==='zh-CN';const [provider,setProvider]=useState<Provider|null>(null);const [draft,setDraft]=useState<Partial<Provider>>({});const [credential,setCredential]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [mutationError,setMutationError]=useState('');
  const text=zh?{title:'模型管理',intro:'管理当前已实现的模型 Provider。Agent transport（例如 DSH）不是 Model Provider。',provider:'DeepSeek 官方 Provider',kind:'模型 Provider',enabled:'启用 Provider',configured:'凭据状态',set:'设置 / 替换 API Key',credential:'API Key（仅提交时保存在受限 SecretStore）',saveCredential:'保存凭据',clearCredential:'清除凭据',model:'模型 ID',url:'Base URL',output:'最大输出 tokens',timeout:'请求超时（毫秒）',save:'保存配置',test:'测试 Provider 连接',testCost:'测试会发送一条最小的真实 Provider 请求，可能产生少量费用；自动化测试使用 Fake Provider。',reasoning:'Reasoning effort',unsupported:'当前 DeepSeek 适配器不支持 reasoning effort；不会保存无效选项。',status:'运行状态',last:'最近连接测试',configuredYes:'已配置',configuredNo:'未配置',success:'成功',auth:'认证失败',unreachable:'无法访问',timeoutState:'超时',invalid:'配置无效',notSupported:'不支持',disabled:'已关闭',ready:'可用',missing:'缺少凭据',warning:'远端地址仅允许 HTTPS 与可公开路由的主机；本地测试配置只允许 loopback HTTP。禁止跳转，错误摘要不返回响应正文。',saved:'配置已保存并热应用于新回合。',conflict:'配置已被其他管理员修改，请刷新后重试。',retry:'重试',offline:'模型配置暂时无法读取。',runtime:'配置修改为 HOT_APPLY；已经执行的回合保留其 Provider / model / credential 快照。',testSuccess:'Provider 接受了最小测试请求。'}:{title:'Model management',intro:'Manage the model providers actually implemented here. Agent transports such as DSH are not model providers.',provider:'Official DeepSeek provider',kind:'Model provider',enabled:'Enable provider',configured:'Credential status',set:'Set / replace API key',credential:'API key (submitted only to the restricted SecretStore)',saveCredential:'Save credential',clearCredential:'Clear credential',model:'Model ID',url:'Base URL',output:'Maximum output tokens',timeout:'Request timeout (milliseconds)',save:'Save configuration',test:'Test provider connection',testCost:'Testing sends one minimal live provider request and may incur a small charge; automated tests use a Fake Provider.',reasoning:'Reasoning effort',unsupported:'The current DeepSeek adapter does not support reasoning effort; unsupported options are not stored.',status:'Runtime status',last:'Last connection test',configuredYes:'Configured',configuredNo:'Not configured',success:'Success',auth:'Authentication failed',unreachable:'Unreachable',timeoutState:'Timed out',invalid:'Invalid configuration',notSupported:'Unsupported',disabled:'Disabled',ready:'Ready',missing:'Credential missing',warning:'Remote targets require HTTPS and publicly routable hosts; local test settings may use loopback HTTP only. Redirects are disabled and response bodies are not returned.',saved:'Configuration saved and hot-applied for new turns.',conflict:'Configuration changed elsewhere. Refresh before retrying.',retry:'Retry',offline:'Model configuration is temporarily unavailable.',runtime:'Changes use HOT_APPLY; in-flight turns retain their Provider / model / credential snapshot.',testSuccess:'Provider accepted the minimal test request.'};
  const load=useCallback(async()=>{setError('');try{const data=await api<State>('/api/models/providers');const p=data.providers[0]??null;setProvider(p);if(p)setDraft({enabled:p.enabled,baseUrl:p.baseUrl,model:p.model,maxOutputTokens:p.maxOutputTokens,timeoutMillis:p.timeoutMillis})}catch{setError(text.offline)}},[text.offline]);
  useEffect(()=>{void load()},[load]);
  const save=async()=>{if(!provider)return;setBusy(true);setNotice('');setMutationError('');try{const result=await api<Provider>('/api/models/providers/deepseek/config',{method:'PATCH',body:JSON.stringify({expectedRevision:provider.revision,values:draft})});setProvider(result);setDraft({enabled:result.enabled,baseUrl:result.baseUrl,model:result.model,maxOutputTokens:result.maxOutputTokens,timeoutMillis:result.timeoutMillis});setNotice(text.saved)}catch(cause){if(cause instanceof ApiError&&cause.status===409){await load();setNotice(text.conflict)}else setMutationError(apiErrorText(cause,language))}finally{setBusy(false)}};
  const setSecret=async()=>{if(!credential)return;const value=credential;setCredential('');setBusy(true);setNotice('');setMutationError('');try{await api('/api/models/providers/deepseek/credential',{method:'POST',body:JSON.stringify({value})});await load();setNotice(text.saved)}catch(cause){setMutationError(apiErrorText(cause,language))}finally{setBusy(false)}};
  const clearSecret=async()=>{setCredential('');setBusy(true);try{await api('/api/models/providers/deepseek/credential',{method:'DELETE'});await load();setNotice(text.saved)}catch(cause){setMutationError(apiErrorText(cause,language))}finally{setBusy(false)}};
  const test=async()=>{setBusy(true);setNotice('');setMutationError('');setProvider(p=>p?({...p,lastTest:{status:'NOT_TESTED',summary:''}}):p);try{const result=await api<{status:string;summary:string}>('/api/models/providers/deepseek/test',{method:'POST'});await load();setNotice(labelStatus(result.status))}catch(cause){setMutationError(apiErrorText(cause,language))}finally{setBusy(false)}};
  const labelStatus=(status:string)=>({SUCCESS:text.success,AUTH_FAILED:text.auth,UNREACHABLE:text.unreachable,TIMEOUT:text.timeoutState,INVALID_CONFIG:text.invalid,UNSUPPORTED:text.notSupported,NOT_TESTED:zh?'尚未测试':'Not tested'}[status]??status);
  if(error)return <main className="page model-page"><h1>{text.title}</h1><p role="alert">{error}</p><button className="button secondary" onClick={()=>void load()}>{text.retry}</button></main>;
  if(!provider)return <main className="page model-page"><h1>{text.title}</h1><p role="status">…</p></main>;
  return <main className="page model-page"><div className="page-heading"><div><p className="eyebrow">{zh?'推理运行时':'Inference runtime'}</p><h1>{text.title}</h1><p>{text.intro}</p></div><span className={`status-pill ${provider.runtimeStatus==='READY'?'':'neutral'}`}>{provider.runtimeStatus==='READY'?text.ready:provider.runtimeStatus==='DISABLED'?text.disabled:provider.runtimeStatus==='MISSING_CREDENTIAL'?text.missing:provider.runtimeStatus}</span></div>
    {mutationError&&<p id="model-error" role="alert">{mutationError}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
    <section className="settings-section"><div className="model-title"><div><h2>{text.provider}</h2><p className="quiet-note">{text.kind} · {provider.providerId} · {provider.applyMode}</p></div><span className={`status-pill ${provider.configured?'':'neutral'}`}>{text.configured}: {provider.configured?text.configuredYes:text.configuredNo}</span></div>
      <label className="social-check"><input aria-invalid={!!mutationError} aria-describedby={mutationError?'model-error':undefined} type="checkbox" checked={Boolean(draft.enabled)} onChange={e=>setDraft(v=>({...v,enabled:e.target.checked}))}/><span>{text.enabled}</span></label>
      <div className="model-form-grid"><label>{text.url}<input aria-invalid={!!mutationError} aria-describedby={mutationError?'model-error':undefined} aria-label={text.url} autoComplete="url" value={String(draft.baseUrl??'')} onChange={e=>setDraft(v=>({...v,baseUrl:e.target.value}))}/></label><label>{text.model}<input aria-invalid={!!mutationError} aria-describedby={mutationError?'model-error':undefined} aria-label={text.model} maxLength={128} value={String(draft.model??'')} onChange={e=>setDraft(v=>({...v,model:e.target.value}))}/></label><label>{text.output}<input aria-invalid={!!mutationError} aria-describedby={mutationError?'model-error':undefined} aria-label={text.output} type="number" min="1" max="8192" step="1" value={Number(draft.maxOutputTokens??1024)} onChange={e=>setDraft(v=>({...v,maxOutputTokens:Number(e.target.value)}))}/></label><label>{text.timeout}<input aria-invalid={!!mutationError} aria-describedby={mutationError?'model-error':undefined} aria-label={text.timeout} type="number" min="1000" max="120000" step="1000" value={Number(draft.timeoutMillis??60000)} onChange={e=>setDraft(v=>({...v,timeoutMillis:Number(e.target.value)}))}/></label></div>
      <div className="model-secret"><label>{text.credential}<input aria-invalid={!!mutationError} aria-describedby={mutationError?'model-error':undefined} aria-label={text.credential} type="password" autoComplete="new-password" value={credential} onChange={e=>setCredential(e.target.value)} /></label><div className="social-button-row"><button className="button primary" disabled={busy||!credential} onClick={()=>void setSecret()}>{text.saveCredential}</button><button className="button secondary" disabled={busy||!provider.configured} onClick={()=>void clearSecret()}>{text.clearCredential}</button></div></div>
      <div className="settings-section model-capability"><h3>{text.reasoning}</h3><p>{text.unsupported}</p><small>{zh?'Provider 能力：':'Provider capability: '}{provider.reasoningEffortSupported?(zh?'支持':'Supported'):(zh?'不支持':'Unsupported')}</small></div>
      <div className="notice-box warning">{text.warning}</div><p className="quiet-note">{text.runtime}</p><button className="button primary" disabled={busy} onClick={()=>void save()}>{text.save}</button>
    </section>
    <section className="settings-section"><h2>{text.test}</h2><p>{text.testCost}</p><button className="button secondary" disabled={busy||!provider.configured} onClick={()=>void test()}>{text.test}</button><div className="model-test-result" aria-live="polite"><strong>{text.last}:</strong> <span>{labelStatus(provider.lastTest.status)}</span><p>{provider.lastTest.status==='SUCCESS'?text.testSuccess:labelStatus(provider.lastTest.status)}</p>{provider.lastTest.testedAt&&<small>{provider.lastTest.testedAt}</small>}</div></section>
  </main>
}
