import { useCallback, useEffect, useState } from 'react'
import { ApiError, api, apiErrorText } from './api'
import type { Language } from './i18n'

type Entry={id:string;term:string;meaning:string;status:'CANDIDATE'|'CONFIRMED'|'REJECTED';source:string;sources:string[];evidenceCount:number;evidencePreview:string[];createdAt:string;updatedAt:string}
type Page={items:Entry[];total:number;page:number;pageSize:number;webResearch:string}
export function SlangPage({language}:{language:Language}){
  const zh=language==='zh-CN';const t=zh?{title:'俚语审核',intro:'离线管理候选词、已确认词和拒绝词。查看页面不会联网研究。聊天证据仅展示脱敏短摘要。',search:'搜索词条与释义',status:'状态',all:'全部',candidate:'待审核',confirmed:'已确认',rejected:'已拒绝',term:'词条',meaning:'释义',source:'来源',evidence:'证据摘要',last:'最近更新',confirm:'确认',reject:'拒绝',edit:'编辑释义',save:'保存释义',manual:'手动添加词条',create:'添加候选词',saved:'已保存',created:'已添加为人工候选词',none:'没有匹配的词条。',research:'网络研究：关闭',private:'证据不会完整显示，也不会写入管理审计。',conflict:'条目已被其他管理员修改，请刷新后重试。',error:'俚语数据暂时不可用。'}:{title:'Slang review',intro:'Review candidate, confirmed and rejected terms offline. Opening this page never triggers web research. Chat evidence is shown only as a redacted short excerpt.',search:'Search terms and meanings',status:'Status',all:'All',candidate:'Candidate',confirmed:'Confirmed',rejected:'Rejected',term:'Term',meaning:'Meaning',source:'Source',evidence:'Evidence summary',last:'Last updated',confirm:'Confirm',reject:'Reject',edit:'Edit meaning',save:'Save meaning',manual:'Add manually',create:'Add candidate',saved:'Saved',created:'Added as a manual candidate',none:'No matching slang entries.',research:'Web research: disabled',private:'Evidence is never shown in full or copied to administration audit.',conflict:'Entry changed elsewhere. Refresh and retry.',error:'Slang data is temporarily unavailable.'}
  const [data,setData]=useState<Page|null>(null),[q,setQ]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(0),[term,setTerm]=useState(''),[meaning,setMeaning]=useState(''),[editId,setEditId]=useState(''),[editMeaning,setEditMeaning]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')
  const load=useCallback(async()=>{setError('');try{setData(await api<Page>(`/api/slang/admin?q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}&page=${page}&size=20`))}catch{setError(t.error)}},[q,status,page,t.error]);useEffect(()=>{void load()},[load])
  const create=async()=>{setBusy(true);setNotice('');try{await api<Entry>('/api/slang/admin',{method:'POST',body:JSON.stringify({term,meaning})});setTerm('');setMeaning('');setStatus('CANDIDATE');setPage(0);setNotice(t.created);await load()}catch(cause){setNotice(apiErrorText(cause,language))}finally{setBusy(false)}}
  const mutate=async(entry:Entry,action:'CONFIRM'|'REJECT'|'MEANING')=>{setBusy(true);setNotice('');try{await api<Entry>(`/api/slang/admin/${entry.id}`,{method:'PATCH',body:JSON.stringify({expectedUpdatedAt:entry.updatedAt,action:action==='MEANING'?'':action,meaning:action==='MEANING'?editMeaning:undefined})});setEditId('');setNotice(t.saved);await load()}catch(cause){if(cause instanceof ApiError&&cause.status===409){setNotice(t.conflict);await load()}else setNotice(apiErrorText(cause,language))}finally{setBusy(false)}}
  if(error)return <main className="page media-page"><h1>{t.title}</h1><p role="alert">{error}</p><button className="button secondary" onClick={()=>void load()}>{zh?'重试':'Retry'}</button></main>
  return <main className="page media-page slang-page"><div className="page-heading"><div><p className="eyebrow">{zh?'离线词库':'Offline dictionary'}</p><h1>{t.title}</h1><p>{t.intro}</p></div></div>{notice&&<p role="status" className="notice">{notice}</p>}
    <section className="settings-section slang-create"><h2>{t.manual}</h2><label>{t.term}<input aria-label={t.term} maxLength={80} value={term} onChange={e=>setTerm(e.target.value)}/></label><label>{t.meaning}<textarea aria-label={t.meaning} maxLength={500} rows={2} value={meaning} onChange={e=>setMeaning(e.target.value)}/></label><button className="button primary" disabled={busy||!term.trim()||!meaning.trim()} onClick={()=>void create()}>{t.create}</button></section>
    <section className="settings-section slang-list"><div className="media-toolbar"><label>{t.search}<input aria-label={t.search} value={q} onChange={e=>{setQ(e.target.value);setPage(0)}}/></label><label>{t.status}<select aria-label={t.status} value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="">{t.all}</option><option value="CANDIDATE">{t.candidate}</option><option value="CONFIRMED">{t.confirmed}</option><option value="REJECTED">{t.rejected}</option></select></label></div><p className="quiet-note">{t.research} · {t.private}</p>
      <div className="slang-table-wrap"><table className="slang-table"><thead><tr><th>{t.term}</th><th>{t.meaning}</th><th>{t.status}</th><th>{t.source}</th><th>{t.evidence}</th><th>{t.last}</th><th>{zh?'操作':'Actions'}</th></tr></thead><tbody>{data?.items.map(entry=><tr key={entry.id}><th scope="row">{entry.term}</th><td>{editId===entry.id?<><textarea aria-label={`${t.edit}: ${entry.term}`} rows={2} maxLength={500} value={editMeaning} onChange={e=>setEditMeaning(e.target.value)}/><button className="button secondary" disabled={busy} onClick={()=>void mutate(entry,'MEANING')}>{t.save}</button></>:entry.meaning}</td><td><span className={`slang-status ${entry.status.toLowerCase()}`}>{entry.status==='CANDIDATE'?t.candidate:entry.status==='CONFIRMED'?t.confirmed:t.rejected}</span></td><td>{entry.source||entry.sources.join(', ')||'—'}</td><td>{entry.evidenceCount? <details><summary>{entry.evidenceCount} · {t.evidence}</summary><ul>{entry.evidencePreview.map((e,i)=><li key={`${entry.id}-${i}`}>{e}</li>)}</ul></details>:'—'}</td><td>{entry.updatedAt}</td><td><div className="slang-actions">{entry.status==='CANDIDATE'&&<><button className="button secondary" disabled={busy} onClick={()=>void mutate(entry,'CONFIRM')}>{t.confirm}</button><button className="button secondary danger-button" disabled={busy} onClick={()=>{if(window.confirm(zh?'拒绝该候选词？':'Reject this candidate?'))void mutate(entry,'REJECT')}}>{t.reject}</button></>}<button className="button secondary" disabled={busy} onClick={()=>{setEditId(entry.id);setEditMeaning(entry.meaning)}}>{t.edit}</button></div></td></tr>)}</tbody></table>{data?.items.length===0&&<p>{t.none}</p>}</div>
      <nav className="media-pagination" aria-label={zh?'俚语分页':'Slang pagination'}><button className="button secondary" disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))}>{zh?'上一页':'Previous'}</button><span>{page+1} / {Math.max(1,Math.ceil((data?.total??0)/(data?.pageSize??20)))}</span><button className="button secondary" disabled={!data||((page+1)*data.pageSize>=data.total)} onClick={()=>setPage(p=>p+1)}>{zh?'下一页':'Next'}</button></nav>
    </section>
  </main>
}
