import { useCallback, useEffect, useState } from 'react'
import { ApiError, api, apiErrorText } from './api'
import type { Language } from './i18n'

type Sticker={id:string;path:string;sha256:string;tags:string[];note:string;usageCount:number;source:string;createdAt:string;lastUsedAt?:string;fileName:string;mimeType:string;fileSize:number;width?:number;height?:number;animated?:boolean;enabled:boolean;updatedAt:string}
type Page={items:Sticker[];total:number;page:number;pageSize:number;maxFileBytes:number;sendTest:string;formats:Record<string,{mimeType:string;importSupported:boolean;previewSupported:boolean;sendSupported:boolean}>}
export function StickersPage({language}:{language:Language}){
  const zh=language==='zh-CN';const t=zh?{title:'表情管理',intro:'文件保存在配置的 sticker 目录中，SQLite 只存元数据。扫描和上传都只导入安全目录内的本地图片。',scan:'扫描 / 导入',upload:'上传图片',search:'搜索文件名、标签或备注',format:'格式',enabled:'启用状态',all:'全部',yes:'已启用',no:'已停用',animated:'仅动画',tags:'标签（逗号分隔）',note:'使用备注',save:'保存元数据',saved:'已保存',empty:'没有匹配的表情。可扫描已配置目录，或上传一张图片。',unsupported:'本页不提供测试发送：当前只有 Agent 回合具备安全 outbound ledger / conversation policy 路径，没有管理员测试发送安全入口。',scanDone:'扫描完成',uploadDone:'上传完成',invalid:'文件格式、内容或大小无效。',error:'表情资源暂时不可用。',showing:'条目',preview:'预览',metadata:'元数据',disabled:'已停用的项目仍可在管理页查看，但 Agent 搜索不会返回它。',sendPath:'OneBot 图片发送接口：适配器可调用；最终格式支持取决于网关。',supported:'支持',unsupportedLabel:'不支持',unknown:'UNKNOWN 投递结果不会自动重试。'}:{title:'Stickers',intro:'Files remain in the configured sticker asset directory; SQLite stores metadata only. Scan and upload import local images through the bounded asset pipeline.',scan:'Scan / import',upload:'Upload image',search:'Search filename, tags or note',format:'Format',enabled:'Enabled',all:'All',yes:'Enabled',no:'Disabled',animated:'Animated only',tags:'Tags (comma-separated)',note:'Usage note',save:'Save metadata',saved:'Saved',empty:'No stickers match. Scan the configured directory or upload an image.',unsupported:'Send testing is unavailable here: only Agent turns have the safe outbound ledger / conversation policy path; no admin test-send path exists.',scanDone:'Scan completed',uploadDone:'Upload completed',invalid:'File type, content or size is invalid.',error:'Sticker assets are temporarily unavailable.',showing:'items',preview:'Preview',metadata:'Metadata',disabled:'Disabled assets remain visible here but are excluded from Agent search.',sendPath:'OneBot image-send adapter is available; final format acceptance depends on the gateway.',supported:'Supported',unsupportedLabel:'Unsupported',unknown:'UNKNOWN delivery is never retried automatically.'};
  const [data,setData]=useState<Page|null>(null),[q,setQ]=useState(''),[format,setFormat]=useState(''),[enabled,setEnabled]=useState(''),[onlyAnimated,setOnlyAnimated]=useState(false),[page,setPage]=useState(0),[selected,setSelected]=useState<Sticker|null>(null),[tags,setTags]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null)
  const formatNames=Object.keys(data?.formats??{}).sort()
  const load=useCallback(async()=>{setError('');try{const p=await api<Page>(`/api/stickers/admin?q=${encodeURIComponent(q)}&format=${encodeURIComponent(format)}&page=${page}&size=24${enabled?`&enabled=${enabled}`:''}${onlyAnimated?'&animated=true':''}`);setData(p);setSelected(old=>old?p.items.find(s=>s.id===old.id)??null:null)}catch{setError(t.error)}},[q,format,page,enabled,onlyAnimated,t.error]);useEffect(()=>{void load()},[load]);
  const choose=(item:Sticker)=>{setSelected(item);setTags(item.tags.join(', '));setNote(item.note)}
  const scan=async()=>{setBusy(true);setNotice('');try{const result=await api<{imported:number;duplicates:number;skipped:number;truncated:boolean}>('/api/stickers/admin/scan',{method:'POST'});setNotice(`${t.scanDone}: ${result.imported} · ${zh?'重复':'duplicates'} ${result.duplicates} · ${zh?'跳过':'skipped'} ${result.skipped}${result.truncated?' · …':''}`);await load()}catch{setNotice(t.error)}finally{setBusy(false)}}
  const upload=async()=>{if(!file)return;setBusy(true);setNotice('');try{const body=new FormData();body.set('file',file);const result=await api<Sticker>('/api/stickers/admin/upload',{method:'POST',body});setFile(null);setNotice(`${t.uploadDone}: ${result.fileName}`);await load();choose(result)}catch(cause){setNotice(apiErrorText(cause,language))}finally{setBusy(false)}}
  const save=async()=>{if(!selected)return;setBusy(true);setNotice('');try{const result=await api<Sticker>(`/api/stickers/admin/${selected.id}`,{method:'PATCH',body:JSON.stringify({tags:tags.split(',').map(s=>s.trim()).filter(Boolean),note,enabled:selected.enabled,expectedUpdatedAt:selected.updatedAt})});setSelected(result);setTags(result.tags.join(', '));setNote(result.note);setNotice(t.saved);await load()}catch(cause){if(cause instanceof ApiError&&cause.status===409){setNotice(zh?'表情已在其他位置修改，请重新选择。':'Sticker changed elsewhere; reselect it.');await load()}else setNotice(apiErrorText(cause,language))}finally{setBusy(false)}}
  const toggle=async()=>{if(!selected)return;setBusy(true);try{const result=await api<Sticker>(`/api/stickers/admin/${selected.id}`,{method:'PATCH',body:JSON.stringify({tags:tags.split(',').map(s=>s.trim()).filter(Boolean),note,enabled:!selected.enabled,expectedUpdatedAt:selected.updatedAt})});setSelected(result);setNotice(t.saved);await load()}catch{setNotice(t.error)}finally{setBusy(false)}}
  const changePage=(next:number)=>setPage(Math.max(0,next));
  if(error)return <main className="page media-page"><h1>{t.title}</h1><p role="alert">{error}</p><button className="button secondary" onClick={()=>void load()}>{zh?'重试':'Retry'}</button></main>
  return <main className="page media-page stickers-page"><div className="page-heading"><div><p className="eyebrow">{zh?'本地资源':'Local assets'}</p><h1>{t.title}</h1><p>{t.intro}</p></div></div>
    {notice&&<p role="status" className="notice">{notice}</p>}
    <section className="settings-section media-toolbar"><label>{t.search}<input aria-label={t.search} value={q} onChange={e=>{setQ(e.target.value);setPage(0)}}/></label><label>{t.format}<select aria-label={t.format} value={format} onChange={e=>{setFormat(e.target.value);setPage(0)}}><option value="">{t.all}</option><option value="png">PNG</option><option value="jpg">JPG</option><option value="jpeg">JPEG</option><option value="gif">GIF</option><option value="webp">WebP</option></select></label><label>{t.enabled}<select aria-label={t.enabled} value={enabled} onChange={e=>{setEnabled(e.target.value);setPage(0)}}><option value="">{t.all}</option><option value="true">{t.yes}</option><option value="false">{t.no}</option></select></label><label className="media-check"><input type="checkbox" checked={onlyAnimated} onChange={e=>setOnlyAnimated(e.target.checked)}/>{t.animated}</label><button className="button secondary" disabled={busy} onClick={()=>void scan()}>{t.scan}</button></section>
    <section className="sticker-import"><label>{t.upload}<input aria-label={t.upload} type="file" accept=".png,.jpg,.jpeg,.gif,.webp,image/png,image/jpeg,image/gif,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className="button secondary" disabled={busy||!file} onClick={()=>void upload()}>{t.upload}</button></section>
    <p className="quiet-note">{data?.total??0} {t.showing} · {data?.maxFileBytes?`${Math.round(data.maxFileBytes/1024/1024)} MiB / ${zh?'文件':'file'}`:''} · {t.unsupported}</p>
    <details className="format-capabilities"><summary>{zh?'格式能力：导入 / 预览 / OneBot 发送适配器':'Format capabilities: import / preview / OneBot send adapter'}</summary><div className="slang-table-wrap"><table className="slang-table"><thead><tr><th>{t.format}</th><th>{zh?'导入':'Import'}</th><th>{t.preview}</th><th>{zh?'发送适配器':'Send adapter'}</th></tr></thead><tbody>{formatNames.map(name=>{const cap=data!.formats[name];return <tr key={name}><th scope="row">{name.toUpperCase()}</th><td aria-label={cap.importSupported?t.supported:t.unsupportedLabel}>{cap.importSupported?`✓ ${t.supported}`:`— ${t.unsupportedLabel}`}</td><td aria-label={cap.previewSupported?t.supported:t.unsupportedLabel}>{cap.previewSupported?`✓ ${t.supported}`:`— ${t.unsupportedLabel}`}</td><td>{cap.sendSupported?(zh?`可调用，网关可能拒绝 · ${t.unknown}`:`Available; gateway may reject · ${t.unknown}`):t.unsupportedLabel}</td></tr>})}</tbody></table></div></details>
    <div className="sticker-workspace"><section className="sticker-grid" aria-label={t.title}>{data?.items.map(item=><button type="button" className={`sticker-card ${selected?.id===item.id?'selected':''}`} key={item.id} onClick={()=>choose(item)} aria-label={`${item.fileName||item.id}${item.enabled?'':' · '+t.no}`} aria-pressed={selected?.id===item.id}><img loading="lazy" src={`/api/stickers/${item.id}/content?v=${item.sha256}`} alt={item.fileName||item.id}/><span className="sticker-card-name">{item.fileName||item.id}</span><span className={`sticker-state ${item.enabled?'':'muted'}`}>{item.enabled?t.yes:t.no}{item.animated===true?' · GIF':''}</span></button>)}{data&&data.items.length===0&&<p>{t.empty}</p>}</section>
      {selected&&<aside className="sticker-detail" aria-label={t.metadata}><h2>{selected.fileName||selected.id}</h2><div className="sticker-preview"><img src={`/api/stickers/${selected.id}/content?v=${selected.sha256}`} alt={`${t.preview}: ${selected.fileName||selected.id}`}/></div><p>{selected.mimeType} · {selected.fileSize} {zh?'字节':'bytes'} · {selected.width&&selected.height?`${selected.width}×${selected.height}`:'—'} · {selected.animated===null?'?':selected.animated?'GIF':(zh?'静态':'Static')}</p><p>{t.sendPath}</p><p>SHA-256 · <code>{selected.sha256.slice(0,16)}…</code></p><label>{t.tags}<input aria-label={t.tags} value={tags} onChange={e=>setTags(e.target.value)}/></label><label>{t.note}<textarea aria-label={t.note} maxLength={500} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="media-actions"><button className="button primary" disabled={busy} onClick={()=>void save()}>{t.save}</button><button className="button secondary" disabled={busy} onClick={()=>void toggle()}>{selected.enabled?t.no:t.yes}</button></div><p className="quiet-note">{t.disabled}</p></aside>}</div>
    <nav className="media-pagination" aria-label={zh?'表情分页':'Sticker pagination'}><button className="button secondary" disabled={page===0} onClick={()=>changePage(page-1)}>{zh?'上一页':'Previous'}</button><span>{page+1} / {Math.max(1,Math.ceil((data?.total??0)/(data?.pageSize??24)))}</span><button className="button secondary" disabled={!data||((page+1)*data.pageSize>=data.total)} onClick={()=>changePage(page+1)}>{zh?'下一页':'Next'}</button></nav>
  </main>
}
