import { useEffect, useRef, useState } from 'react'
import { api, apiErrorText } from './api'
import type { Language } from './i18n'
import { UsageCostSummary } from './UsageCostSummary'

type Props={language:Language}
const text=(lang:Language,zh:string,en:string)=>lang==='zh-CN'?zh:en
export function UsageConsolePage({language:lang}:Props){
 const [window,setWindow]=useState('7d'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[provider,setProvider]=useState(''),[model,setModel]=useState(''),[conversation,setConversation]=useState('')
 const [summary,setSummary]=useState<any>(),[series,setSeries]=useState<any[]>([]),[breakdown,setBreakdown]=useState<any>(),[pricing,setPricing]=useState<any>(),[notice,setNotice]=useState(''),[error,setError]=useState('')
 const [pricingError,setPricingError]=useState('')
 const [newProvider,setNewProvider]=useState(''),[newModel,setNewModel]=useState(''),[newCurrency,setNewCurrency]=useState('USD')
 const refreshSequence=useRef(0)
 const query=(filters=true)=>{const p=new URLSearchParams({window});if(window==='custom'){p.set('from',from);p.set('to',to)}if(filters&&provider)p.set('provider',provider);if(filters&&model)p.set('model',model);if(filters&&conversation)p.set('conversation',conversation);return p.toString()}
 const refresh=()=>{const sequence=++refreshSequence.current;setSummary(undefined);setSeries([]);setError('');return Promise.all([api<any>(`/api/usage/summary?${query()}`),api<any>(`/api/usage/series?${query()}`),api<any>(`/api/usage/breakdown?${query(false)}`),api<any>('/api/pricing')]).then(([s,t,b,p])=>{if(sequence!==refreshSequence.current)return;setSummary(s);setSeries(t);setBreakdown(b);setPricing(p);setError('')}) .catch(e=>{if(sequence===refreshSequence.current)setError(apiErrorText(e,lang))})}
 useEffect(()=>{if(window!=='custom'||(from&&to))void refresh()},[window,from,to,provider,model,conversation,lang])
 useEffect(()=>()=>{refreshSequence.current++},[])
 const addPrice=()=>{if(!newProvider.trim()||!newModel.trim())return;setPricing({...pricing,rows:[...pricing.rows,{provider:newProvider.trim(),model:newModel.trim(),input:0,cacheHit:0,cacheMiss:0,output:0,reasoning:0,currency:newCurrency}]});setNewProvider('');setNewModel('')}
 const savePrices=async()=>{setPricingError('');setNotice('');try{const rows=pricing.rows.map((r:any)=>({...r,input:r.input===''?null:r.input,cacheHit:r.cacheHit===''?null:r.cacheHit,cacheMiss:r.cacheMiss===''?null:r.cacheMiss,output:r.output===''?null:r.output,reasoning:r.reasoning===''?null:r.reasoning}));const result=await api<any>('/api/pricing',{method:'PATCH',body:JSON.stringify({revision:pricing.revision,rows})});setPricing({...pricing,revision:result.revision,rows});await refresh();setNotice(text(lang,'价格已保存；历史费用按当前价格重估。','Rates saved; historical estimates now use current prices.'))}catch(e){setPricingError(apiErrorText(e,lang))}}
 const maxTokens=Math.max(1,...series.map(x=>Number(x.inputTokens)+Number(x.outputTokens)))
 return <div className="page ops-workspace"><div className="page-heading"><div><p className="eyebrow">XingChen</p><h1>{text(lang,'用量与价格','Usage & pricing')}</h1></div><label>{text(lang,'时间范围','Time window')}<select aria-label={text(lang,'时间范围','Time window')} value={window} onChange={e=>setWindow(e.target.value)}><option value="24h">24h</option><option value="3d">3d</option><option value="7d">7d</option><option value="30d">30d</option><option value="custom">{text(lang,'自定义 UTC','Custom UTC')}</option></select></label></div>
 {window==='custom'&&<div className="rule-add"><label>{text(lang,'从（UTC）','From (UTC)')}<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{text(lang,'到（UTC）','To (UTC)')}<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>}
 {breakdown&&<section className="usage-filters" aria-label={text(lang,'用量筛选','Usage filters')}><label>{text(lang,'提供商','Provider')}<select aria-label={text(lang,'提供商','Provider')} value={provider} onChange={e=>setProvider(e.target.value)}><option value="">{text(lang,'全部','All')}</option>{[...new Set((breakdown.providers??[]).map((x:any)=>x.provider))].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>{text(lang,'模型','Model')}<select aria-label={text(lang,'模型','Model')} value={model} onChange={e=>setModel(e.target.value)}><option value="">{text(lang,'全部','All')}</option>{[...new Set((breakdown.providers??[]).map((x:any)=>x.model))].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>{text(lang,'会话 ID','Conversation ID')}<select aria-label={text(lang,'会话 ID','Conversation ID')} value={conversation} onChange={e=>setConversation(e.target.value)}><option value="">{text(lang,'全部','All')}</option>{(breakdown.conversations??[]).filter((x:any)=>x.conversationId).map((x:any)=><option key={x.conversationId} value={x.conversationId}>{x.platformConversationId??x.conversationId}</option>)}</select></label></section>}
 {error&&<p role="alert">{error} <button className="button secondary" onClick={()=>void refresh()}>{text(lang,'重试','Retry')}</button></p>}{summary&&<><section className="settings-section"><h2>{text(lang,'汇总','Summary')}</h2><p>{text(lang,'输入','Input')} {summary.summary.inputTokens} · {text(lang,'缓存命中','Cache hit')} {summary.summary.cacheHitTokens} · {text(lang,'缓存未命中','Cache miss')} {summary.summary.cacheMissTokens} · {text(lang,'输出','Output')} {summary.summary.outputTokens} · {text(lang,'请求','Requests')} {summary.summary.requests}</p><p>{text(lang,'总 token','Total tokens')}: {summary.summary.totalTokens}</p><small>{text(lang,'Cache hit/miss 是 input 子集，reasoning 是 output 子集；合计不重复计算。用量和日期桶使用 UTC。','Cache hit/miss are input subsets; reasoning is an output subset. Totals do not double count. Usage and daily buckets use UTC.')}</small>{!summary.reasoningAvailable&&<p>{text(lang,'Reasoning：不可用（数据未包含该字段）','Reasoning: unavailable (field absent in source data)')}</p>}{summary.personAttributionAvailable===false&&<p>{text(lang,'按 Person：不可用（账本未记录 personId，不推断分摊）','By person: unavailable (ledger has no personId; no inferred allocation)')}</p>}</section>
 <UsageCostSummary cost={summary.cost} language={lang}/>
 <section className="settings-section"><h2>{text(lang,'每日趋势（UTC）','Daily trend (UTC)')}</h2>{series.length===0?<p>{text(lang,'暂无记录','No records')}</p>:<><div className="usage-bars" role="img" aria-label={text(lang,'按日期显示 token 趋势；下方有数据表','Token trend by date; an accessible data table follows')}>{series.map((r:any)=><div className="usage-bar-row" key={r.day}><span>{r.day}</span><div className="usage-bar-track"><i style={{width:`${Math.max(2,Math.round((Number(r.inputTokens)+Number(r.outputTokens))/maxTokens*100))}%`}}/></div><strong>{Number(r.inputTokens)+Number(r.outputTokens)}</strong></div>)}</div><div className="responsive-table"><table><thead><tr><th>UTC</th><th>{text(lang,'请求','Requests')}</th><th>{text(lang,'输入','Input')}</th><th>{text(lang,'缓存命中','Cache hit')}</th><th>{text(lang,'缓存未命中','Cache miss')}</th><th>{text(lang,'输出','Output')}</th><th>{text(lang,'推理','Reasoning')}</th></tr></thead><tbody>{series.map((r:any)=><tr key={r.day}><td>{r.day}</td><td>{r.requests}</td><td>{r.inputTokens}</td><td>{r.cacheHitTokens}</td><td>{r.cacheMissTokens}</td><td>{r.outputTokens}</td><td>{Number(r.reasoningAvailable)===1?r.reasoningTokens:text(lang,'不可用','Unavailable')}</td></tr>)}</tbody></table></div></>}</section>
 <section className="settings-section"><h2>{text(lang,'提供商 / 模型','Provider / Model')}</h2><Table language={lang} rows={breakdown.providers??[]}/></section><section className="settings-section"><h2>{text(lang,'会话汇总','Conversation breakdown')}</h2><Table language={lang} rows={breakdown.conversations??[]}/></section>
 <section className="settings-section"><h2>{text(lang,'价格（每百万 token）','Pricing (per 1M tokens)')}</h2><p>{text(lang,'费用是估算值，历史记录按当前费率重估，不是发票快照。','Costs are estimates; historical rows are revalued with current rates, not invoice snapshots.')}</p><p>{text(lang,'空白费率表示缺失，不代表零；若相应类别有 token，整条记录为未定价。','A blank rate is missing, not zero; any nonzero category with a missing rate makes the whole record unpriced.')}</p><form className="rule-add" onSubmit={e=>{e.preventDefault();addPrice()}}><label>{text(lang,'提供商','Provider')}<input required maxLength={128} aria-invalid={!!pricingError} aria-describedby={pricingError?'pricing-error':undefined} value={newProvider} onChange={e=>setNewProvider(e.target.value)}/></label><label>{text(lang,'模型','Model')}<input required maxLength={128} aria-invalid={!!pricingError} aria-describedby={pricingError?'pricing-error':undefined} value={newModel} onChange={e=>setNewModel(e.target.value)}/></label><label>{text(lang,'币种','Currency')}<input required pattern="[A-Z]{3}" maxLength={3} aria-invalid={!!pricingError} aria-describedby={pricingError?'pricing-error':undefined} value={newCurrency} onChange={e=>setNewCurrency(e.target.value.toUpperCase())}/></label><button className="button secondary">{text(lang,'添加价格项','Add pricing row')}</button></form>{pricing?.rows.map((r:any,i:number)=><div className="pricing-row" key={`${r.provider}/${r.model}`}><strong>{r.provider} / {r.model} ({r.currency})</strong>{(['input','cacheHit','cacheMiss','output','reasoning'] as const).map(k=><label key={k}>{text(lang,...rateLabels[k])}<input aria-label={`${r.model} ${text(lang,...rateLabels[k])} (${k})`} type="number" min="0" step="any" aria-invalid={!!pricingError} aria-describedby={pricingError?'pricing-error':undefined} value={r[k]??''} onChange={e=>setPricing({...pricing,rows:pricing.rows.map((x:any,n:number)=>n===i?{...x,[k]:e.target.value}:x)})}/></label>)}</div>)}<button className="button primary" disabled={!pricing?.rows.length} onClick={()=>void savePrices()}>{text(lang,'保存价格','Save rates')}</button>{pricingError&&<p id="pricing-error" role="alert">{pricingError}</p>}{notice&&<p role="status">{notice}</p>}</section><section className="settings-section"><h2>{text(lang,'记录','Records')}</h2><Records key={pricing?.revision} language={lang} window={window} from={from} to={to} provider={provider} model={model} conversation={conversation}/></section></>}
 </div>
}
function Table({rows,language:lang}:{rows:any[];language:Language}){if(!rows?.length)return <p>{text(lang,'暂无记录','No records')}</p>;const keys=Object.keys(rows[0]);return <div className="responsive-table"><table><thead><tr>{keys.map(k=><th key={k}>{text(lang,usageLabels[k]?.[0]??k,usageLabels[k]?.[1]??k)}</th>)}</tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={i}>{keys.map(k=><td key={k}>{usageCell(r[k],lang)}</td>)}</tr>)}</tbody></table></div>}
function Records({language:lang,window,from,to,provider,model,conversation}:{language:Language;window:string;from:string;to:string;provider:string;model:string;conversation:string}){const [page,setPage]=useState(0),[rows,setRows]=useState<any[]>([]),[recordError,setRecordError]=useState('');useEffect(()=>{const p=new URLSearchParams({window,page:String(page),size:'25'});if(window==='custom'){p.set('from',from);p.set('to',to)}if(provider)p.set('provider',provider);if(model)p.set('model',model);if(conversation)p.set('conversation',conversation);setRows([]);setRecordError('');api<any[]>(`/api/usage/records?${p}`).then(setRows).catch(()=>setRecordError(text(lang,'记录请求失败','Records request failed')))},[page,window,from,to,provider,model,conversation]);return <>{recordError&&<p role="alert">{recordError}</p>}{!recordError&&<Table language={lang} rows={rows}/>}<button className="button secondary" disabled={!page} onClick={()=>setPage(page-1)}>{text(lang,'上一页','Previous')}</button><button className="button secondary" onClick={()=>setPage(page+1)}>{text(lang,'下一页','Next')}</button></>}
const usageLabels:Record<string,[string,string]>={provider:['提供商','Provider'],model:['模型','Model'],requests:['请求','Requests'],inputTokens:['输入 token','Input tokens'],cacheHitTokens:['缓存命中 token','Cache hit tokens'],cacheMissTokens:['缓存未命中 token','Cache miss tokens'],outputTokens:['输出 token','Output tokens'],reasoningTokens:['推理 token','Reasoning tokens'],conversationId:['会话 ID','Conversation ID'],conversationType:['会话类型','Conversation type'],platformConversationId:['平台会话 ID','Platform conversation ID'],totalTokens:['总 token','Total tokens'],id:['记录 ID','Record ID'],turnId:['轮次 ID','Turn ID'],usageTime:['时间（UTC）','Time (UTC)'],reasoningAvailable:['推理数据可用','Reasoning available'],durationMillis:['耗时（毫秒）','Duration (ms)'],pricingStatus:['定价状态','Pricing status'],pricingReason:['定价原因','Pricing reason'],currency:['币种','Currency'],estimatedCost:['估算费用','Estimated cost']}
function usageCell(value:unknown,lang:Language){const translations:Record<string,[string,string]>={PRICED:['已定价','Priced'],UNPRICED:['未定价','Unpriced'],NO_MATCHING_PRICE:['无匹配价格','No matching price'],MISSING_INPUT_RATE:['缺少输入费率','Missing input rate'],MISSING_CACHE_HIT_RATE:['缺少缓存命中费率','Missing cache hit rate'],MISSING_CACHE_MISS_RATE:['缺少缓存未命中费率','Missing cache miss rate'],MISSING_OUTPUT_RATE:['缺少输出费率','Missing output rate'],MISSING_REASONING_RATE:['缺少推理费率','Missing reasoning rate'],INVALID_CURRENCY:['无效币种','Invalid currency'],INVALID_RATE:['无效费率','Invalid rate']};const raw=String(value??'—');return translations[raw]?text(lang,...translations[raw]):raw}
const rateLabels:Record<string,[string,string]>={input:['输入','Input'],cacheHit:['缓存命中','Cache hit'],cacheMiss:['缓存未命中','Cache miss'],output:['输出','Output'],reasoning:['推理','Reasoning']}
