import { expect, test } from './auditFixtures'

const login=async(page:import('@playwright/test').Page,user='e2e-admin',password='local-e2e-console-password')=>{await page.goto('/login');await page.getByLabel('管理员账号').fill(user);await page.getByLabel('密码').fill(password);await page.getByRole('button',{name:'登录'}).click();await expect(page).toHaveURL('/')}
const csrf=async(page:import('@playwright/test').Page)=>(await (await page.request.get('/api/auth/csrf')).json()).token as string

test('usage, access, logs and operations console are protected, bounded and responsive',async({page})=>{
 test.setTimeout(90_000);await login(page);const csrfToken=await csrf(page);const csrfCookie=(await page.context().cookies()).find(c=>c.name==='XSRF-TOKEN');expect(csrfCookie?.value).toBe(csrfToken);expect(csrfCookie?.httpOnly).toBe(true);expect((await page.context().cookies()).find(c=>c.name==='JSESSIONID')?.httpOnly).toBe(true)
 await page.getByRole('link',{name:'用量',exact:true}).click();await expect(page.getByRole('heading',{name:'用量与价格'})).toBeVisible();await expect(page.getByRole('heading',{name:'估算费用',exact:true})).toBeVisible();await expect(page.getByText(/历史用量/)).toBeVisible();await page.getByLabel('时间范围').selectOption('24h');await page.getByLabel('时间范围').selectOption('7d');await expect(page.getByRole('heading',{name:'提供商 / 模型'})).toBeVisible()
 const price=await page.request.get('/api/pricing');const before=await price.json();const costBefore=(await (await page.request.get('/api/usage/summary?window=7d')).json()).cost.costsByCurrency.USD.estimatedCost;const csrfValue=await csrf(page);const changedRows=before.rows.map((r:any,i:number)=>i===0?{...r,cacheHit:Number(r.cacheHit)+1}:r);const save=await page.request.patch('/api/pricing',{headers:{'X-XSRF-TOKEN':csrfValue},data:{revision:before.revision,rows:changedRows}});expect(save.status()).toBe(200);const costAfter=(await (await page.request.get('/api/usage/summary?window=7d')).json()).cost.costsByCurrency.USD.estimatedCost;expect(Number(costAfter)).toBeGreaterThan(Number(costBefore));const stale=await page.request.patch('/api/pricing',{headers:{'X-XSRF-TOKEN':csrfValue},data:{revision:before.revision,rows:before.rows}});expect(stale.status()).toBe(409)
 await page.getByRole('link',{name:'访问控制',exact:true}).click();await expect(page.getByRole('heading',{name:'访问控制'})).toBeVisible();await expect(page.getByText(/默认拒绝/).first()).toBeVisible();await expect(page.getByText(/e2e-member/).first()).toBeVisible();await page.getByLabel('用户稳定 ID',{exact:true}).fill('browser-e2e-member');await page.getByRole('button',{name:'添加规则'}).click();await expect(page.getByText(/browser-e2e-member/).first()).toBeVisible();page.once('dialog',dialog=>dialog.accept());const policyResponse=page.waitForResponse(r=>r.url().endsWith('/api/access/rules')&&r.request().method()==='PATCH');await page.getByRole('button',{name:'保存策略'}).click();expect((await policyResponse).status()).toBe(200);await expect(page.getByText('访问规则已更新')).toBeVisible();await page.getByLabel('用户稳定 ID').fill('browser-e2e-member');await page.getByLabel('会话 / 群组 ID').fill('preview-group');await page.getByRole('button',{name:/检查/}).click();await expect(page.getByText('允许 (ALLOW) · 显式允许 (EXPLICIT_ALLOW)')).toBeVisible();
 await page.getByRole('link',{name:'安全',exact:true}).click();await expect(page.getByRole('heading',{name:'安全中心'})).toBeVisible();const posture=await page.request.get('/api/security/posture');expect((await posture.json()).passwordConfigured).toBe(true);expect(await page.locator('body').innerText()).not.toContain('password_hash')
 await page.getByRole('link',{name:'日志',exact:true}).click();await expect(page.getByRole('heading',{name:'日志与审计'})).toBeVisible();await page.getByLabel('组件').selectOption('AUTH');await page.getByRole('button',{name:'应用筛选'}).click();await expect(page.getByRole('cell',{name:'登录成功'}).first()).toBeVisible();await page.getByRole('button',{name:'审计记录'}).click();await page.getByLabel('操作者').fill('e2e-admin');await page.getByLabel('类别').fill('ACCESS');await page.getByRole('button',{name:'应用筛选'}).click();await expect(page.getByRole('cell',{name:'e2e-admin'}).first()).toBeVisible();await expect(page.locator('body')).not.toContainText(/fixture message|private fixture memory|API_KEY=/)
 await page.getByRole('link',{name:'运行维护',exact:true}).click();await expect(page.getByRole('heading',{name:'运行维护'})).toBeVisible();await expect(page.getByRole('cell',{name:'未跟踪 (NOT_TRACKED)',exact:true})).toBeVisible();await page.setViewportSize({width:375,height:812});await page.getByRole('button',{name:'打开导航'}).click();await expect(page.getByRole('navigation',{name:'主导航'})).toBeVisible();await page.getByRole('link',{name:'用量',exact:true}).click();await expect(page.getByRole('heading',{name:'用量与价格'})).toBeVisible();await page.getByRole('button',{name:'打开导航'}).click();await page.getByRole('link',{name:'访问控制',exact:true}).click();await expect(page.getByRole('heading',{name:'访问控制'})).toBeVisible();await page.getByRole('button',{name:'打开导航'}).click();await page.getByRole('link',{name:'安全',exact:true}).click();await expect(page.getByRole('heading',{name:'安全中心'})).toBeVisible();await page.getByRole('button',{name:'打开导航'}).click();await page.getByRole('link',{name:'日志',exact:true}).click();await expect(page.getByRole('heading',{name:'日志与审计'})).toBeVisible();await page.getByRole('button',{name:'运行日志'}).click();await expect(page.getByLabel('组件')).toBeVisible();await page.getByRole('button',{name:'打开导航'}).click();await page.getByRole('link',{name:'运行维护',exact:true}).click();await expect(page.getByRole('heading',{name:'运行维护'})).toBeVisible();
 await page.getByRole('button',{name:'打开导航'}).click();await page.getByRole('button',{name:'退出登录'}).click();await page.getByRole('alertdialog').getByRole('button',{name:'确认'}).click();await expect(page).toHaveURL(/\/login$/);expect((await page.request.get('/api/usage/summary')).status()).toBe(401)
})

test('password change invalidates old credentials and the prior browser session',async({page})=>{
 await login(page,'e2e-rotation-admin','local-e2e-secondary-password');const oldSession=await page.context().cookies();await page.getByRole('link',{name:'安全',exact:true}).click();await page.getByLabel('当前密码').fill('local-e2e-secondary-password');await page.getByLabel('新密码（至少 14 字符）').fill('local-e2e-rotated-password-2036');await page.getByLabel('确认新密码').fill('local-e2e-rotated-password-2036');await page.getByRole('button',{name:'更新并退出所有会话'}).click();await expect(page.getByRole('status')).toContainText('密码已更新');expect((await page.request.get('/api/console/overview')).status()).toBe(401);expect(oldSession.some(c=>c.name==='JSESSIONID')).toBe(true)
 await page.goto('/login');await page.getByLabel('管理员账号').fill('e2e-rotation-admin');await page.getByLabel('密码').fill('local-e2e-secondary-password');await page.getByRole('button',{name:'登录'}).click();await expect(page.getByRole('alert')).toHaveText('账号或密码不正确');await page.getByLabel('密码').fill('local-e2e-rotated-password-2036');await page.getByRole('button',{name:'登录'}).click();await expect(page).toHaveURL('/')
})
