import { expect, test } from './auditFixtures'
import { memoryTestWindow } from '../src/ui/memoryTime'

const username = process.env.XINGCHEN_E2E_ADMIN_USER ?? 'e2e-admin'
const password = process.env.XINGCHEN_E2E_ADMIN_PASSWORD ?? 'local-e2e-console-password'

async function openMobileNavigation(page: import('@playwright/test').Page, language: 'zh-CN' | 'en-US') {
  const navigationName = language === 'zh-CN' ? '主导航' : 'Main navigation'
  const triggerName = language === 'zh-CN' ? '打开导航' : 'Open navigation'
  const navigation = page.getByRole('navigation', { name: navigationName })
  const trigger = page.getByRole('button', { name: triggerName })
  if (await trigger.getAttribute('aria-expanded') !== 'true') await trigger.click()
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(navigation).toBeVisible()
}

test('admin console auth, session, locale, theme, overview, settings and responsive navigation', async ({ page,expectedHttpErrors }) => {
  test.setTimeout(90_000)
  await page.goto('/')
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole('heading', { name: '欢迎回来' })).toBeVisible()
  await page.getByLabel('管理员账号').fill(username)
  await page.getByLabel('密码').fill('wrong-local-password-000')
  await page.getByRole('button', { name: '登录' }).click()
  await expect(page.getByRole('alert')).toHaveText('账号或密码不正确')

  await page.getByLabel('密码').fill(password)
  await page.getByRole('button', { name: '登录' }).click()
  await expect(page).toHaveURL('/')
  await expect(page.getByRole('heading', { name: '总览' })).toBeVisible()
  expect((await page.request.get('/health')).status()).toBe(200)
  const cookies = await page.context().cookies()
  const sessionCookie = cookies.find((item) => item.name === 'JSESSIONID')
  expect(sessionCookie?.httpOnly).toBe(true)
  expect(sessionCookie?.sameSite).toBe('Strict')
  await page.reload()
  await expect(page.getByRole('heading', { name: '总览' })).toBeVisible()
  await expect(page.getByText('外部连接已关闭')).toBeVisible()

  // Conversation / runtime operations use deterministic fake-profile records only.
  await page.getByRole('link', { name: '会话', exact: true }).click()
  await expect(page.getByRole('heading', { name: '会话', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Console Owner/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /group-sleeping/ })).toBeVisible()
  await page.getByLabel('运行状态').selectOption('WAITING')
  await expect(page.getByRole('button', { name: /group-waiting/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Console Owner/ })).toHaveCount(0)
  const prepareWaiting = async () => page.evaluate(async () => {
    const csrf = (await (await fetch('/api/auth/csrf', { credentials: 'same-origin' })).json()).token
    const response = await fetch('/api/fake/conversations/waiting-group/waiting', { method: 'POST', headers: { 'X-XSRF-TOKEN': csrf } })
    return response.status
  })
  expect(await prepareWaiting()).toBe(200)
  await page.getByRole('button', { name: /group-waiting/ }).click()
  await expect(page.getByRole('heading', { name: 'group-waiting' })).toBeVisible()
  await expect(page.getByText(/next-message/)).toBeVisible()
  const waitingBefore = await page.request.get(`/api/conversations/10000000-0000-0000-0000-000000000004`)
  const waitingGeneration = (await waitingBefore.json()).generation
  await page.getByRole('button', { name: '重置会话' }).click()
  const waitingDialog = page.getByRole('alertdialog')
  await expect(waitingDialog).toContainText('长期记忆')
  const waitingResetResponse = page.waitForResponse(response => /\/api\/conversations\/10000000-0000-0000-0000-000000000004\/reset$/.test(response.url()) && response.request().method() === 'POST')
  await waitingDialog.getByRole('button', { name: '确认' }).click()
  expect((await waitingResetResponse).status()).toBe(200)
  await expect(page.getByText('会话已重置。')).toBeVisible()
  const waitingAfter = await page.request.get('/api/conversations/10000000-0000-0000-0000-000000000004')
  expect((await waitingAfter.json()).generation).toBe(waitingGeneration + 1)
  expect((await waitingAfter.json()).runtime.wake_state).toBe('IDLE')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'group-waiting' })).toBeVisible()
  const preserved = await page.request.get('/api/fake/conversations/private-owner/preservation')
  expect(preserved.status()).toBe(200)
  expect(await preserved.json()).toMatchObject({ relationships: 1, memories: 1 })

  await page.goto('/conversations')
  await page.getByRole('button', { name: /Console Owner/ }).click()
  await expect(page.getByRole('heading', { name: 'Console Owner' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '最近消息' })).toBeVisible()
  await page.locator('#conversation-mode').selectOption('CLOSED_AGENT')
  await page.getByRole('button', { name: '保存模式' }).click()
  await expect(page.getByText('模式已更新。')).toBeVisible()
  await page.getByRole('button', { name: '手动唤醒' }).click()
  await expect(page.getByText('会话已唤醒。')).toBeVisible()

  await page.goto('/conversations')
  await page.getByLabel('含 UNKNOWN 发送').check()
  await page.getByRole('button', { name: /group-unknown/ }).click()
  await expect(page.getByText(/系统不会自动重发/)).toBeVisible()
  await page.goto('/conversations')
  await page.getByLabel('含中断任务').check()
  await page.getByRole('button', { name: /group-interrupted/ }).click()
  await expect(page.getByText(/需要恢复审查/)).toBeVisible()

  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/conversations')
  await page.getByRole('button', { name: /Console Owner/ }).click()
  const privateBefore = await page.request.get('/api/conversations/10000000-0000-0000-0000-000000000003')
  const privateGeneration = (await privateBefore.json()).generation
  await page.getByRole('button', { name: '重置会话' }).click()
  const privateResetResponse = page.waitForResponse(response => /\/api\/conversations\/10000000-0000-0000-0000-000000000003\/reset$/.test(response.url()) && response.request().method() === 'POST')
  await page.getByRole('alertdialog').getByRole('button', { name: '确认' }).click()
  expect((await privateResetResponse).status()).toBe(200)
  await expect(page.getByText('会话已重置。')).toBeVisible()
  const privateAfter = await page.request.get('/api/conversations/10000000-0000-0000-0000-000000000003')
  expect((await privateAfter.json()).generation).toBe(privateGeneration + 1)
  const privatePreserved = await page.request.get('/api/fake/conversations/private-owner/preservation')
  expect(await privatePreserved.json()).toMatchObject({ relationships: 1, memories: 1, memberships: 2 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)

  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '总览' })).toBeVisible()
  await page.getByLabel('主题').selectOption('dark')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByLabel('主题').selectOption('late')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'late')
  await page.getByLabel('主题').selectOption('light')

  await page.getByLabel('语言').selectOption('en-US')
  await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible()
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Console settings' })).toBeVisible()
  await page.getByRole('link', { name: 'QQ / Gateway' }).click()
  await expect(page.locator('.status-pill')).toHaveText('Not configured')
  await expect(page.getByRole('heading', { name: 'Login management' })).toBeVisible()
  await expect(page.getByText(/does not support direct QR retrieval/)).toBeVisible()
  const gatewayConfig = page.getByRole('heading', { name: 'OneBot configuration' }).locator('..')
  await expect(gatewayConfig).toBeVisible()
  await page.getByLabel('Enable OneBot runtime').check()
  await page.getByLabel('OneBot HTTP URL').fill('http://127.0.0.1:3000')
  await page.getByLabel('OneBot WebSocket URL').fill('ws://127.0.0.1:3001')
  await gatewayConfig.getByRole('button', { name: 'Save settings' }).click()
  await expect(page.getByText('Configuration saved and applied to the OneBot runtime.')).toBeVisible()
  const changeFakeState = async (state: 'CONNECTED' | 'DISCONNECTED') => page.evaluate(async (next) => {
    const csrf = (await (await fetch('/api/auth/csrf', { credentials: 'same-origin' })).json()).token
    const response = await fetch('/api/test/gateway/state', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-XSRF-TOKEN': csrf }, body: JSON.stringify({ state: next }) })
    return response.status
  }, state)
  expect(await changeFakeState('CONNECTED')).toBe(200)
  await page.reload()
  await expect(page.getByText(/Fake QQ · fake-qq/)).toBeVisible()
  expect((await page.request.post('/api/gateway/reconnect')).status()).toBe(403)
  expectedHttpErrors.push({path:'/api/gateway/reconnect',status:501})
  const unsupportedReconnect = await page.evaluate(async () => {
    const csrf = (await (await fetch('/api/auth/csrf', { credentials: 'same-origin' })).json()).token
    const response = await fetch('/api/gateway/reconnect', { method: 'POST', headers: { 'X-XSRF-TOKEN': csrf } })
    return response.status
  })
  expect(unsupportedReconnect).toBe(501)
  expect(await changeFakeState('DISCONNECTED')).toBe(200)
  await page.reload()
  await expect(page.locator('.status-pill').filter({ hasText: 'OneBot disconnected' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByLabel('OneBot HTTP URL')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)

  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Open navigation' })).toBeVisible()
  await openMobileNavigation(page, 'en-US')
  await page.getByRole('link', { name: 'Overview' }).click()
  await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible()
  await openMobileNavigation(page, 'en-US')
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: 'Confirm' }).click()
  await expect(page).toHaveURL(/\/login$/)
  const protectedResponse = await page.request.get(new URL('/api/console/overview', page.url()).toString())
  expect(protectedResponse.status()).toBe(401)
  expect((await page.request.get(new URL('/api/conversations', page.url()).toString())).status()).toBe(401)
})

test('people, relationships, memory isolation, reset preservation and mobile controls', async ({ page }) => {
  test.setTimeout(120_000)
  const testNow = new Date()
  // Browser context is explicitly UTC; do not inherit the Node runner's local timezone.
  const memoryRange = memoryTestWindow(testNow, true)
  await page.goto('/login')
  await page.getByLabel('管理员账号').fill(username)
  await page.getByLabel('密码').fill(password)
  await page.getByRole('button', { name: '登录' }).click()
  await page.getByRole('link', { name: '成员', exact: true }).click()
  await expect(page.getByRole('heading', { name: '人物' })).toBeVisible()
  await page.getByLabel(/搜索平台 ID/).fill('e2e-owner')
  await page.getByRole('button', { name: '搜索' }).click()
  await page.getByRole('link', { name: /Owner card/ }).click()
  const person = '20000000-0000-0000-0000-000000000002'
  const member = '20000000-0000-0000-0000-000000000003'
  const group = '10000000-0000-0000-0000-000000000002'
  const privateConversation = '10000000-0000-0000-0000-000000000003'
  await expect(page).toHaveURL(new RegExp(`/people/${person}$`))
  await expect(page.getByText('平台身份键不可编辑')).toBeVisible()
  await expect(page.getByText('Owner alias')).toBeVisible()
  await expect(page.getByText('group-active')).toBeVisible()
  expect(await page.getByRole('textbox').count()).toBe(0)

  await page.goto('/relationships')
  await page.getByLabel('称呼方人物 ID').fill(person)
  await page.getByLabel('目标人物 ID').fill(member)
  await page.getByRole('textbox', { name: '称呼', exact:true }).fill('妹妹')
  await page.getByRole('button', { name: '创建显式关系' }).click()
  await expect(page.getByText('称呼已创建')).toBeVisible()
  await page.getByRole('textbox', { name: '称呼', exact:true }).fill('姐姐')
  await page.getByLabel('范围').selectOption('CONVERSATION')
  const conversationScope = page.getByRole('textbox', { name: '会话 ID', exact:true })
  await conversationScope.fill(group)
  await expect(conversationScope).toHaveValue(group)
  expect(await conversationScope.evaluate((input: HTMLInputElement) => input.checkValidity())).toBe(true)
  const localCreateResponse = page.waitForResponse(response => response.url().includes('/api/relationships') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '创建显式关系' }).click()
  const localCreate = await localCreateResponse
  expect(localCreate.status()).toBe(200)
  await expect(page.getByRole('status')).toHaveText('称呼已创建')
  const relationshipList = await page.request.get(`/api/relationships?personId=${person}`)
  expect((await relationshipList.json()).items.map((item: { term: string; scopeId: string }) => [item.term, item.scopeId])).toContainEqual(['姐姐', 'group-active'])
  const localTerm = page.locator('.relationship-entry').filter({ hasText: 'group-active' })
  await expect(localTerm).toContainText('姐姐')
  await localTerm.getByRole('button', { name: '编辑' }).click()
  await page.getByRole('textbox', { name: '称呼', exact:true }).fill('学姐')
  await page.getByLabel('范围').selectOption('PRIVATE')
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.getByText('称呼已更新')).toBeVisible()
  await expect(page.locator('.relationship-entry').filter({ hasText: '学姐' })).toContainText('私有 (PRIVATE)')
  await page.getByLabel('用于预览的会话 ID').fill(group)
  await page.getByRole('button', { name: '预览当前称呼' }).click()
  await expect(page.getByText(/当前生效称呼: 学姐/)).toBeVisible()
  await expect(page.locator('.identity-box')).toContainText('会话显式')
  page.once('dialog', dialog => dialog.accept())
  await page.locator('.relationship-entry').filter({ hasText: '妹妹' }).getByRole('button', { name: '停用称呼 妹妹' }).click()
  await expect(page.getByText('称呼已停用')).toBeVisible()
  await expect(page.locator('.relationship-entry').filter({ hasText: '妹妹' })).toHaveCount(0)
  await page.reload()
  await expect(page.getByText('学姐')).toBeVisible()

  const preview = async (who: string, conv: string, project?: string) => {
    const url = new URL('/api/memory/retrieval-preview', page.url())
    url.searchParams.set('personId', who); url.searchParams.set('conversationId', conv)
    if (project) url.searchParams.set('projectKey', project)
    const response = await page.request.get(url.toString())
    expect(response.headers()['cache-control']).toContain('no-store')
    expect(response.status(), await response.text()).toBe(200)
    return (await response.json()) as { items: { id: string; scope: string }[]; modelInvoked: boolean }
  }
  const sameContext = await preview(person, group, 'fixture-project')
  expect(sameContext.modelInvoked).toBe(false)
  expect(sameContext.items.map(item => item.id)).toEqual(expect.arrayContaining([
    '70000000-0000-0000-0000-000000000001', '70000000-0000-0000-0000-000000000003',
    '70000000-0000-0000-0000-000000000004', '70000000-0000-0000-0000-000000000006',
  ]))
  const otherContext = await preview(member, '10000000-0000-0000-0000-000000000001', 'other-project')
  expect(otherContext.items.map(item => item.id)).not.toContain('70000000-0000-0000-0000-000000000001')
  expect(otherContext.items.map(item => item.id)).not.toContain('70000000-0000-0000-0000-000000000003')
  expect(otherContext.items.map(item => item.id)).not.toContain('70000000-0000-0000-0000-000000000004')
  expect(otherContext.items.map(item => item.id)).not.toContain('70000000-0000-0000-0000-000000000006')
  const otherConversationSameProject = await preview(person, '10000000-0000-0000-0000-000000000001', 'fixture-project')
  expect(otherConversationSameProject.items.map(item => item.id)).not.toContain('70000000-0000-0000-0000-000000000003')
  const differentProject = await preview(person, group, 'other-project')
  expect(differentProject.items.map(item => item.id)).not.toContain('70000000-0000-0000-0000-000000000004')
  const memberPrivate = await preview(member, group, 'fixture-project')
  expect(memberPrivate.items.map(item => item.id)).toContain('70000000-0000-0000-0000-000000000002')
  expect(memberPrivate.items.map(item => item.id)).not.toContain('70000000-0000-0000-0000-000000000001')

  await page.goto(`/memory?person=${person}&conversation=${privateConversation}`)
  await page.getByLabel('记忆正文').last().fill('e2e long-term fern note')
  await page.getByRole('button', { name: '创建记忆' }).click()
  await expect(page.getByText('记忆已创建')).toBeVisible()
  await page.getByLabel('全文搜索').fill('fern')
  await page.getByLabel('人物 ID').fill(person)
  await page.getByLabel('会话 ID',{exact:true}).fill(privateConversation)
  await page.getByLabel('类型').first().selectOption('SEMANTIC')
  await page.getByLabel('范围').first().selectOption('PERSON_GLOBAL')
  await page.getByLabel('状态').selectOption('ACTIVE')
  await page.getByLabel(/创建时间起/).fill(memoryRange.from)
  await page.getByLabel(/创建时间止/).fill(memoryRange.to)
  await page.getByRole('button', { name: '筛选' }).click()
  await page.getByRole('link', { name: /e2e long-term fern note/ }).click()
  const memoryId = new URL(page.url()).searchParams.get('id')!
  await expect(page.locator('.memory-content')).toContainText('e2e long-term fern note')
  const detailResponse = await page.request.get(`/api/memory/${memoryId}`)
  expect(detailResponse.headers()['cache-control']).toContain('no-store')
  await page.getByRole('button', { name: '预览检索可见性' }).click()
  await expect(page.getByText(/模型未调用/)).toBeVisible()
  expect((await preview(person, privateConversation)).items.map(item => item.id)).toContain(memoryId)
  expect((await preview(member, privateConversation)).items.map(item => item.id)).not.toContain(memoryId)
  expect(await page.evaluate(() => [...Object.values(localStorage), ...Object.values(sessionStorage)].some(value => value.includes('e2e long-term fern note')))).toBe(false)
  await page.getByLabel('记忆正文').fill('e2e long-term fern note edited')
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.locator('.memory-content')).toContainText('edited')
  await page.getByLabel('范围').last().selectOption('GLOBAL')
  page.once('dialog', async dialog => { expect(dialog.message()).toMatch(/扩大|expands/); await dialog.dismiss() })
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.locator('.memory-content')).toContainText('edited')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '停用 / 忘记' }).click()
  await expect(page.getByText('记忆已停用')).toBeVisible()
  await page.getByLabel('全文搜索').fill('fern')
  await page.getByLabel('范围').first().selectOption('GLOBAL')
  await page.getByLabel('状态').selectOption('ACTIVE')
  await page.getByRole('button', { name: '筛选' }).click()
  await expect(page.getByText('e2e long-term fern note', { exact: true })).toHaveCount(0)

  await page.goto('/memory')
  await page.getByLabel('人物 ID').fill(member)
  await page.getByLabel('会话 ID',{exact:true}).fill(group)
  await page.getByLabel('类型').first().selectOption('EPISODIC')
  await page.getByLabel('范围').first().selectOption('CONVERSATION')
  await page.getByLabel('状态').selectOption('ACTIVE')
  await page.getByRole('button', { name: '筛选' }).click()
  await expect(page.getByText('conversation fixture memory')).toBeVisible()
  await page.getByLabel('会话 ID',{exact:true}).fill('')
  await page.getByLabel('项目键').fill('fixture-project')
  await page.getByLabel('类型').first().selectOption('PROJECT')
  await page.getByLabel('范围').first().selectOption('PROJECT')
  await page.getByRole('button', { name: '筛选' }).click()
  await expect(page.getByText('project fixture memory')).toBeVisible()

  await page.goto('/conversations')
  await page.getByRole('button', { name: /group-active/ }).click()
  const beforeReset = await page.request.get(`/api/conversations/${group}`)
  const generation = (await beforeReset.json()).generation
  await page.getByRole('button', { name: '重置会话' }).click()
  await expect(page.getByRole('alertdialog')).toHaveAttribute('aria-labelledby','reset-title')
  await expect(page.getByRole('alertdialog').getByRole('button',{name:'取消'})).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('alertdialog').getByRole('button',{name:'确认'})).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button',{name:'重置会话'})).toBeFocused()
  await page.keyboard.press('Enter')
  await page.getByRole('alertdialog').getByRole('button', { name: '确认' }).click()
  await expect(page.getByText('会话已重置。')).toBeVisible()
  const afterReset = await page.request.get(`/api/conversations/${group}`)
  expect((await afterReset.json()).generation).toBe(generation + 1)
  const personAfterReset = await page.request.get(`/api/people/${person}`)
  expect(personAfterReset.headers()['cache-control']).toContain('no-store')
  expect((await personAfterReset.json()).aliases.map((item: { alias: string }) => item.alias)).toContain('Owner alias')
  expect((await personAfterReset.json()).memberships.map((item: { platformConversationId: string }) => item.platformConversationId)).toContain('group-active')
  const persistedRelationship = await page.request.get(`/api/relationships?personId=${person}`)
  expect((await persistedRelationship.json()).items.map((item: { term: string }) => item.term)).toContain('学姐')
  const persistedMemory = await page.request.get(`/api/memory?person=${person}&status=ACTIVE`)
  expect(persistedMemory.status(), await persistedMemory.text()).toBe(200)
  expect((await persistedMemory.json()).items.map((item: { id: string }) => item.id)).toContain('70000000-0000-0000-0000-000000000001')
  expect((await preview(person, group)).items.map(item => item.id)).toContain('70000000-0000-0000-0000-000000000001')

  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/people')
  await page.getByLabel(/搜索平台 ID/).fill('e2e-owner')
  await page.getByRole('button', { name: '搜索' }).click()
  await page.getByRole('link', { name: /Owner card/ }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.goto('/relationships')
  await page.getByLabel('称呼方人物 ID').fill(person)
  await page.getByLabel('目标人物 ID').fill(member)
  await page.getByRole('textbox', { name: '称呼', exact:true }).fill('妹妹')
  await page.getByRole('button', { name: '创建显式关系' }).click()
  await expect(page.getByText('称呼已创建')).toBeVisible()
  const mobileTerm = page.locator('.relationship-entry').filter({ hasText: '学姐' })
  await mobileTerm.getByRole('button', { name: '编辑' }).click()
  await page.getByRole('textbox', { name: '称呼', exact:true }).fill('学妹')
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.getByText('称呼已更新')).toBeVisible()
  await page.getByLabel('用于预览的会话 ID').fill(group)
  await page.getByRole('button', { name: '预览当前称呼' }).click()
  await expect(page.locator('.identity-box')).toContainText('当前生效称呼: 学妹')
  await expect(page.locator('.identity-box')).toContainText('全局显式')
  page.once('dialog', dialog => dialog.accept())
  await page.locator('.relationship-entry').filter({ hasText: '妹妹' }).getByRole('button', { name: '停用称呼 妹妹' }).click()
  await expect(page.getByText('称呼已停用')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.goto(`/memory?person=${person}&conversation=${group}`)
  await page.getByLabel('记忆正文').last().fill('mobile-private-note')
  await page.getByLabel('范围').last().selectOption('PRIVATE')
  await page.getByRole('button', { name: '创建记忆' }).click()
  await expect(page.getByText('记忆已创建')).toBeVisible()
  await page.getByLabel('全文搜索').fill('mobile')
  await page.getByLabel('类型').first().selectOption('SEMANTIC')
  await page.getByLabel('范围').first().selectOption('PRIVATE')
  await page.getByLabel('状态').selectOption('ACTIVE')
  await page.getByLabel(/创建时间起/).fill(memoryRange.from)
  await page.getByLabel(/创建时间止/).fill(memoryRange.to)
  await page.getByRole('button', { name: '筛选' }).click()
  await page.getByRole('link', { name: /mobile-private-note/ }).click()
  await expect(page.locator('.memory-content')).toContainText('mobile-private-note')
  await page.getByLabel('记忆正文').fill('mobile-private-note edited')
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.locator('.memory-content')).toContainText('edited')
  await page.getByLabel('范围').selectOption('PERSON_GLOBAL')
  page.once('dialog', async dialog => { expect(dialog.message()).toMatch(/扩大|expands/); await dialog.dismiss() })
  await page.getByRole('button', { name: '保存修改' }).click()
  await page.getByLabel('范围').selectOption('PERSON_GLOBAL')
  page.once('dialog', async dialog => { expect(dialog.message()).toMatch(/扩大|expands/); await dialog.accept() })
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.getByText('记忆已保存')).toBeVisible()
  await page.getByRole('button', { name: '预览检索可见性' }).click()
  await expect(page.getByText(/模型未调用/)).toBeVisible()
  await expect(page.locator('.identity-box')).toContainText('PERSON_GLOBAL')
  await expect(page.locator('.identity-box')).toContainText('同一人物的长期记忆')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '停用 / 忘记' }).click()
  await expect(page.getByText('记忆已停用')).toBeVisible()
  await page.getByLabel('全文搜索').fill('mobile')
  await page.getByLabel('状态').selectOption('ACTIVE')
  await page.getByRole('button', { name: '筛选' }).click()
  await expect(page.getByText('mobile-private-note edited', { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await openMobileNavigation(page, 'zh-CN')
  await page.getByRole('button', { name: '退出登录' }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: '确认' }).click()
  await expect(page).toHaveURL(/\/login$/)
  expect((await page.request.get('/api/memory')).status()).toBe(401)
  expect((await page.request.get('/api/people')).status()).toBe(401)
})

test('people, relationship and memory labels are localized in Chinese and English', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('管理员账号').fill(username)
  await page.getByLabel('密码').fill(password)
  await page.getByRole('button', { name: '登录' }).click()
  await expect(page.getByRole('heading', { name: '总览' })).toBeVisible()
  await page.getByLabel('语言').selectOption('en-US')

  await page.goto('/people')
  await expect(page.getByRole('heading', { name: 'People' })).toBeVisible()
  await expect(page.getByLabel('Search platform ID, display name, alias, or group card')).toBeVisible()
  await page.goto('/relationships')
  await expect(page.getByRole('heading', { name: 'Relationship management' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Create explicit term' })).toBeVisible()
  await page.goto('/memory')
  await expect(page.getByRole('heading', { name: 'Long-term memory' })).toBeVisible()
  await expect(page.getByLabel('Created from (inclusive)')).toBeVisible()
  await expect(page.getByLabel('Created to (exclusive)')).toBeVisible()
  await page.goto('/memory?id=70000000-0000-0000-0000-000000000001&person=20000000-0000-0000-0000-000000000002&conversation=10000000-0000-0000-0000-000000000002')
  await page.getByRole('button', { name: 'Preview retrieval visibility' }).click()
  await expect(page.locator('.identity-box')).toContainText('Long-term memory for the same person')

  await page.getByLabel('Language').selectOption('zh-CN')
  await page.goto('/people')
  await expect(page.getByRole('heading', { name: '人物' })).toBeVisible()
  await expect(page.getByLabel('搜索平台 ID、昵称、别名或群名片')).toBeVisible()
  await page.goto('/relationships')
  await expect(page.getByRole('heading', { name: '关系管理' })).toBeVisible()
  await page.goto('/memory')
  await expect(page.getByRole('heading', { name: '长期记忆' })).toBeVisible()
  await expect(page.getByLabel('创建时间起（含）')).toBeVisible()
  await expect(page.getByLabel('创建时间止（不含）')).toBeVisible()
})

test('Persona and Simulation prompts create immutable versions, compare, rollback and persist across reload', async ({ page }) => {
  test.setTimeout(90_000)
  await page.goto('/login'); await page.getByLabel('管理员账号').fill(username); await page.getByLabel('密码').fill(password); await page.getByRole('button',{name:'登录'}).click();await expect(page.getByRole('heading',{name:'总览'})).toBeVisible()
  await page.goto('/persona'); await expect(page.getByRole('heading',{name:'人格'})).toBeVisible(); await expect(page.getByText('定义机器人是谁，以及表达风格。')).toBeVisible()
  const persona=page.getByLabel('人格');const initialPersona=await persona.inputValue();await persona.fill(`${initialPersona}\nPersona E2E v2`);await expect(page.getByText('未保存更改',{exact:true})).toBeVisible();await page.getByRole('button',{name:'保存为新版本并启用'}).click();await expect(page.locator('.notice')).toContainText('已创建并启用新版本')
  await expect(page.locator('.status-pill')).toContainText('当前版本 v2');await expect(page.getByRole('button',{name:'版本 v1'})).toBeVisible();await page.getByRole('button',{name:'与当前比较'}).last().click();await expect(page.getByLabel('逐行版本差异')).toContainText('Persona E2E v2');
  await page.getByRole('button',{name:'版本 v1'}).click();await expect(page.getByRole('heading',{name:'版本预览 · v1'})).toBeVisible();await page.getByRole('button',{name:'回滚到此内容'}).click();const rollback=page.getByRole('dialog');await expect(rollback).toContainText('目标历史版本 v1');await rollback.getByRole('button',{name:'创建回滚版本'}).click();await expect(page.locator('.status-pill')).toContainText('当前版本 v3');await page.reload();await expect(page.locator('.status-pill')).toContainText('当前版本 v3');
  await page.goto('/simulation');await expect(page.getByRole('heading',{name:'行为模拟提示词'})).toBeVisible();await expect(page.getByText('定义机器人在社交环境中如何行动。')).toBeVisible();const simulation=page.getByLabel('行为模拟提示词');await simulation.fill(`${await simulation.inputValue()}\nSimulation E2E v2`);await page.getByRole('button',{name:'保存为新版本并启用'}).click();await expect(page.locator('.status-pill')).toContainText('当前版本 v2');await page.getByRole('button',{name:'与当前比较'}).last().click();await expect(page.getByLabel('逐行版本差异')).toContainText('Simulation E2E v2');await page.getByRole('button',{name:'版本 v1'}).click();await page.getByRole('button',{name:'回滚到此内容'}).click();await page.getByRole('dialog').getByRole('button',{name:'创建回滚版本'}).click();await expect(page.locator('.status-pill')).toContainText('当前版本 v3');
  await page.getByLabel('语言').selectOption('en-US');await page.setViewportSize({width:375,height:812});await page.reload();await expect(page.getByRole('heading',{name:'Simulation prompt'})).toBeVisible();await expect(page.locator('.prompt-editor')).toBeVisible();await page.getByRole('button',{name:'Compare with active'}).last().click();await expect(page.locator('.prompt-diff')).toBeVisible();expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain('Simulation E2E v2');expect(await page.evaluate(()=>JSON.stringify(sessionStorage))).not.toContain('Simulation E2E v2');await page.getByRole('button',{name:'Version v2'}).click();await expect(page.getByRole('heading',{name:/Version preview · v2/})).toBeVisible();await page.getByRole('button',{name:'Rollback to this content'}).click();await page.getByRole('dialog').getByRole('button',{name:'Create rollback version'}).click();await expect(page.locator('.status-pill')).toContainText('Active v4');
  await page.goto('/persona');await expect(page.getByRole('heading',{name:'Persona',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Hard Security Policy (read-only)'})).toBeVisible();await expect(page.getByText('Hard Security Policy is fixed by the trusted system and cannot be overridden by Persona or Simulation.')).toBeVisible();
  await openMobileNavigation(page,'en-US');await page.getByRole('button',{name:'Sign out'}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Confirm'}).click();await expect(page).toHaveURL(/\/login$/);expect((await page.request.get('/api/prompts/PERSONA/current')).status()).toBe(401);expect((await page.request.get('/api/prompts/security')).status()).toBe(401)
})

test('prompt optimistic conflict never silently replaces the active version', async ({ page }) => {
  await page.goto('/login');await page.getByLabel('管理员账号').fill(username);await page.getByLabel('密码').fill(password);await page.getByRole('button',{name:'登录'}).click();await expect(page.getByRole('heading',{name:'总览'})).toBeVisible();await page.goto('/persona');await expect(page.getByRole('heading',{name:'人格'})).toBeVisible()
  await page.route('**/api/prompts/PERSONA/versions',route=>route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({code:'STATE_CONFLICT',message:'Prompt changed'})}))
  const editor=page.getByLabel('人格');await editor.fill(`${await editor.inputValue()}\nconflicting draft`);await page.getByRole('button',{name:'保存为新版本并启用'}).click();await expect(page.getByRole('alert')).toContainText('提示词已在其他位置更新');await expect(editor).toHaveValue(/conflicting draft/);await expect(page.getByText('未保存更改',{exact:true})).toBeVisible()
})

test('social settings overrides and fake model management are secret-safe, persistent and responsive', async ({ page }) => {
  test.setTimeout(90_000)
  const conversation = '10000000-0000-0000-0000-000000000003'
  await page.goto('/login')
  await page.getByLabel('管理员账号').fill(username)
  await page.getByLabel('密码').fill(password)
  await page.getByRole('button', { name: '登录' }).click()
  await expect(page.getByRole('heading', { name: '总览' })).toBeVisible()

  await page.goto(`/social-settings?conversation=${conversation}`)
  await expect(page.getByRole('heading', { name: '社交设置' })).toBeVisible()
  await expect(page.getByText(/当前 reserved2 runtime 没有主动发言调度器/)).toBeVisible()
  const probability = page.getByRole('spinbutton', { name: '普通消息参与概率' })
  await probability.fill('0.35')
  await page.getByRole('button', { name: '保存全局设置' }).click()
  await expect(page.getByRole('status')).toContainText('设置已保存')
  const mentionRow = page.locator('.social-override-row').filter({ hasText: '被提及时唤醒' })
  await mentionRow.getByRole('combobox').selectOption('false')
  await page.getByRole('button', { name: '保存会话覆盖' }).click()
  await expect(mentionRow).toContainText('生效值: 否')
  let effective = await page.request.get(`/api/social-settings/conversations/${conversation}`)
  expect((await effective.json()).effective).toMatchObject({ mentionWake: false, ordinaryMessageProbability: 0.35 })

  // A stale save is surfaced as a conflict and does not overwrite the server's current revision.
  await mentionRow.getByRole('combobox').selectOption('true')
  await page.route(`**/api/social-settings/conversations/${conversation}`, async route => {
    if (route.request().method() === 'PATCH') await route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ code: 'STATE_CONFLICT', message: 'stale revision' }) })
    else await route.continue()
  })
  await page.getByRole('button', { name: '保存会话覆盖' }).click()
  await expect(page.getByRole('status')).toContainText('已在其他位置修改')
  await page.unrouteAll()
  await page.getByRole('button', { name: '清除全部覆盖' }).click()
  await expect(page.locator('.social-override-row').filter({ hasText: '被提及时唤醒' })).toContainText('生效值: 是')
  effective = await page.request.get(`/api/social-settings/conversations/${conversation}`)
  expect((await effective.json()).overrides).toEqual({})
  await page.reload()
  await expect(page.getByRole('spinbutton', { name: '普通消息参与概率' })).toHaveValue('0.35')

  await page.goto('/models')
  await expect(page.getByRole('heading', { name: '模型管理' })).toBeVisible()
  await expect(page.getByText('凭据状态: 未配置')).toBeVisible()
  await expect(page.getByText(/不支持 reasoning effort/)).toBeVisible()
  await page.getByLabel('模型 ID').fill('fixture-model-e2e')
  await page.getByLabel('最大输出 tokens').fill('512')
  await page.getByRole('button', { name: '保存配置' }).click()
  await expect(page.getByRole('status')).toContainText('配置已保存')
  const key = 'fake-only-e2e-secret-never-persist-in-browser'
  const secretInput = page.getByLabel(/API Key/)
  await secretInput.fill(key)
  await page.getByRole('button', { name: '保存凭据' }).click()
  await expect(secretInput).toHaveValue('')
  await expect(page.getByText('凭据状态: 已配置')).toBeVisible()
  expect(page.url()).not.toContain(key)
  expect(await page.evaluate(() => JSON.stringify({ local: Object.fromEntries(Object.keys(localStorage).map(k => [k, localStorage.getItem(k)])), session: Object.fromEntries(Object.keys(sessionStorage).map(k => [k, sessionStorage.getItem(k)])) }))).not.toContain(key)
  expect(await page.locator('body').innerText()).not.toContain(key)
  await page.getByRole('button', { name: '测试 Provider 连接' }).click()
  await expect(page.getByRole('status')).toContainText('成功')
  await page.reload()
  await expect(page.getByLabel('模型 ID')).toHaveValue('fixture-model-e2e')
  await expect(page.getByText('凭据状态: 已配置')).toBeVisible()

  await page.getByLabel('语言').selectOption('en-US')
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/social-settings')
  await expect(page.getByRole('heading', { name: 'Social settings' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.goto('/models')
  await expect(page.getByRole('heading', { name: 'Model management' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)

  await openMobileNavigation(page, 'en-US')
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: 'Confirm' }).click()
  await expect(page).toHaveURL(/\/login$/)
  expect((await page.request.get('/api/social-settings/global')).status()).toBe(401)
  expect((await page.request.get('/api/models/providers')).status()).toBe(401)
})

test('Sticker assets, slang lifecycle and truthful voice capability work only in the fake profile', async ({ page }) => {
  test.setTimeout(90_000)
  await page.goto('/login')
  await page.getByLabel('管理员账号').fill(username)
  await page.getByLabel('密码').fill(password)
  await page.getByRole('button', { name: '登录' }).click()
  await page.waitForURL('/')

  await page.goto('/stickers')
  await expect(page.getByRole('heading', { name: '表情管理' })).toBeVisible()
  await page.getByRole('button', { name: '扫描 / 导入' }).click()
  await expect(page.getByRole('button', { name: /fixture\.png/ })).toBeVisible()
  const previewUrl = await page.getByRole('button', { name: /fixture\.png/ }).locator('img').getAttribute('src')
  expect(previewUrl).toMatch(/^\/api\/stickers\/[0-9a-f-]+\/content\?v=/)
  const preview = await page.request.get(previewUrl!)
  expect(preview.status()).toBe(200)
  expect(preview.headers()['content-type']).toContain('image/png')
  expect(preview.headers()['x-content-type-options']).toBe('nosniff')
  await page.getByRole('button', { name: /fixture\.png/ }).click()
  await page.getByLabel('标签（逗号分隔）').fill('开心, 测试')
  await page.getByLabel('使用备注').fill('E2E 本地夹具')
  await page.getByRole('button', { name: '保存元数据' }).click()
  await expect(page.getByRole('status')).toContainText('已保存')
  await page.getByRole('button', { name: '已停用' }).click()
  await expect(page.getByRole('button', { name: /fixture\.png.*已停用/ })).toBeVisible()
  const disabled = await page.request.get('/api/stickers/admin?enabled=false')
  expect((await disabled.json()).items).toHaveLength(1)
  const enabled = await page.request.get('/api/stickers/admin?enabled=true')
  expect((await enabled.json()).items).toHaveLength(0)
  await expect(page.getByText(/没有管理员测试发送安全入口/)).toBeVisible()

  await page.goto('/slang')
  await expect(page.getByRole('heading', { name: '俚语审核' })).toBeVisible()
  await page.getByLabel('词条', { exact: true }).fill('E2E 已确认词')
  await page.getByLabel('释义', { exact: true }).fill('人工添加的测试词')
  await page.getByRole('button', { name: '添加候选词' }).click()
  await expect(page.getByRole('row', { name: /E2E 已确认词/ })).toBeVisible()
  await page.getByRole('row', { name: /E2E 已确认词/ }).getByRole('button', { name: '确认' }).click()
  await expect(page.getByRole('row', { name: /E2E 已确认词/ })).toHaveCount(0)
  await page.getByLabel('状态').selectOption('CONFIRMED')
  await expect(page.getByRole('row', { name: /E2E 已确认词/ })).toBeVisible()
  await page.getByLabel('状态').selectOption('CANDIDATE')
  await page.getByLabel('词条', { exact: true }).fill('E2E 已拒绝词')
  await page.getByLabel('释义', { exact: true }).fill('不得进入 Agent 检索')
  await page.getByRole('button', { name: '添加候选词' }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('row', { name: /E2E 已拒绝词/ }).getByRole('button', { name: '拒绝' }).click()
  await page.getByLabel('状态').selectOption('REJECTED')
  await expect(page.getByRole('row', { name: /E2E 已拒绝词/ })).toBeVisible()
  await page.getByLabel('搜索词条与释义').fill('E2E 已拒绝词')
  await expect(page.getByRole('row', { name: /E2E 已拒绝词/ })).toBeVisible()

  await page.goto('/voice')
  await expect(page.getByRole('heading', { name: '语音能力' })).toBeVisible()
  await expect(page.getByText('record', { exact: true })).toBeVisible()
  await expect(page.getByText('不支持', { exact: true }).first()).toBeVisible()
  const voiceStatus = await page.request.get('/api/voice/capabilities')
  expect(voiceStatus.headers()['cache-control']).toContain('no-store')
  expect(await voiceStatus.json()).toMatchObject({ status: 'PARTIAL_METADATA_ONLY', transcription: false, tts: false, voiceSend: false, rateSetting: false })

  await page.setViewportSize({ width: 375, height: 812 })
  for (const [path, heading] of [['/stickers', '表情管理'], ['/slang', '俚语审核'], ['/voice', '语音能力']] as const) {
    await page.goto(path)
    await expect(page.getByRole('heading', { name: heading })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.goto('/')
  await openMobileNavigation(page, 'zh-CN')
  await page.getByRole('button', { name: '退出登录' }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: '确认' }).click()
  await expect(page).toHaveURL(/\/login$/)
  expect((await page.request.get('/api/stickers/admin')).status()).toBe(401)
  expect((await page.request.get('/api/slang/admin')).status()).toBe(401)
  expect((await page.request.get('/api/voice/capabilities')).status()).toBe(401)
})
