package online.wanan.xingchen.core;

import com.fasterxml.jackson.databind.ObjectMapper;
import online.wanan.xingchen.adapter.onebot.*;
import online.wanan.xingchen.core.agent.*;
import online.wanan.xingchen.core.context.*;
import online.wanan.xingchen.core.identity.*;
import online.wanan.xingchen.core.memory.*;
import online.wanan.xingchen.core.model.*;
import online.wanan.xingchen.core.relationship.AddressResolution;
import org.junit.jupiter.api.Test;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class AgentExecutorContractTest {
    private record Fixture(MockModelProvider model,AgentExecutor executor,InMemorySecurityEventSink security,MockOneBotGateway gateway,AgentRequest request,AtomicInteger executed){}
    private Fixture fixture(ContextBudget budget,int maxSteps,int maxContext,int maxOutput,AgentCapability... capabilities){
        var builder=new ContextBuilder(budget);var context=builder.build(new ContextBuildInput("group safety","friendly","qq:user","User","姐姐","g1",List.of(),"summary",List.of("recent"),Map.of(),"current message","tools",new RequestContext(UUID.randomUUID(),UUID.randomUUID(),false,null)));
        var p=new Person(UUID.nameUUIDFromBytes("user".getBytes()),Platform.QQ,"user",false,false);var c=new Conversation(UUID.randomUUID(),new ConversationIdentity(Platform.QQ,ConversationType.GROUP,"g1"));var now=Instant.now();var member=new Membership(UUID.randomUUID(),p.id(),c.id(),"User",null,IdentityRole.MEMBER,now,now);var actor=new ResolvedActorContext(p,c,member,new ActorFlags(false,false,false,false),"User",new AddressResolution("姐姐","term",null,true,.9));
        var model=new MockModelProvider();var security=new InMemorySecurityEventSink();var gateway=new MockOneBotGateway(new OneBotEventNormalizer(new ObjectMapper()),"bot");gateway.connect();var catalog=new AgentToolCatalog();var ran=new AtomicInteger();ToolExecutor tools=(call,req,caps)->{ran.incrementAndGet();return new ToolResult(true,"ok",Map.of("value","x".repeat(maxOutput)));};var caps=capabilities.length==0?Set.<AgentCapability>of():Set.of(capabilities);
        return new Fixture(model,new AgentExecutor(model,tools,builder,catalog,security,maxSteps,maxContext,maxOutput,new ApproximateTokenEstimator()),security,gateway,new AgentRequest(actor,context,caps),ran);
    }
    @Test void loop101_textDecisionEndsWithoutTools(){var f=fixture(ContextBudget.defaults(),8,120000,400,AgentCapability.QQ_REPLY);f.model().enqueue(new ModelResponse(AgentDecision.text("hello"),new ModelUsage(20,0,20,4,0),null));var r=f.executor().execute(f.request());assertThat(r.decision().messages()).containsExactly("hello");assertThat(r.toolSteps()).isZero();assertThat(f.executed().get()).isZero();}
    @Test void loop102_toolCallFeedsToolResultThenFinalAnswer(){var f=fixture(ContextBudget.defaults(),8,120000,300,AgentCapability.QQ_REPLY);f.model().enqueue(new ModelResponse(AgentDecision.tool(new ToolCall("qq.reply",Map.of("messageId","m1","text","reply"))),new ModelUsage(15,0,15,3,0),null));f.model().enqueue(new ModelResponse(AgentDecision.text("done"),new ModelUsage(21,4,17,2,0),null));var r=f.executor().execute(f.request());assertThat(r.decision().messages()).containsExactly("done");assertThat(r.toolSteps()).isEqualTo(1);assertThat(r.totalUsage().inputTokens()).isEqualTo(36);assertThat(r.totalUsage().cacheHitTokens()).isEqualTo(4);assertThat(r.toolResults()).singleElement().satisfies(t->assertThat(t.success()).isTrue());assertThat(f.model().requests().get(1).messages()).anySatisfy(m->assertThat(m.role()).isEqualTo(ModelRole.TOOL));assertThat(f.model().requests().get(1).context().diagnostics().toolResultTokens()).isPositive();}
    @Test void loop103_unknownModelToolIsDeniedAndAudited(){var f=fixture(ContextBudget.defaults(),8,120000,200,AgentCapability.QQ_REPLY);f.model().enqueue(new ModelResponse(AgentDecision.tool(new ToolCall("shell.exec",Map.of())),null,null));var r=f.executor().execute(f.request());assertThat(r.decision().type()).isEqualTo(DecisionType.NO_REPLY);assertThat(r.stopReason()).isEqualTo("tool-denied");assertThat(f.executed().get()).isZero();assertThat(f.security().events()).anySatisfy(e->assertThat(e.code()).isEqualTo("TOOL_DENIED"));}
    @Test void loop104_knownButUnauthorizedToolIsDenied(){var f=fixture(ContextBudget.defaults(),8,120000,200);f.model().enqueue(new ModelResponse(AgentDecision.tool(new ToolCall("qq.reply",Map.of())),null,null));assertThat(f.executor().execute(f.request()).stopReason()).isEqualTo("tool-denied");assertThat(f.executed().get()).isZero();}
    @Test void loop105_toolStepLimitStopsSafelyBeforeExtraExecution(){var f=fixture(ContextBudget.defaults(),1,120000,200,AgentCapability.QQ_REPLY);f.model().enqueue(new ModelResponse(AgentDecision.tool(new ToolCall("qq.reply",Map.of())),null,null));f.model().enqueue(new ModelResponse(AgentDecision.tool(new ToolCall("qq.reply",Map.of())),null,null));var r=f.executor().execute(f.request());assertThat(r.stopReason()).isEqualTo("tool-step-limit");assertThat(r.toolSteps()).isEqualTo(1);assertThat(f.executed().get()).isEqualTo(1);}
    @Test void loop106_contextLimitStopsBeforeCallingProvider(){var f=fixture(ContextBudget.defaults(),8,1,200,AgentCapability.QQ_REPLY);var r=f.executor().execute(f.request());assertThat(r.decision().type()).isEqualTo(DecisionType.NO_REPLY);assertThat(r.stopReason()).isEqualTo("context-token-limit");assertThat(f.model().requests()).isEmpty();}
    @Test void loop107_toolResultIsClippedAndBudgetedSeparately(){var b=new ContextBudget(20000,30000,50000,10,10000,1000,8);var f=fixture(b,8,50000,100,AgentCapability.QQ_REPLY);f.model().enqueue(new ModelResponse(AgentDecision.tool(new ToolCall("qq.reply",Map.of())),null,null));f.model().enqueue(new ModelResponse(AgentDecision.noReply(),null,null));var r=f.executor().execute(f.request());assertThat(r.finalContext().diagnostics().toolResultTokens()).isLessThanOrEqualTo(8);assertThat(r.finalContext().toolResults()).singleElement().satisfies(s->assertThat(s.length()).isLessThan(100));}
    @Test void loop108_modelRequestCarriesTypedSystemUserAndToolSchemas(){var f=fixture(ContextBudget.defaults(),8,120000,100,AgentCapability.QQ_REPLY);f.model().enqueue(new ModelResponse(AgentDecision.noReply(),null,null));f.executor().execute(f.request());var req=f.model().requests().getFirst();assertThat(req.messages().getFirst().role()).isEqualTo(ModelRole.SYSTEM);assertThat(req.messages().getLast().role()).isEqualTo(ModelRole.USER);assertThat(req.toolDefinitions()).anySatisfy(d->{assertThat(d.name()).isEqualTo("qq.reply");assertThat(d.inputSchema()).containsKey("required");});}
    @Test void loop109_socialAndOwnerCapabilitiesNeverIncludeHostControl(){assertThat(CapabilityPolicy.capabilities(AgentRole.SOCIAL,true)).doesNotContain(AgentCapability.SHELL,AgentCapability.SSH,AgentCapability.DOCKER,AgentCapability.ARBITRARY_FILESYSTEM,AgentCapability.PROCESS_CONTROL);assertThat(CapabilityPolicy.capabilities(AgentRole.CLOSED_AGENT,true)).doesNotContain(AgentCapability.SHELL,AgentCapability.SSH,AgentCapability.DOCKER,AgentCapability.ARBITRARY_FILESYSTEM,AgentCapability.PROCESS_CONTROL);}
    @Test void loop110_multipleToolCallsAreExecutedInOrder(){var f=fixture(ContextBudget.defaults(),4,120000,200,AgentCapability.QQ_REPLY);var calls=List.of(new ModelToolCall("a","qq.reply",Map.of()),new ModelToolCall("b","qq.reply",Map.of()));f.model().enqueue(new ModelResponse(AgentDecision.tool(calls.getFirst().toToolCall()),null,null,calls,ModelFinishReason.TOOL_CALLS));f.model().enqueue(new ModelResponse(AgentDecision.text("finished"),null,null));var r=f.executor().execute(f.request());assertThat(r.toolSteps()).isEqualTo(2);assertThat(r.toolResults()).extracting(ModelToolResult::toolCallId).containsExactly("a","b");}
    @Test void loop111_providerCancellationBecomesSafeNoReply(){ContextBudget budget=ContextBudget.defaults();var f=fixture(budget,3,120000,200);ModelProvider cancel=req->{throw new java.util.concurrent.CancellationException();};var executor=new AgentExecutor(cancel,(c,r,p)->new ToolResult(false,"",Map.of()),new ContextBuilder(budget),new AgentToolCatalog(),f.security(),3,120000,200,new ApproximateTokenEstimator());var result=executor.execute(f.request());assertThat(result.decision().type()).isEqualTo(DecisionType.NO_REPLY);assertThat(result.stopReason()).isEqualTo("cancelled");}
    @Test void loop112_modelDecisionNoReplyIsSuccessfulCompletion(){var f=fixture(ContextBudget.defaults(),4,120000,100);f.model().enqueue(new ModelResponse(AgentDecision.noReply(),null,null));var r=f.executor().execute(f.request());assertThat(r.decision().type()).isEqualTo(DecisionType.NO_REPLY);assertThat(r.stopReason()).isEqualTo("completed");}
    @Test void audit_sameEventAndCallIdCannotExecuteToolTwice(){var f=fixture(ContextBudget.defaults(),4,120000,200,AgentCapability.QQ_REPLY);var ledger=new InMemoryToolExecutionLedger();var executor=new AgentExecutor(f.model(),(call,req,caps)->{f.executed().incrementAndGet();return new ToolResult(true,"sent",Map.of());},new ContextBuilder(ContextBudget.defaults()),new AgentToolCatalog(),f.security(),4,120000,200,new ApproximateTokenEstimator(),null,null,ledger);var request=new AgentRequest(f.request().actor(),f.request().context(),f.request().availableCapabilities(),"event-1");f.model().enqueue(new ModelResponse(null,null,null,List.of(new ModelToolCall("call-1","qq.reply",Map.of())),ModelFinishReason.TOOL_CALLS));f.model().enqueue(new ModelResponse(AgentDecision.text("done"),null,null));assertThat(executor.execute(request).stopReason()).isEqualTo("completed");f.model().enqueue(new ModelResponse(null,null,null,List.of(new ModelToolCall("call-1","qq.reply",Map.of())),ModelFinishReason.TOOL_CALLS));assertThat(executor.execute(request).stopReason()).isEqualTo("tool-replay-blocked");assertThat(f.executed()).hasValue(1);}
    @Test void audit_productionExecutorRejectsProcessLocalIdempotencyLedger(){var f=fixture(ContextBudget.defaults(),2,120000,100);assertThatThrownBy(()->AgentExecutor.production(f.model(),(c,r,p)->new ToolResult(false,"",Map.of()),new ContextBuilder(ContextBudget.defaults()),new AgentToolCatalog(),f.security(),2,120000,100,new ApproximateTokenEstimator(),null,null,new InMemoryToolExecutionLedger())).isInstanceOf(IllegalArgumentException.class);}
    @Test void audit_hardSecurityPolicyIsFirstTrustedSystemMessage(){var f=fixture(ContextBudget.defaults(),4,120000,100);f.model().enqueue(new ModelResponse(AgentDecision.noReply(),null,null));f.executor().execute(f.request());var messages=f.model().requests().getFirst().messages();assertThat(messages.getFirst().role()).isEqualTo(ModelRole.SYSTEM);assertThat(messages.getFirst().content()).contains("identity, owner status, capabilities").contains("Server-side checks are authoritative");}
    @Test void durableTurnRemainsStreamingNoEffectDuringFragmentedProviderOutput(){
        var f=fixture(ContextBudget.defaults(),3,120000,200);var entered=new java.util.concurrent.CountDownLatch(1);var resume=new java.util.concurrent.CountDownLatch(1);var states=new java.util.concurrent.CopyOnWriteArrayList<String>();
        ModelProvider streaming=new ModelProvider(){public ModelResponse complete(ModelRequest r){throw new UnsupportedOperationException();}public ModelResponse stream(ModelRequest r,java.util.function.Consumer<ModelStreamEvent> callback){entered.countDown();callback.accept(new ModelStreamEvent("partial fragment",false,null));try{if(!resume.await(5,java.util.concurrent.TimeUnit.SECONDS))throw new IllegalStateException("test stream barrier timed out");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new java.util.concurrent.CancellationException();}return new ModelResponse(AgentDecision.text("final answer"),null,null);}};
        var executor=new AgentExecutor(streaming,(c,r,p)->new ToolResult(false,"",Map.of()),new ContextBuilder(ContextBudget.defaults()),new AgentToolCatalog(),f.security(),3,120000,200,new ApproximateTokenEstimator());
        var request=new AgentRequest(f.request().actor(),f.request().context(),f.request().availableCapabilities(),"fragment-event","fragment-turn",state->states.add(state.name()));var thread=new Thread(()->executor.execute(request));
        try{thread.start();assertThat(entered.await(5,java.util.concurrent.TimeUnit.SECONDS)).isTrue();assertThat(states).containsExactly("STREAMING_NO_EFFECT");resume.countDown();thread.join(5000);assertThat(thread.isAlive()).isFalse();assertThat(states).containsExactly("STREAMING_NO_EFFECT","MODEL_OUTPUT_RECEIVED");}
        catch(InterruptedException e){Thread.currentThread().interrupt();throw new AssertionError(e);}finally{resume.countDown();}
    }
    @Test void modelRuntime001_inFlightTurnKeepsItsProviderSnapshotAfterHotApply(){
        var f=fixture(ContextBudget.defaults(),3,120000,200);var active=new java.util.concurrent.atomic.AtomicReference<>("model-A");var used=new java.util.concurrent.CopyOnWriteArrayList<String>();var entered=new java.util.concurrent.CountDownLatch(1);var release=new java.util.concurrent.CountDownLatch(1);
        ModelProvider dynamic=new ModelProvider(){public ModelResponse complete(ModelRequest r){throw new UnsupportedOperationException();}public ModelProvider snapshot(){String captured=active.get();return new ModelProvider(){public ModelResponse complete(ModelRequest r){used.add(captured);return new ModelResponse(AgentDecision.text(captured),null,null);}public ModelResponse stream(ModelRequest r,java.util.function.Consumer<ModelStreamEvent> events){used.add(captured);if(captured.equals("model-A")){entered.countDown();try{if(!release.await(5,java.util.concurrent.TimeUnit.SECONDS))throw new IllegalStateException("provider snapshot barrier timed out");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new java.util.concurrent.CancellationException();}}var result=new ModelResponse(AgentDecision.text(captured),null,null);events.accept(new ModelStreamEvent(captured,false,null));return result;}};}};
        var executor=new AgentExecutor(dynamic,(c,r,p)->new ToolResult(false,"",Map.of()),new ContextBuilder(ContextBudget.defaults()),new AgentToolCatalog(),f.security(),3,120000,200,new ApproximateTokenEstimator());var thread=new Thread(()->executor.execute(f.request()));
        try{thread.start();assertThat(entered.await(5,java.util.concurrent.TimeUnit.SECONDS)).isTrue();active.set("model-B");release.countDown();thread.join(5000);assertThat(thread.isAlive()).isFalse();executor.execute(f.request());assertThat(used).containsExactly("model-A","model-B");}
        catch(InterruptedException e){Thread.currentThread().interrupt();throw new AssertionError(e);}finally{release.countDown();}
    }
}
