package online.wanan.xingchen.core;

import online.wanan.xingchen.core.context.*;
import online.wanan.xingchen.core.memory.*;
import online.wanan.xingchen.core.model.*;
import online.wanan.xingchen.core.prompt.*;
import org.junit.jupiter.api.Test;
import java.time.Instant;
import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;

class ContextPipelineContractTest {
    @Test void ctx101_runtimePromptEngineKeepsLayerVersionsAndTextSeparate(){var p=new PromptProfile(UUID.randomUUID(),"p","SIM RULE","PERSONA STYLE");var s=new PromptEngine().assemble(p,3,8);assertThat(s.simulationVersion()).isEqualTo(3);assertThat(s.personaVersion()).isEqualTo(8);assertThat(s.simulationPrompt()).isNotEqualTo(s.personaPrompt());}
    @Test void ctx102_contextSectionsAreComposedInRequiredOrder(){var req=req();var input=new ContextBuildInput("SIM","PERSONA","qq:100","Irena","姐姐","g1",List.of(),"SUMMARY",List.of("RECENT"),Map.of("task","open"),"CURRENT","TOOLS",req);var result=new ContextBuilder(new ContextBudget(200,300,400,4,40,20)).build(input);String rendered=result.renderSections();assertThat(rendered.indexOf("[Simulation Prompt]")).isLessThan(rendered.indexOf("[Persona Prompt]"));assertThat(rendered.indexOf("[Persona Prompt]")).isLessThan(rendered.indexOf("[Identity]"));assertThat(rendered.indexOf("[Identity]")).isLessThan(rendered.indexOf("[Relationship]"));assertThat(rendered.indexOf("[Relationship]")).isLessThan(rendered.indexOf("[Relevant Memories]"));assertThat(rendered.indexOf("[Relevant Memories]")).isLessThan(rendered.indexOf("[Conversation Summary]"));assertThat(rendered.indexOf("[Conversation Summary]")).isLessThan(rendered.indexOf("[Agent Tools]"));assertThat(rendered.indexOf("[Agent Tools]")).isLessThan(rendered.indexOf("[Recent Messages]"));assertThat(rendered.indexOf("[Recent Messages]")).isLessThan(rendered.indexOf("[Current Message]"));}
    @Test void ctx103_identityBlockContainsIdDisplayAndAssistantAddress(){var result=new ContextBuilder(new ContextBudget(200,300,400,5,40,20)).build(new ContextBuildInput("s","p","qq:123","伊蕾娜","姐姐","g1",List.of(),"",List.of(),Map.of(),"hi","",req()));assertThat(result.identityBlock()).contains("actorId=qq:123","displayName=伊蕾娜");assertThat(result.relationshipBlock()).contains("assistantAddress=姐姐");}
    @Test void ctx104_diagnosticsAccountForLayersAndIncludedMemoryIds(){UUID p=UUID.randomUUID(),c=UUID.randomUUID();var m=memory(p,c,"remembered detail");var result=new ContextBuilder(new ContextBudget(200,300,400,10,50,20)).build(new ContextBuildInput("simulate","persona","qq:1","name","姐姐","g1",List.of(m),"summary",List.of("recent"),Map.of(),"now","tool",reqFor(p,c)));assertThat(result.diagnostics().personaTokens()).isPositive();assertThat(result.diagnostics().simulationTokens()).isPositive();assertThat(result.diagnostics().includedMemoryIds()).containsExactly(m.id());assertThat(result.diagnostics().totalEstimatedTokens()).isEqualTo(result.estimatedTokens());assertThat(result.diagnostics().lifecycleState()).isEqualTo(result.lifecycleStatus());}
    @Test void ctx105_contextRespectsRecentMemorySummaryAndHardBudgets(){UUID p=UUID.randomUUID(),c=UUID.randomUUID();var memories=new ArrayList<Memory>();for(int i=0;i<8;i++)memories.add(memory(p,c,"fact-long-value-"+i));var result=new ContextBuilder(new ContextBudget(35,55,90,3,10,8)).build(new ContextBuildInput("sim","persona","qq:1","name","姐姐","g1",memories,"a long summary that will be clipped to its budget",List.of("old","recent one","recent two","recent three"),Map.of(),"hello","tool",reqFor(p,c)));assertThat(result.recentMessages()).hasSizeLessThanOrEqualTo(3);assertThat(result.diagnostics().summaryTokens()).isLessThanOrEqualTo(8);assertThat(result.diagnostics().memoryTokens()).isLessThanOrEqualTo(10);assertThat(result.estimatedTokens()).isLessThanOrEqualTo(90);assertThat(result.diagnostics().excludedMemoryCount()).isGreaterThan(0);}
    private RequestContext req(){return new RequestContext(UUID.randomUUID(),UUID.randomUUID(),false,null);}private RequestContext reqFor(UUID p,UUID c){return new RequestContext(p,c,false,null);}
    private Memory memory(UUID p,UUID c,String value){var now=Instant.now();return new Memory(UUID.randomUUID(),MemoryType.PERSON,p,null,null,value,MemoryScope.PERSON_GLOBAL,p.toString(),.9,.9,true,now,now,null,null,MemoryStatus.ACTIVE);}
}
