package online.wanan.xingchen.core;

import com.fasterxml.jackson.databind.ObjectMapper;
import online.wanan.xingchen.adapter.onebot.*;
import online.wanan.xingchen.core.agent.*;
import online.wanan.xingchen.core.context.*;
import online.wanan.xingchen.core.conversation.*;
import online.wanan.xingchen.core.identity.*;
import online.wanan.xingchen.core.memory.*;
import online.wanan.xingchen.core.model.*;
import online.wanan.xingchen.core.prompt.*;
import online.wanan.xingchen.core.relationship.*;
import online.wanan.xingchen.storage.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.TestInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;
import java.time.Instant;
import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.NONE)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@DirtiesContext(classMode=DirtiesContext.ClassMode.AFTER_CLASS)
class ConversationOrchestratorE2ETest {
    private static final java.nio.file.Path TEST_DB=TestSqliteDatabase.create("conversation-e2e");
    @DynamicPropertySource static void isolatedDatabase(DynamicPropertyRegistry properties){properties.add("spring.datasource.url",()->TestSqliteDatabase.jdbcUrl(TEST_DB));properties.add("xingchen.memory.database-path",()->TEST_DB.toAbsolutePath().toString());}
    @Autowired IncomingMessageStore messageStore;@Autowired ContextDiagnosticsStore diagnostics;@Autowired org.springframework.jdbc.core.JdbcTemplate jdbc;
    @AfterAll void cleanDatabase(){TestSqliteDatabase.clean(jdbc,TEST_DB);}
    record Fixture(ConversationOrchestrator orchestrator,IdentityRegistry registry,RelationshipTermRegistry terms,
                   InMemoryMemoryRepository memories,MockOneBotGateway gateway,MockModelProvider model,
                   InMemorySessionLifecycleManager lifecycle,ConversationWindow window,OneBotEventNormalizer normalizer) {}
    private Fixture fixture(ContextBudget budget,Set<String> owners){var registry=new IdentityRegistry("bot",owners);var terms=new RelationshipTermRegistry();var memories=new InMemoryMemoryRepository();var builder=new ContextBuilder(budget);var model=new MockModelProvider();var catalog=new AgentToolCatalog();var gateway=new MockOneBotGateway(new OneBotEventNormalizer(new ObjectMapper()),"bot");gateway.connect();var lifecycle=new InMemorySessionLifecycleManager(builder);var window=new ConversationWindow();var resolver=new IdentityResolver(registry,new AddressResolver(),terms,"bot");var prompt=new PromptEngine().assemble(new PromptProfile(UUID.randomUUID(),"test","Keep group safety.","Friendly.") ,1,1);var agent=new SocialAgent(model,catalog);var orch=new ConversationOrchestrator(resolver,messageStore,new MemoryRetriever(memories,new ApproximateTokenEstimator()),memories,new MemoryPolicy(),builder,prompt,agent,CapabilityPolicy.capabilities(AgentRole.SOCIAL,false),new MockToolExecutor(gateway,catalog),gateway,window,new MockSummaryProvider(),lifecycle,diagnostics);return new Fixture(orch,registry,terms,memories,gateway,model,lifecycle,window,new OneBotEventNormalizer(new ObjectMapper()));}
    private PlatformEvent event(Fixture f,String user,String group,String messageId,String text,String name){String json="""
      {"post_type":"message","message_type":"group","self_id":"bot","user_id":"%s","group_id":"%s","time":100000002,"message_id":"%s","sender":{"user_id":"%s","nickname":"%s","card":"","role":"member"},"message":[{"type":"text","data":{"text":"%s"}}]}
      """.formatted(user,group,messageId,user,name,text);return f.normalizer().normalize(json,Set.of("owner"));}
    private RelationshipTerm address(Fixture f,String target,String value,ScopeType scope,String scopeId){var bot=f.registry().identify(Platform.QQ,"bot");var p=f.registry().identify(Platform.QQ,target);var now=Instant.now();var term=new RelationshipTerm(UUID.randomUUID(),bot.id(),p.id(),RelationshipType.ADDRESS_AS,value,scope,scopeId,true,.99,"setup",now,now);f.terms().save(term);return term;}
    private Memory memory(UUID person,UUID conversation,String text,MemoryScope scope){var now=Instant.now();return new Memory(UUID.randomUUID(),MemoryType.PERSON,person,scope==MemoryScope.CONVERSATION?conversation:null,null,text,scope,scope==MemoryScope.CONVERSATION?conversation.toString():person.toString(),.95,.9,true,now,now,null,null,MemoryStatus.ACTIVE);}
    @Test void e2e101_messageFlowsThroughIdentityContextMockModelAndQQSender(){var f=fixture(ContextBudget.defaults(),Set.of("owner"));address(f,"100","姐姐",ScopeType.GLOBAL,"");var candidate=new MemoryCandidate(null,MemoryType.PERSON,MemoryScope.PERSON_GLOBAL==null?"":"I like cats",MemoryScope.PERSON_GLOBAL,null,null,.95,.8,true,"m1");f.model().enqueue(new ModelResponse(AgentDecision.text("你好，姐姐。"),new ModelUsage(30,0,30,8,0),candidate));var result=f.orchestrator().handle(event(f,"100","g1","m-e2e-1","你好","伊蕾娜"));assertThat(result.decision().messages()).containsExactly("你好，姐姐。");assertThat(result.actor().actorId()).isEqualTo("qq:100");assertThat(result.actor().displayIdentity()).isEqualTo("伊蕾娜");assertThat(result.actor().address()).isEqualTo("姐姐");assertThat(result.context().relationshipBlock()).contains("assistantAddress=姐姐");assertThat(result.context().renderSections()).contains("Keep group safety.","Friendly.","actorId=qq:100","assistantAddress=姐姐");assertThat(f.gateway().sent()).singleElement().satisfies(s->assertThat(s.content()).isEqualTo("你好，姐姐。"));assertThat(result.memoryEvaluation().memory().subjectPersonId()).isEqualTo(result.actor().person().id());assertThat(f.memories().sources(result.memoryEvaluation().memory().id())).singleElement().satisfies(s->assertThat(s.actorPersonId()).isEqualTo(result.actor().person().id()));}
    @Test void msg101_duplicatePlatformMessageIsIdempotentAndDoesNotResend(){var f=fixture(ContextBudget.defaults(),Set.of());f.model().enqueue(new ModelResponse(AgentDecision.text("reply"),null,null));var e=event(f,"u1","g1","duplicate-1","hi","N");var first=f.orchestrator().handle(e);var second=f.orchestrator().handle(e);assertThat(first.duplicate()).isFalse();assertThat(second.duplicate()).isTrue();assertThat(f.gateway().sent()).hasSize(1);assertThat(f.model().receivedContexts()).hasSize(1);}
    @Test void event102_lateOneBotEventIsArchivedButDoesNotAdvanceConversation(){var f=fixture(ContextBudget.defaults(),Set.of());f.model().enqueue(new ModelResponse(AgentDecision.text("first"),null,null));var newest=f.normalizer().normalize("""
      {"post_type":"message","message_type":"group","self_id":"bot","user_id":"u2","group_id":"g-order","time":100000004,"message_id":"m-new","sender":{"user_id":"u2","nickname":"N","role":"member"},"message":[{"type":"text","data":{"text":"newer"}}]}
      """.strip(),Set.of());var older=f.normalizer().normalize("""
      {"post_type":"message","message_type":"group","self_id":"bot","user_id":"u2","group_id":"g-order","time":100000003,"message_id":"m-old","sender":{"user_id":"u2","nickname":"N","role":"member"},"message":[{"type":"text","data":{"text":"older"}}]}
      """.strip(),Set.of());f.orchestrator().handle(newest);var late=f.orchestrator().handle(older);assertThat(late.ignored()).isTrue();assertThat(late.decision()).isNull();assertThat(f.gateway().sent()).hasSize(1);var row=jdbc.queryForMap("SELECT last_timestamp FROM event_order_state WHERE platform='QQ' AND conversation_id=?",late.actor().conversation().id().toString());assertThat(row.get("last_timestamp").toString()).isEqualTo(newest.timestamp().toString());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM messages WHERE platform_message_id IN ('m-new','m-old')",Integer.class)).isEqualTo(2);}
    @Test void scope101_groupMemoryDoesNotLeakButGlobalAddressDoes(){var f=fixture(ContextBudget.defaults(),Set.of());var person=f.registry().identify(Platform.QQ,"A");var g1=f.registry().identifyConversation(new ConversationIdentity(Platform.QQ,ConversationType.GROUP,"g1"));var m=memory(person.id(),g1.id(),"A likes group one meme",MemoryScope.CONVERSATION);f.memories().save(m,List.of(new MemorySource(m.id(),"QQ",g1.id(),"source-g1",person.id(),Instant.now())));address(f,"A","姐姐",ScopeType.GLOBAL,"");f.model().enqueue(new ModelResponse(AgentDecision.text("嗨"),null,null));var result=f.orchestrator().handle(event(f,"A","g2","scope-1","在吗","A"));assertThat(result.context().memories()).isEmpty();assertThat(result.actor().address()).isEqualTo("姐姐");}
    @Test void rollover101_recentWindowRollsOverButIdentityAddressMemoryAndSummaryRemain(){var f=fixture(new ContextBudget(25,65,300,20,40,15),Set.of());address(f,"100","姐姐",ScopeType.GLOBAL,"");var person=f.registry().identify(Platform.QQ,"100");var longTerm=memory(person.id(),null,"likes cats",MemoryScope.PERSON_GLOBAL);f.memories().save(longTerm,List.of(new MemorySource(longTerm.id(),"QQ",UUID.randomUUID(),"source-memory",person.id(),Instant.now())));f.model().enqueue(new ModelResponse(AgentDecision.text("记得你呀"),null,null));String longText="older conversation context ".repeat(12);var result=f.orchestrator().handle(event(f,"100","g1","roll-1",longText,"Irena"));assertThat(result.rolledOver()).isTrue();assertThat(result.context().recentMessages()).isEmpty();assertThat(result.context().conversationSummary()).contains("Recent conversation:");assertThat(result.context().actorId()).isEqualTo("qq:100");assertThat(result.context().relationshipAddress()).isEqualTo("姐姐");assertThat(result.context().memories()).extracting(Memory::id).contains(longTerm.id());assertThat(f.lifecycle().loadHandoff(result.actor().conversation().id().toString())).isNotNull();}
    @Test void owner101_projectDecisionAcceptedButMemberDecisionDowngradedWithProvenance(){var f=fixture(ContextBudget.defaults(),Set.of("owner"));f.model().enqueue(new ModelResponse(AgentDecision.noReply(),null,new MemoryCandidate(null,MemoryType.PROJECT,"Project A should pause",MemoryScope.PROJECT,null,"project-A",.95,.9,true,"owner-msg")));f.model().enqueue(new ModelResponse(AgentDecision.noReply(),null,new MemoryCandidate(null,MemoryType.PROJECT,"Project A should pause",MemoryScope.PROJECT,null,"project-A",.95,.9,true,"member-msg")));var owner=f.orchestrator().handle(event(f,"owner","g1","owner-1","这个项目先停。","Owner"));var member=f.orchestrator().handle(event(f,"123","g1","member-1","这个项目先停。","Member"));assertThat(owner.memoryEvaluation().outcome()).isEqualTo(MemoryPolicy.Outcome.ACCEPT);assertThat(owner.memoryEvaluation().memory().scopeType()).isEqualTo(MemoryScope.PROJECT);assertThat(member.memoryEvaluation().outcome()).isEqualTo(MemoryPolicy.Outcome.DOWNGRADE);assertThat(member.memoryEvaluation().memory().scopeType()).isEqualTo(MemoryScope.CONVERSATION);assertThat(f.memories().sources(member.memoryEvaluation().memory().id())).singleElement().satisfies(s->assertThat(s.actorPersonId()).isEqualTo(member.actor().person().id()));}
    @Test void tool101_agentToolCallExecutesOnlyThroughMockGateway(){var f=fixture(ContextBudget.defaults(),Set.of());f.model().enqueue(new ModelResponse(AgentDecision.tool(new ToolCall("qq.send",Map.of("target","g1","text","tool reply","kind","group"))),null,null));var result=f.orchestrator().handle(event(f,"u","g1","tool-1","send please","N"));assertThat(result.decision().type()).isEqualTo(DecisionType.TOOL_CALL);assertThat(result.toolResult().success()).isTrue();assertThat(f.gateway().sent()).singleElement().satisfies(s->assertThat(s.content()).isEqualTo("tool reply"));}
    @Test void agent101_noReplyDoesNotSendAnyMessage(){var f=fixture(ContextBudget.defaults(),Set.of());f.model().enqueue(new ModelResponse(AgentDecision.noReply(),null,null));var result=f.orchestrator().handle(event(f,"u","g1","no-reply-1","silent","N"));assertThat(result.decision().type()).isEqualTo(DecisionType.NO_REPLY);assertThat(f.gateway().sent()).isEmpty();}
    @Test void notice101_lifecycleNoticePersistsButDoesNotInvokeModel(){var f=fixture(ContextBudget.defaults(),Set.of());var notice=f.normalizer().normalize("{\"post_type\":\"notice\",\"notice_type\":\"group_increase\",\"sub_type\":\"approve\",\"user_id\":\"u1\",\"operator_id\":\"admin\",\"group_id\":\"g1\",\"time\":100000002}",Set.of());var result=f.orchestrator().handle(notice);assertThat(result.ignored()).isTrue();assertThat(f.model().receivedContexts()).isEmpty();assertThat(f.gateway().sent()).isEmpty();}
}
