package online.wanan.xingchen.core;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.HttpServer;
import online.wanan.xingchen.adapter.deepseek.*;
import online.wanan.xingchen.core.agent.*;
import online.wanan.xingchen.core.context.*;
import org.junit.jupiter.api.*;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import static org.assertj.core.api.Assertions.*;

class DeepSeekProviderContractTest {
    HttpServer server;AtomicInteger requests;
    @BeforeEach void start() throws Exception {server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);requests=new AtomicInteger();server.start();}
    @AfterEach void stop(){server.stop(0);}
    private DeepSeekProvider provider(int timeout,int retries){return new DeepSeekProvider(new DeepSeekConfiguration("http://127.0.0.1:"+server.getAddress().getPort(),"deepseek-chat","TEST_KEY",1000,timeout,retries,1,256),new ObjectMapper(),Map.of("TEST_KEY","not-a-real-secret"));}
    private ModelRequest request(){var c=new ContextBuilder(ContextBudget.defaults()).build(new ContextBuildInput("rule","persona","qq:u","User","姐姐","g",List.of(),"",List.of(),Map.of(),"hi","",null));return new ModelRequest(c,new AgentToolCatalog().available(CapabilityPolicy.capabilities(AgentRole.SOCIAL,false)));}
    private void respond(int status,String body,long delay){server.createContext("/chat/completions",exchange->{requests.incrementAndGet();exchange.getRequestBody().readAllBytes();if(!"Bearer not-a-real-secret".equals(exchange.getRequestHeaders().getFirst("Authorization"))){exchange.sendResponseHeaders(401,-1);exchange.close();return;}if(delay>0)try{Thread.sleep(delay);}catch(InterruptedException ignored){}byte[] bytes=body.getBytes(StandardCharsets.UTF_8);exchange.getResponseHeaders().add("Content-Type","application/json");exchange.sendResponseHeaders(status,bytes.length);exchange.getResponseBody().write(bytes);exchange.close();});}
    @Test void ds101_textRequestMapsSystemUserAndProviderUsage(){respond(200,"""
      {"choices":[{"message":{"role":"assistant","content":"hello"},"finish_reason":"stop"}],"usage":{"prompt_tokens":12,"prompt_cache_hit_tokens":3,"prompt_cache_miss_tokens":9,"completion_tokens":4,"completion_tokens_details":{"reasoning_tokens":1}}}
      """,0);var result=provider(1000,0).complete(request());assertThat(result.decision().messages()).containsExactly("hello");assertThat(result.finishReason()).isEqualTo(ModelFinishReason.STOP);assertThat(result.usage().inputTokens()).isEqualTo(12);assertThat(result.usage().cacheHitTokens()).isEqualTo(3);assertThat(result.usage().cacheMissTokens()).isEqualTo(9);assertThat(result.usage().outputTokens()).isEqualTo(4);assertThat(result.usage().reasoningTokens()).isEqualTo(1);assertThat(result.usage().provider()).isEqualTo("deepseek");}
    @Test void ds102_toolCallsRemainProviderNeutralAndSchemaIsSent(){respond(200,"""
      {"choices":[{"message":{"content":null,"tool_calls":[{"id":"call-1","type":"function","function":{"name":"qq_reply","arguments":"{\\"messageId\\":\\"9\\",\\"text\\":\\"ok\\"}"}}]},"finish_reason":"tool_calls"}],"usage":{"prompt_tokens":4,"completion_tokens":2}}
      """,0);var result=provider(1000,0).complete(request());assertThat(result.toolCalls()).singleElement().satisfies(c->{assertThat(c.name()).isEqualTo("qq.reply");assertThat(c.arguments()).containsEntry("messageId","9");});assertThat(result.finishReason()).isEqualTo(ModelFinishReason.TOOL_CALLS);}
    @Test void ds103_silentMarkerMapsToFormalNoReply(){respond(200,"{\"choices\":[{\"message\":{\"content\":\"[SILENT]\"},\"finish_reason\":\"stop\"}]}",0);assertThat(provider(1000,0).complete(request()).decision().type()).isEqualTo(DecisionType.NO_REPLY);}
    @Test void ds104_streamEmitsDeltasAndFinalUsage(){server.createContext("/chat/completions",exchange->{requests.incrementAndGet();exchange.getRequestBody().readAllBytes();String s="data: {\"choices\":[{\"delta\":{\"content\":\"hel\"},\"finish_reason\":null}]}\n\n"+"data: {\"choices\":[{\"delta\":{\"content\":\"lo\"},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":3,\"completion_tokens\":2}}\n\n"+"data: [DONE]\n\n";byte[] b=s.getBytes(StandardCharsets.UTF_8);exchange.getResponseHeaders().add("Content-Type","text/event-stream");exchange.sendResponseHeaders(200,b.length);exchange.getResponseBody().write(b);exchange.close();});List<ModelStreamEvent> events=new ArrayList<>();var result=provider(1000,0).stream(request(),events::add);assertThat(events).extracting(ModelStreamEvent::text).containsExactly("hel","lo","");assertThat(events.getLast().complete()).isTrue();assertThat(result.decision().messages()).containsExactly("hello");assertThat(result.usage().outputTokens()).isEqualTo(2);}
    @Test void audit_streamReassemblesFragmentedToolArguments() throws Exception{server.createContext("/chat/completions",exchange->{requests.incrementAndGet();exchange.getRequestBody().readAllBytes();ObjectMapper mapper=new ObjectMapper();var first=mapper.createObjectNode();var firstCall=first.putArray("choices").addObject().putObject("delta").putArray("tool_calls").addObject();firstCall.put("index",0);firstCall.put("id","call-fragmented");firstCall.putObject("function").put("name","qq_reply").put("arguments","{\"messageId\":\"9\",");var second=mapper.createObjectNode();var secondCall=second.putArray("choices").addObject().putObject("delta").putArray("tool_calls").addObject();secondCall.put("index",0);secondCall.putObject("function").put("arguments","\"text\":\"ok\"}");String s="data: "+mapper.writeValueAsString(first)+"\n\n"+"data: "+mapper.writeValueAsString(second)+"\n\n"+"data: {\"choices\":[{\"delta\":{},\"finish_reason\":\"tool_calls\"}]}\n\n"+"data: [DONE]\n\n";byte[] bytes=s.getBytes(StandardCharsets.UTF_8);exchange.getResponseHeaders().add("Content-Type","text/event-stream");exchange.sendResponseHeaders(200,bytes.length);exchange.getResponseBody().write(bytes);exchange.close();});var response=provider(1000,0).stream(request(),e->{});assertThat(response.toolCalls()).singleElement().satisfies(call->{assertThat(call.id()).isEqualTo("call-fragmented");assertThat(call.arguments()).containsEntry("messageId","9").containsEntry("text","ok");});}
    @Test void ds112_fragmentedToolThenDisconnectRetriesBecauseNoCompleteProposalOrEffect() throws Exception{server.createContext("/chat/completions",exchange->{int n=requests.incrementAndGet();exchange.getRequestBody().readAllBytes();exchange.getResponseHeaders().add("Content-Type","text/event-stream");if(n==1){ObjectMapper m=new ObjectMapper();var chunk=m.createObjectNode();var call=chunk.putArray("choices").addObject().putObject("delta").putArray("tool_calls").addObject();call.put("index",0);call.put("id","partial");call.putObject("function").put("name","qq_reply").put("arguments","{\"messageId\":\"");exchange.sendResponseHeaders(200,0);exchange.getResponseBody().write(("data: "+m.writeValueAsString(chunk)+"\n\n").getBytes(StandardCharsets.UTF_8));exchange.getResponseBody().close();return;}String body="data: {\"choices\":[{\"delta\":{\"content\":\"ok\"},\"finish_reason\":\"stop\"}]}\n\ndata: [DONE]\n\n";byte[] bytes=body.getBytes(StandardCharsets.UTF_8);exchange.sendResponseHeaders(200,bytes.length);exchange.getResponseBody().write(bytes);exchange.close();});var result=provider(1000,1).stream(request(),e->{});assertThat(result.decision().messages()).containsExactly("ok");assertThat(requests.get()).isEqualTo(2);}
    @Test void ds113_bufferedPartialOutputThenDisconnectRetriesAndCompletes() throws Exception{server.createContext("/chat/completions",exchange->{int n=requests.incrementAndGet();exchange.getRequestBody().readAllBytes();exchange.getResponseHeaders().add("Content-Type","text/event-stream");exchange.sendResponseHeaders(200,0);if(n==1){exchange.getResponseBody().write("data: {\"choices\":[{\"delta\":{\"content\":\"partial\"}}]}\n\n".getBytes(StandardCharsets.UTF_8));exchange.getResponseBody().close();return;}byte[] body="data: {\"choices\":[{\"delta\":{\"content\":\"complete\"},\"finish_reason\":\"stop\"}]}\n\ndata: [DONE]\n\n".getBytes(StandardCharsets.UTF_8);exchange.getResponseBody().write(body);exchange.close();});List<ModelStreamEvent> events=new ArrayList<>();var result=provider(1000,1).stream(request(),events::add);assertThat(result.decision().messages()).containsExactly("complete");assertThat(events).extracting(ModelStreamEvent::text).containsExactly("partial","complete","");assertThat(requests.get()).isEqualTo(2);}
    @Test void ds114_executedToolStateThenDisconnectDoesNotRetry() throws Exception{server.createContext("/chat/completions",exchange->{requests.incrementAndGet();exchange.getRequestBody().readAllBytes();exchange.getResponseHeaders().add("Content-Type","text/event-stream");exchange.sendResponseHeaders(200,0);exchange.getResponseBody().write("data: {\"choices\":[{\"delta\":{}}]}\n\n".getBytes(StandardCharsets.UTF_8));exchange.getResponseBody().close();});var state=new ModelTurnExecutionState();state.begin();state.toolProposed();state.toolExecuted();var base=request();var req=new ModelRequest(base.context(),base.tools(),base.messages(),64,new CancellationToken(),state);assertThatThrownBy(()->provider(1000,2).stream(req,e->{})).isInstanceOf(ModelProviderException.class);assertThat(state.state()).isEqualTo(ModelTurnExecutionState.State.UNCERTAIN);assertThat(requests.get()).isEqualTo(1);}
    @Test void ds105_serverErrorRetriesWithinConfiguredBound(){server.createContext("/chat/completions",exchange->{int n=requests.incrementAndGet();exchange.getRequestBody().readAllBytes();byte[] b=(n==1?"temporary":"{\"choices\":[{\"message\":{\"content\":\"ok\"},\"finish_reason\":\"stop\"}]}").getBytes(StandardCharsets.UTF_8);exchange.sendResponseHeaders(n==1?503:200,b.length);exchange.getResponseBody().write(b);exchange.close();});assertThat(provider(1000,1).complete(request()).decision().messages()).containsExactly("ok");assertThat(requests.get()).isEqualTo(2);}
    @Test void ds106_rateLimitIsRetryableButBounded(){respond(429,"rate limited",0);assertThatThrownBy(()->provider(1000,1).complete(request())).isInstanceOf(ModelProviderException.class).satisfies(e->{assertThat(((ModelProviderException)e).retryable()).isTrue();assertThat(((ModelProviderException)e).statusCode()).isEqualTo(429);});assertThat(requests.get()).isEqualTo(2);}
    @Test void ds107_clientAuthFailureDoesNotRetry(){respond(401,"secret must not be relayed",0);assertThatThrownBy(()->provider(1000,3).complete(request())).hasMessageContaining("401").hasMessageNotContaining("secret");assertThat(requests.get()).isEqualTo(1);}
    @Test void ds108_malformedProviderJsonIsSanitized(){respond(200,"not json",0);assertThatThrownBy(()->provider(1000,0).complete(request())).hasMessage("malformed DeepSeek response");}
    @Test void ds109_missingKeyFailsBeforeNetwork(){var p=new DeepSeekProvider(new DeepSeekConfiguration("http://127.0.0.1:"+server.getAddress().getPort(),"model","MISSING",1000,1000,0),new ObjectMapper(),Map.of());assertThatThrownBy(()->p.complete(request())).hasMessageContaining("not configured");assertThat(requests.get()).isZero();}
    @Test void ds110_preCancelledRequestNeverConnects(){var r=request();r.cancellation().cancel();assertThatThrownBy(()->provider(1000,0).complete(r)).isInstanceOf(java.util.concurrent.CancellationException.class);assertThat(requests.get()).isZero();}
    @Test void ds111_timeoutIsBoundedAndMarkedRetryable(){respond(200,"{\"choices\":[]}",250);assertThatThrownBy(()->provider(30,0).complete(request())).isInstanceOf(ModelProviderException.class).satisfies(e->assertThat(((ModelProviderException)e).retryable()).isTrue());}
}
