package online.wanan.xingchen.core;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.HttpServer;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;

/** Loopback-only fake OneBot HTTP API plus a minimal test WebSocket endpoint. */
public final class FakeOneBotServer implements AutoCloseable {
    public enum SendBehavior { SEND_SUCCESS, EXPLICIT_FAILURE, PRE_DISPATCH_FAILURE, DROP_AFTER_RECEIVE, TIMEOUT_AFTER_COMMIT }
    private static final String GUID="258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
    private final HttpServer http;private final ServerSocket wsServer;private final ExecutorService executor=Executors.newCachedThreadPool();private final ObjectMapper mapper=new ObjectMapper();private final String httpToken;private final String wsToken;
    private final Map<String,Queue<Integer>> statuses=new ConcurrentHashMap<>();private final Map<String,Queue<Long>> delays=new ConcurrentHashMap<>();private final Map<String,AtomicInteger> counts=new ConcurrentHashMap<>();private final Queue<SendBehavior> sendBehaviors=new ConcurrentLinkedQueue<>();private final AtomicInteger sendReceiveCount=new AtomicInteger(),appliedSendCount=new AtomicInteger();private final List<String> appliedMessageIds=new CopyOnWriteArrayList<>();private volatile Socket activeSocket;private volatile OutputStream activeOutput;private volatile boolean closed;private volatile String lastHttpAuthorization;private volatile String lastWsAuthorization;
    public FakeOneBotServer(String token)throws IOException{this(token,token);}
    public FakeOneBotServer(String httpToken,String wsToken)throws IOException{this.httpToken=httpToken;this.wsToken=wsToken;http=HttpServer.create(new InetSocketAddress(InetAddress.getByName("127.0.0.1"),0),0);http.createContext("/",this::handleHttp);http.setExecutor(executor);http.start();wsServer=new ServerSocket(0,50,InetAddress.getByName("127.0.0.1"));executor.submit(this::acceptSockets);}
    public URI httpUri(){return URI.create("http://127.0.0.1:"+http.getAddress().getPort());}public URI wsUri(){return URI.create("ws://127.0.0.1:"+wsServer.getLocalPort()+"/onebot");}
    public int actionCount(String name){return counts.getOrDefault(name,new AtomicInteger()).get();}public String lastHttpAuthorization(){return lastHttpAuthorization;}public String lastWsAuthorization(){return lastWsAuthorization;}public int wsConnections(){return wsConnections.get();}
    public int sendReceiveCount(){return sendReceiveCount.get();}public int appliedSendCount(){return appliedSendCount.get();}public List<String> appliedMessageIds(){return List.copyOf(appliedMessageIds);}
    private final AtomicInteger wsConnections=new AtomicInteger();
    void failNext(String action,int status){statuses.computeIfAbsent(action,k->new ConcurrentLinkedQueue<>()).add(status);}void delayNext(String action,long millis){delays.computeIfAbsent(action,k->new ConcurrentLinkedQueue<>()).add(millis);}
    void sendBehavior(SendBehavior behavior){sendBehaviors.add(behavior);}
    public online.wanan.xingchen.adapter.onebot.SendReceipt dispatchGroup(online.wanan.xingchen.adapter.onebot.OneBotGateway gateway,String group,String text){
        if(sendBehaviors.peek()==SendBehavior.PRE_DISPATCH_FAILURE){sendBehaviors.poll();return new online.wanan.xingchen.adapter.onebot.SendReceipt(false,"group",group,"fixture-pre-dispatch-failure",online.wanan.xingchen.adapter.onebot.DeliveryStatus.REJECTED);}
        return gateway.sendGroupMessage(group,text);
    }
    public online.wanan.xingchen.adapter.onebot.SendReceipt dispatchPrivate(online.wanan.xingchen.adapter.onebot.OneBotGateway gateway,String user,String text){
        if(sendBehaviors.peek()==SendBehavior.PRE_DISPATCH_FAILURE){sendBehaviors.poll();return new online.wanan.xingchen.adapter.onebot.SendReceipt(false,"private",user,"fixture-pre-dispatch-failure",online.wanan.xingchen.adapter.onebot.DeliveryStatus.REJECTED);}
        return gateway.sendPrivateMessage(user,text);
    }
    private void handleHttp(com.sun.net.httpserver.HttpExchange x)throws IOException{String path=x.getRequestURI().getPath();String action=path.substring(path.lastIndexOf('/')+1);counts.computeIfAbsent(action,k->new AtomicInteger()).incrementAndGet();lastHttpAuthorization=x.getRequestHeaders().getFirst("Authorization");if(httpToken!=null&&!httpToken.isBlank()&&!Objects.equals(lastHttpAuthorization,"Bearer "+httpToken)){x.sendResponseHeaders(401,-1);x.close();return;}JsonNode body=mapper.readTree(x.getRequestBody());boolean sendAction=action.startsWith("send_");SendBehavior behavior=sendAction?Objects.requireNonNullElse(sendBehaviors.poll(),SendBehavior.SEND_SUCCESS):SendBehavior.SEND_SUCCESS;if(sendAction)sendReceiveCount.incrementAndGet();
        if(behavior==SendBehavior.DROP_AFTER_RECEIVE){x.close();return;}
        if(behavior==SendBehavior.EXPLICIT_FAILURE){byte[] failure=mapper.writeValueAsBytes(Map.of("status","failed","retcode",1,"message","explicit fixture rejection"));x.getResponseHeaders().add("Content-Type","application/json");x.sendResponseHeaders(200,failure.length);x.getResponseBody().write(failure);x.close();return;}
        if(sendAction&&(behavior==SendBehavior.SEND_SUCCESS||behavior==SendBehavior.TIMEOUT_AFTER_COMMIT)){appliedSendCount.incrementAndGet();appliedMessageIds.add("fake-"+actionCount(action));}
        Queue<Long> dq=delays.get(action);Long delay=dq==null?null:dq.poll();if(behavior==SendBehavior.TIMEOUT_AFTER_COMMIT&&delay==null)delay=10_000L;if(delay!=null&&delay>0)try{Thread.sleep(delay);}catch(InterruptedException e){Thread.currentThread().interrupt();}Queue<Integer> q=statuses.get(action);Integer status=q==null?null:q.poll();if(status!=null){x.sendResponseHeaders(status,-1);x.close();return;}Object data=switch(action){case "get_login_info"->Map.of("user_id","123456789","nickname","Fake Bot");case "get_group_member_info"->Map.of("user_id",body.path("user_id").asText(),"nickname","Fake User","card","","role","member");case "get_group_member_list"->List.of(Map.of("user_id","u1","nickname","Fake User","card","","role","member"));case "get_msg"->Map.of("message_id",body.path("message_id").asText(),"message_type","group","group_id","g1","user_id","u1","sender",Map.of("user_id","u1","nickname","Fake User"),"message",List.of(Map.of("type","text","data",Map.of("text","quoted"))));case "get_group_msg_history"->Map.of("messages",List.of());default->Map.of("message_id","fake-"+actionCount(action));};byte[] payload=mapper.writeValueAsBytes(Map.of("status","ok","retcode",0,"data",data));x.getResponseHeaders().add("Content-Type","application/json");x.sendResponseHeaders(200,payload.length);x.getResponseBody().write(payload);x.close();}
    private void acceptSockets(){while(!closed)try{Socket s=wsServer.accept();executor.submit(()->handleSocket(s));}catch(IOException e){if(!closed)throw new UncheckedIOException(e);}}
    private void handleSocket(Socket s){try{InputStream in=s.getInputStream();String headers=readHeaders(in);String key=Arrays.stream(headers.split("\\r?\\n")).filter(l->l.toLowerCase(Locale.ROOT).startsWith("sec-websocket-key:")).map(l->l.substring(l.indexOf(':')+1).trim()).findFirst().orElse("");String auth=Arrays.stream(headers.split("\\r?\\n")).filter(l->l.toLowerCase(Locale.ROOT).startsWith("authorization:")).map(l->l.substring(l.indexOf(':')+1).trim()).findFirst().orElse("");lastWsAuthorization=auth.isBlank()?null:auth;if(wsToken!=null&&!wsToken.isBlank()&&!auth.equals("Bearer "+wsToken)){s.getOutputStream().write("HTTP/1.1 401 Unauthorized\r\nContent-Length: 0\r\n\r\n".getBytes(StandardCharsets.US_ASCII));s.close();return;}String accept=Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-1").digest((key+GUID).getBytes(StandardCharsets.US_ASCII)));OutputStream out=s.getOutputStream();out.write(("HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: "+accept+"\r\n\r\n").getBytes(StandardCharsets.US_ASCII));out.flush();activeSocket=s;activeOutput=out;wsConnections.incrementAndGet();while(!closed&&readClientFrame(in)){} }catch(Exception ignored){}finally{if(activeSocket==s){activeSocket=null;activeOutput=null;}try{s.close();}catch(IOException ignored){}}}
    private static String readHeaders(InputStream in)throws IOException{ByteArrayOutputStream b=new ByteArrayOutputStream();int state=0;while(b.size()<16_384){int v=in.read();if(v<0)throw new EOFException();b.write(v);state=switch(state){case 0->v=='\r'?1:0;case 1->v=='\n'?2:0;case 2->v=='\r'?3:0;case 3->v=='\n'?4:0;default->state;};if(state==4)break;}return b.toString(StandardCharsets.US_ASCII);}
    private static boolean readClientFrame(InputStream in)throws IOException{int first=in.read();if(first<0)return false;int second=in.read();if(second<0)return false;int op=first&15;long length=second&127;if(length==126){length=(in.read()<<8)|in.read();}else if(length==127){length=0;for(int i=0;i<8;i++)length=(length<<8)|in.read();}byte[] mask=(second&128)!=0?in.readNBytes(4):new byte[0];if(length>0&&length<1_000_000){byte[] data=in.readNBytes((int)length);if(mask.length==4)for(int i=0;i<data.length;i++)data[i]^=mask[i%4];}return op!=8;}
    void emit(String json)throws IOException{byte[] data=json.getBytes(StandardCharsets.UTF_8);OutputStream out=activeOutput;if(out==null)throw new IllegalStateException("no OneBot WebSocket client connected");synchronized(out){out.write(0x81);if(data.length<126)out.write(data.length);else{out.write(126);out.write((data.length>>8)&255);out.write(data.length&255);}out.write(data);out.flush();}}
    void disconnectWebSocket()throws IOException{Socket s=activeSocket;if(s!=null)s.close();}
    @Override public void close(){closed=true;try{wsServer.close();}catch(IOException ignored){}Socket s=activeSocket;if(s!=null)try{s.close();}catch(IOException ignored){}http.stop(0);executor.shutdownNow();}
}
