package online.wanan.xingchen.core;

import online.wanan.xingchen.core.context.ApproximateTokenEstimator;
import online.wanan.xingchen.core.context.ProviderTokenEstimator;
import online.wanan.xingchen.core.identity.*;
import online.wanan.xingchen.core.memory.*;
import online.wanan.xingchen.core.model.*;
import online.wanan.xingchen.core.relationship.AddressResolution;
import org.junit.jupiter.api.Test;
import java.time.Instant;
import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;

class MemoryPipelineContractTest {
    private final Instant now=Instant.parse("2026-09-30T00:00:00Z");
    private Memory memory(UUID person,UUID conversation,MemoryType type,MemoryScope scope,String text,double importance,Instant updated){return new Memory(UUID.randomUUID(),type,person,scope==MemoryScope.CONVERSATION?conversation:null,null,text,scope,scope==MemoryScope.CONVERSATION?conversation.toString():scope==MemoryScope.PERSON_GLOBAL?person.toString():null,.9,importance,true,now,updated,null,null,MemoryStatus.ACTIVE);}
    private RequestContext request(UUID person,UUID conv,boolean owner){return new RequestContext(person,conv,owner,null);}
    @Test void mem101_retrievalExcludesIneligibleConversationScope(){UUID p=UUID.randomUUID(),c1=UUID.randomUUID(),c2=UUID.randomUUID();var repo=new InMemoryMemoryRepository();var m=memory(p,c1,MemoryType.EPISODIC,MemoryScope.CONVERSATION,"private group fact",1,now);repo.save(m,List.of(new MemorySource(m.id(),"QQ",c1,"m",p,now)));assertThat(new MemoryRetriever(repo,new ApproximateTokenEstimator()).retrieve(request(p,c2,false),"fact",c2,p,100).memories()).isEmpty();}
    @Test void mem102_exactPersonPrecedesMoreImportantLocalConversationMemory(){UUID p=UUID.randomUUID(),c=UUID.randomUUID();var repo=new InMemoryMemoryRepository();var exact=memory(p,c,MemoryType.PERSON,MemoryScope.PERSON_GLOBAL,"person fact",.1,now);var local=memory(UUID.randomUUID(),c,MemoryType.EPISODIC,MemoryScope.CONVERSATION,"group fact",1,now);repo.save(exact,List.of(src(exact,p,c)));repo.save(local,List.of(src(local,p,c)));var got=new MemoryRetriever(repo,new ApproximateTokenEstimator()).retrieve(request(p,c,false),"fact",c,p,100);assertThat(got.memories().getFirst().id()).isEqualTo(exact.id());}
    @Test void mem103_personStableTypesRankAheadOfEpisodicWithinActor(){UUID p=UUID.randomUUID(),c=UUID.randomUUID();var repo=new InMemoryMemoryRepository();var pref=memory(p,c,MemoryType.PREFERENCE,MemoryScope.PERSON_GLOBAL,"tea",.2,now);var episode=memory(p,c,MemoryType.EPISODIC,MemoryScope.PERSON_GLOBAL,"coffee",1,now);repo.save(pref,List.of(src(pref,p,c)));repo.save(episode,List.of(src(episode,p,c)));var got=new MemoryRetriever(repo,new ApproximateTokenEstimator()).retrieve(request(p,c,false),"",c,p,100);assertThat(got.memories().getFirst().type()).isEqualTo(MemoryType.PREFERENCE);}
    @Test void mem104_memoryTokenBudgetIsHardBounded(){UUID p=UUID.randomUUID(),c=UUID.randomUUID();var repo=new InMemoryMemoryRepository();for(int i=0;i<5;i++){var m=memory(p,c,MemoryType.EPISODIC,MemoryScope.PERSON_GLOBAL,"0123456789abcdefghij-"+i,1,now.plusSeconds(i));repo.save(m,List.of(src(m,p,c)));}var result=new MemoryRetriever(repo,new ApproximateTokenEstimator()).retrieve(request(p,c,false),"",c,p,10);assertThat(result.estimatedTokens()).isLessThanOrEqualTo(10);assertThat(result.memories().size()).isLessThan(5);}
    @Test void mem105_exactAndConversationQueriesAreDeduplicated(){UUID p=UUID.randomUUID(),c=UUID.randomUUID();var repo=new InMemoryMemoryRepository();var m=memory(p,c,MemoryType.PERSON,MemoryScope.PERSON_GLOBAL,"fact",.8,now);repo.save(m,List.of(src(m,p,c)));var result=new MemoryRetriever(repo,new ApproximateTokenEstimator()).retrieve(request(p,c,false),"fact",c,p,100);assertThat(result.memories()).filteredOn(x->x.id().equals(m.id())).hasSize(1);}
    @Test void mem106_inactiveAndExpiredRecordsNeverEnterRetrieval(){UUID p=UUID.randomUUID(),c=UUID.randomUUID();var repo=new InMemoryMemoryRepository();var m=memory(p,c,MemoryType.PERSON,MemoryScope.PERSON_GLOBAL,"expired",1,now);var expired=new Memory(m.id(),m.type(),p,null,null,m.content(),m.scopeType(),m.scopeId(),m.confidence(),m.importance(),true,now,now,null,now.minusSeconds(1),MemoryStatus.ACTIVE);repo.save(expired,List.of(src(expired,p,c)));var result=new MemoryRetriever(repo,new ApproximateTokenEstimator()).retrieve(request(p,c,false),"expired",c,p,100);assertThat(result.memories()).isEmpty();}
    @Test void mem107_ownerProjectDecisionIsAccepted(){var eval=new MemoryPolicy().evaluate(candidate(null,MemoryType.PROJECT,MemoryScope.PROJECT),actor("owner",true));assertThat(eval.outcome()).isEqualTo(MemoryPolicy.Outcome.ACCEPT);assertThat(eval.memory().scopeType()).isEqualTo(MemoryScope.PROJECT);}
    @Test void mem108_memberProjectDecisionIsDowngradedWithProvenanceActor(){var member=actor("member",false);var eval=new MemoryPolicy().evaluate(candidate(null,MemoryType.PROJECT,MemoryScope.PROJECT),member);assertThat(eval.outcome()).isEqualTo(MemoryPolicy.Outcome.DOWNGRADE);assertThat(eval.memory().scopeType()).isEqualTo(MemoryScope.CONVERSATION);assertThat(eval.memory().type()).isEqualTo(MemoryType.EPISODIC);assertThat(eval.memory().subjectPersonId()).isEqualTo(member.person().id());}
    @Test void mem108b_memberGlobalCandidateIsDowngradedToCurrentConversation(){var member=actor("member",false);var eval=new MemoryPolicy().evaluate(candidate(null,MemoryType.SEMANTIC,MemoryScope.GLOBAL),member);assertThat(eval.outcome()).isEqualTo(MemoryPolicy.Outcome.DOWNGRADE);assertThat(eval.memory().scopeType()).isEqualTo(MemoryScope.CONVERSATION);}
    @Test void mem108c_ownerStillCannotReadAnotherGroupsConversationMemory(){var repo=new InMemoryMemoryRepository();UUID owner=UUID.randomUUID(),g1=UUID.randomUUID(),g2=UUID.randomUUID();var m=memory(owner,g1,MemoryType.EPISODIC,MemoryScope.CONVERSATION,"only group one",1,now);repo.save(m,List.of(src(m,owner,g1)));assertThat(repo.findByConversation(g1,request(owner,g2,true))).isEmpty();}
    @Test void audit_memoryProjectScopeMustMatchEvenForOwner(){UUID p=UUID.randomUUID(),c=UUID.randomUUID();var m=new Memory(UUID.randomUUID(),MemoryType.PROJECT,p,null,"alpha","project alpha",MemoryScope.PROJECT,"alpha",.9,.9,true,now,now,null,null,MemoryStatus.ACTIVE);assertThat(MemoryVisibility.canRead(m,new RequestContext(p,c,true,"beta"))).isFalse();assertThat(MemoryVisibility.canRead(m,new RequestContext(p,c,true,"alpha"))).isTrue();}
    @Test void audit_personGlobalIsPrivateToSubjectEvenFromOwner(){UUID subject=UUID.randomUUID(),owner=UUID.randomUUID(),c=UUID.randomUUID();var m=memory(subject,c,MemoryType.PERSON,MemoryScope.PERSON_GLOBAL,"private person fact",1,now);assertThat(MemoryVisibility.canRead(m,new RequestContext(owner,c,true,null))).isFalse();assertThat(MemoryVisibility.canRead(m,new RequestContext(subject,c,false,null))).isTrue();}
    @Test void mem109_factCandidateCannotBeAttributedToDifferentPerson(){var member=actor("member",false);var eval=new MemoryPolicy().evaluate(candidate(UUID.randomUUID(),MemoryType.PERSON,MemoryScope.PERSON_GLOBAL),member);assertThat(eval.outcome()).isEqualTo(MemoryPolicy.Outcome.REJECT);}
    @Test void mem110_userFactCandidateSubjectIsSpeakerNotOwner(){var member=actor("member",false);var eval=new MemoryPolicy().evaluate(candidate(null,MemoryType.PERSON,MemoryScope.PERSON_GLOBAL),member);assertThat(eval.memory().subjectPersonId()).isEqualTo(member.person().id()).isNotEqualTo(actor("owner",true).person().id());}
    @Test void mem111_memberCannotCreateOwnerGlobalMemory(){assertThat(new MemoryPolicy().evaluate(candidate(null,MemoryType.PREFERENCE,MemoryScope.OWNER_GLOBAL),actor("member",false)).outcome()).isEqualTo(MemoryPolicy.Outcome.REJECT);}
    private MemoryCandidate candidate(UUID subject,MemoryType type,MemoryScope scope){return new MemoryCandidate(subject,type,"I like cats",scope,null,scope==MemoryScope.PROJECT?"p1":null,.9,.8,true,"m1");}
    private ResolvedActorContext actor(String id,boolean owner){UUID personId=UUID.nameUUIDFromBytes(id.getBytes());var p=new Person(personId,Platform.QQ,id,false,owner);var c=new Conversation(UUID.randomUUID(),new ConversationIdentity(Platform.QQ,ConversationType.GROUP,"g1"));var m=new Membership(UUID.randomUUID(),personId,c.id(),id,null,IdentityRole.MEMBER,now,now);return new ResolvedActorContext(p,c,m,new ActorFlags(false,owner,false,false),id,new AddressResolution(id,"display",null,false,0));}
    private MemorySource src(Memory m,UUID p,UUID c){return new MemorySource(m.id(),"QQ",c,"m-"+m.id(),p,now);}
}
